package org.pms.silverocean.service.leasefinance;

import org.pms.silverocean.database.pms.LateFeeRuleRepo;
import org.pms.silverocean.service.I18NService;
import org.pms.silverocean.service.notification.NotificationDTO;
import org.pms.silverocean.service.notification.NotificationService;
import org.pms.silverocean.service.notification.common.NotificationType;
import org.pms.silverocean.service.property.UnitDao;
import lombok.RequiredArgsConstructor;import org.apache.commons.lang3.StringUtils;import org.pms.silverocean.common.PMSUtils;import org.pms.silverocean.common.ResponseCode;import org.pms.silverocean.database.pms.LeaseFinancialEventRepo;import org.pms.silverocean.database.pms.entities.*;import org.pms.silverocean.service.PMSCustomException;import org.pms.silverocean.service.auth.dao.UserDao;import org.pms.silverocean.service.auth.roles.enums.PMSRole;import org.pms.silverocean.service.lease.LeaseDao;import org.pms.silverocean.service.payment.invoice.InvoiceDao;import org.pms.silverocean.service.payment.ledger.FinancialLedgerService;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import java.math.*;import java.time.ZonedDateTime;import java.util.*;

@Service @RequiredArgsConstructor
public class LeaseFinanceService{
 private final LeaseFinancialEventRepo events;private final LateFeeRuleRepo rules;private final LeaseDao leases;private final InvoiceDao invoices;private final FinancialLedgerService ledger;private final UserDao users;private final NotificationService notifications;private final I18NService i18n;private final UnitDao units;
 @Transactional public LeaseFinancialEvent create(LeaseFinanceModels.Create request){long userId=users.getUserId();Lease lease=writeLease(request.leaseId(),userId);String key=request.idempotencyKey().trim();return events.findByIdempotencyKey(key).map(e->{if(!same(e,request))throw invalid();return e;}).orElseGet(()->append(lease,request,key,userId));}
 public LeaseFinanceModels.Ledger view(long leaseId){long userId=users.getUserId();Lease lease=leases.getLeaseByIdAndStaffOwnerOrTenantId(leaseId,userId).orElseGet(()->privileged()?leases.getLeaseById(leaseId).orElseThrow(this::invalid):null);if(lease==null)throw invalid();return new LeaseFinanceModels.Ledger(events.findAllByLeaseIdOrderByOccurredAtAsc(leaseId),balance(leaseId));}
 @Transactional public LateFeeRule setRule(long leaseId,LeaseFinanceModels.Rule request){long userId=users.getUserId();writeLease(leaseId,userId);if(request.flatAmount().signum()==0&&request.percentageRate().signum()==0)throw invalid();LateFeeRule rule=rules.findByLeaseIdAndActiveTrue(leaseId).orElseGet(LateFeeRule::new);if(rule.getId()==null){rule.setLeaseId(leaseId);rule.setCreatedBy(userId);rule.setActive(true);}rule.setFlatAmount(money(request.flatAmount()));rule.setPercentageRate(request.percentageRate().setScale(4,RoundingMode.HALF_UP));rule.setGraceDays(request.graceDays());rule.setMaximumAmount(request.maximumAmount()==null?null:money(request.maximumAmount()));rule.setEnabled(request.enabled());return rules.save(rule);}
 @Transactional public LeaseFinancialEvent assess(LeaseFinanceModels.Assess request){long userId=users.getUserId();Lease lease=writeLease(request.leaseId(),userId);LateFeeRule rule=rules.findByLeaseIdAndActiveTrue(request.leaseId()).filter(LateFeeRule::isEnabled).orElseThrow(this::invalid);PMSInvoice invoice=invoices.getInvoiceByIdForUpdate(request.invoiceId()).orElseThrow(this::invalid);UnitTenant tenancy=leases.getUnitTenantByTenantId(lease.getTenantId()).orElseThrow(this::invalid);Unit unit=leases.getUnitByTenantId(lease.getTenantId()).orElseThrow(this::invalid);if(invoice.getUnitId()!=unit.getId()||invoice.getBilledUserId()!=tenancy.getUserId()||invoice.isPaid()||invoice.getDueDate()==null||!java.time.LocalDate.now(PMSUtils.getZoneId()).isAfter(invoice.getDueDate().plusDays(rule.getGraceDays()))||events.existsByLeaseIdAndInvoiceIdAndEventType(lease.getId(),invoice.getId(),"LATE_FEE_CHARGED"))throw invalid();BigDecimal base=BigDecimal.valueOf(invoice.getPendingAmount());BigDecimal fee=rule.getFlatAmount().add(base.multiply(rule.getPercentageRate()).divide(new BigDecimal("100"),2,RoundingMode.HALF_UP));if(rule.getMaximumAmount()!=null)fee=fee.min(rule.getMaximumAmount());LeaseFinancialEvent event=create(new LeaseFinanceModels.Create(request.idempotencyKey(),lease.getId(),invoice.getId(),LeaseFinanceModels.Type.LATE_FEE_CHARGED,fee,null,"Late fee assessed after "+rule.getGraceDays()+" grace days"));notifyLateFee(lease,tenancy,unit,invoice,event);return event;}
 private void notifyLateFee(Lease lease,UnitTenant tenancy,Unit unit,PMSInvoice invoice,LeaseFinancialEvent event){String body=String.format(i18n.getLocalizedMessage(NotificationType.RENT_OVERDUE_EMAIL.getBody()),event.getAmount(),event.getCurrency(),invoice.getId(),lease.getId());long ownerId=units.findPropertyOwnerId(unit.getId()).orElseThrow(this::invalid);new HashSet<>(List.of(tenancy.getUserId(),ownerId)).forEach(id->users.findById(id).map(Users::getEmail).filter(StringUtils::isNotBlank).ifPresent(email->notifications.queueNotification(new NotificationDTO(body,email,NotificationType.RENT_OVERDUE_EMAIL))));}
 private LeaseFinancialEvent append(Lease lease,LeaseFinanceModels.Create request,String key,long userId){BigDecimal amount=money(request.amount());validateBalance(lease.getId(),request.type(),amount);UnitTenant tenancy=leases.getUnitTenantByTenantId(lease.getTenantId()).orElseThrow(this::invalid);Unit unit=leases.getUnitByTenantId(lease.getTenantId()).orElseThrow(this::invalid);PMSInvoice invoice=validateInvoice(request,lease,tenancy,unit);String reference=StringUtils.left(StringUtils.trimToNull(request.externalReference()),120);if(List.of(LeaseFinanceModels.Type.DEPOSIT_RECEIVED,LeaseFinanceModels.Type.DEPOSIT_REFUND).contains(request.type())&&reference==null)throw invalid();LeaseFinancialEvent event=new LeaseFinancialEvent(key,lease.getId(),invoice==null?null:invoice.getId(),request.type().name(),amount,StringUtils.defaultIfBlank(lease.getCurrency(),unit.getCurrency()).toUpperCase(Locale.ROOT),reference,StringUtils.left(request.reason().trim(),1000),ZonedDateTime.now(PMSUtils.getZoneId()),userId);event=events.save(event);ledger.recordLeaseFinancialEvent(lease,tenancy,unit,event);return event;}
 private PMSInvoice validateInvoice(LeaseFinanceModels.Create request,Lease lease,UnitTenant tenancy,Unit unit){if(request.invoiceId()==null){if(request.type()==LeaseFinanceModels.Type.CREDIT_NOTE_APPLIED)throw invalid();return null;}PMSInvoice invoice=invoices.getInvoiceByIdForUpdate(request.invoiceId()).orElseThrow(this::invalid);long ownerId=units.findPropertyOwnerId(unit.getId()).orElseThrow(this::invalid);if(invoice.getUnitId()!=unit.getId()||invoice.getBilledUserId()!=tenancy.getUserId()||invoice.getPayToUserId()!=ownerId)throw invalid();if(request.type()==LeaseFinanceModels.Type.CREDIT_NOTE_APPLIED&&invoice.getPendingAmount()<request.amount().doubleValue())throw invalid();if(request.type()==LeaseFinanceModels.Type.CREDIT_NOTE_APPLIED){invoice.setPendingAmount(BigDecimal.valueOf(invoice.getPendingAmount()).subtract(money(request.amount())).max(BigDecimal.ZERO).doubleValue());invoice.setPaid(invoice.getPendingAmount()<=0);invoices.saveInvoice(invoice);}return invoice;}
 private void validateBalance(long leaseId,LeaseFinanceModels.Type type,BigDecimal amount){LeaseFinanceModels.Balance b=balance(leaseId);if((type==LeaseFinanceModels.Type.DEPOSIT_DEDUCTION||type==LeaseFinanceModels.Type.DEPOSIT_REFUND)&&amount.compareTo(b.depositHeld())>0)throw invalid();if(type==LeaseFinanceModels.Type.LATE_FEE_WAIVED&&amount.compareTo(b.lateFeeOutstanding())>0)throw invalid();if(type==LeaseFinanceModels.Type.CREDIT_NOTE_APPLIED&&amount.compareTo(b.unappliedCredit())>0)throw invalid();}
 private LeaseFinanceModels.Balance balance(long id){BigDecimal held=total(id,"DEPOSIT_RECEIVED").subtract(total(id,"DEPOSIT_DEDUCTION")).subtract(total(id,"DEPOSIT_REFUND"));BigDecimal late=total(id,"LATE_FEE_CHARGED").subtract(total(id,"LATE_FEE_WAIVED"));BigDecimal credit=total(id,"CREDIT_NOTE_ISSUED").subtract(total(id,"CREDIT_NOTE_APPLIED"));return new LeaseFinanceModels.Balance(held,late,credit);}
 private BigDecimal total(long id,String type){BigDecimal value=events.total(id,type);return value==null?BigDecimal.ZERO:value;}
 private Lease writeLease(long id,long userId){Lease lease=leases.getLeaseByIdAndStaffOwner(id,userId).orElseGet(()->privileged()?leases.getLeaseById(id).orElse(null):null);if(lease==null)throw invalid();return lease;}
 private boolean privileged(){return users.hasRole(PMSRole.FINANCE)||users.hasRole(PMSRole.SUPER_ADMIN);}
 private boolean same(LeaseFinancialEvent e,LeaseFinanceModels.Create r){return e.getLeaseId()==r.leaseId()&&e.getEventType().equals(r.type().name())&&e.getAmount().compareTo(money(r.amount()))==0&&Objects.equals(e.getInvoiceId(),r.invoiceId());}
 private BigDecimal money(BigDecimal a){return a.setScale(2,RoundingMode.HALF_UP);}private PMSCustomException invalid(){return new PMSCustomException(ResponseCode.GENERAL_FAILURE);}
}
