management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  metrics:
    tags:
      application: slickhood-backend
  endpoint:
    health:
      group:
        production-readiness:
          include: productionReadiness
          show-details: always
