package org.pms.silverocean.service.affiliate;

import lombok.RequiredArgsConstructor;import org.apache.commons.lang3.StringUtils;import org.pms.silverocean.common.ResponseCode;import org.pms.silverocean.database.pms.*;import org.pms.silverocean.database.pms.entities.*;import org.pms.silverocean.service.PMSCustomException;import org.pms.silverocean.service.account.dao.AccountDao;import org.pms.silverocean.service.account.enums.AccountCategory;import org.pms.silverocean.service.auth.dao.UserDao;import org.pms.silverocean.service.auth.roles.enums.PMSRole;import org.pms.silverocean.service.payment.invoice.InvoiceDao;import org.springframework.beans.factory.annotation.Value;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal;import java.math.RoundingMode;import java.time.ZoneId;import java.time.ZonedDateTime;import java.util.List;import java.util.Locale;import java.util.UUID;

@Service @RequiredArgsConstructor
public class AffiliateService {
 private final AffiliateProfileRepo profileRepo;private final AffiliateReferralRepo referralRepo;private final AffiliateCommissionRepo commissionRepo;private final AffiliatePayoutRepo payoutRepo;private final UserDao userDao;private final InvoiceDao invoiceDao;private final AccountDao accountDao;
 @Value("${affiliate.commission-rate:10.00}") private BigDecimal defaultRate;
 @Value("${affiliate.minimum-payout:1000.00}") private BigDecimal defaultMinimumPayout;

 @Transactional public AffiliateProfile ensureProfile(){requireAffiliate();long userId=userDao.getUserId();return profileRepo.findByUserIdAndActiveTrue(userId).orElseGet(()->{AffiliateProfile p=new AffiliateProfile();p.setUserId(userId);p.setCreatedBy(userId);p.setReferralCode(uniqueCode());p.setStatus("ACTIVE");p.setCommissionRate(defaultRate);p.setMinimumPayout(defaultMinimumPayout);p.setCurrency("KES");p.setActive(true);return profileRepo.save(p);});}
 public AffiliateModels.Dashboard dashboard(){AffiliateProfile p=ensureProfile();long id=p.getUserId();List<AffiliateCommission> commissions=commissionRepo.findAllByAffiliateUserIdAndActiveTrueOrderByCreatedOnDesc(id);BigDecimal available=sum(commissions,"EARNED"),lifetime=commissions.stream().filter(c->!"REVERSED".equals(c.getStatus())).map(AffiliateCommission::getCommissionAmount).reduce(BigDecimal.ZERO,BigDecimal::add);BigDecimal pending=payoutRepo.findAllByAffiliateUserIdAndActiveTrueOrderByCreatedOnDesc(id).stream().filter(x->"REQUESTED".equals(x.getStatus())||"PROCESSING".equals(x.getStatus())).map(AffiliatePayout::getAmount).reduce(BigDecimal.ZERO,BigDecimal::add);return new AffiliateModels.Dashboard(p,referralRepo.countByAffiliateUserIdAndActiveTrue(id),referralRepo.countByAffiliateUserIdAndStatusAndActiveTrue(id,"CONVERTED"),available,lifetime,pending,referralRepo.findAllByAffiliateUserIdAndActiveTrueOrderByCreatedOnDesc(id),commissions,payoutRepo.findAllByAffiliateUserIdAndActiveTrueOrderByCreatedOnDesc(id));}
 public AffiliateProfile resolve(String raw){String code=normalize(raw);return profileRepo.findByReferralCodeAndActiveTrue(code).filter(p->"ACTIVE".equals(p.getStatus())).orElseThrow(this::notFound);}
 @Transactional public void attributeRegistration(String rawCode,long referredUserId,String campaign){if(StringUtils.isBlank(rawCode)||referralRepo.findByReferredUserIdAndActiveTrue(referredUserId).isPresent())return;AffiliateProfile p=resolve(rawCode);if(p.getUserId()==referredUserId)throw invalid();AffiliateReferral r=new AffiliateReferral();r.setAffiliateUserId(p.getUserId());r.setReferredUserId(referredUserId);r.setReferralCode(p.getReferralCode());r.setCampaign(StringUtils.left(StringUtils.trimToNull(campaign),100));r.setStatus("REGISTERED");r.setRegisteredAt(now());r.setCreatedBy(p.getUserId());r.setActive(true);referralRepo.save(r);}
 @Transactional public void recordPaidConversion(long invoiceId,String providerReference){if(commissionRepo.existsByInvoiceId(invoiceId))return;PMSInvoice invoice=invoiceDao.getInvoiceById(invoiceId).orElse(null);if(invoice==null||!invoice.isPaid()||invoice.getPendingAmount()>0||!"SUBSCRIPTION".equalsIgnoreCase(invoice.getBillingType()))return;AffiliateReferral referral=referralRepo.findByReferredUserIdAndActiveTrue(invoice.getBilledUserId()).orElse(null);if(referral==null)return;AffiliateProfile profile=profileRepo.findByUserIdAndActiveTrue(referral.getAffiliateUserId()).filter(p->"ACTIVE".equals(p.getStatus())).orElse(null);if(profile==null)return;BigDecimal qualifying=BigDecimal.valueOf(invoice.getAmount());BigDecimal amount=qualifying.multiply(profile.getCommissionRate()).divide(BigDecimal.valueOf(100),2,RoundingMode.HALF_UP);AffiliateCommission c=new AffiliateCommission();c.setAffiliateUserId(profile.getUserId());c.setReferredUserId(invoice.getBilledUserId());c.setInvoiceId(invoiceId);c.setInvoiceRef(invoice.getRef());c.setQualifyingAmount(qualifying);c.setCommissionRate(profile.getCommissionRate());c.setCommissionAmount(amount);c.setCurrency(invoice.getCurrency());c.setStatus("EARNED");c.setProviderReference(StringUtils.left(providerReference,100));c.setEarnedAt(now());c.setCreatedBy(profile.getUserId());c.setActive(true);commissionRepo.save(c);referral.setStatus("CONVERTED");if(referral.getConvertedAt()==null)referral.setConvertedAt(now());referralRepo.save(referral);}
 @Transactional public AffiliateProfile setPayoutAccount(long accountId){AffiliateProfile p=ensureProfile();PaymentAccount a=accountDao.getAccountByIdAndCreatedBy(accountId,p.getUserId());if(!a.isActive()||!a.isVerified()||a.getCategory()== AccountCategory.SLICKHOOD)throw invalid();p.setPayoutAccountId(accountId);return profileRepo.save(p);}
 @Transactional public AffiliatePayout requestPayout(){AffiliateProfile p=ensureProfile();if(p.getPayoutAccountId()==null||payoutRepo.existsByAffiliateUserIdAndStatusAndActiveTrue(p.getUserId(),"REQUESTED")||payoutRepo.existsByAffiliateUserIdAndStatusAndActiveTrue(p.getUserId(),"PROCESSING"))throw invalid();List<AffiliateCommission> earned=commissionRepo.findAllByAffiliateUserIdAndStatusAndActiveTrue(p.getUserId(),"EARNED");BigDecimal amount=earned.stream().filter(c->p.getCurrency().equals(c.getCurrency())).map(AffiliateCommission::getCommissionAmount).reduce(BigDecimal.ZERO,BigDecimal::add);if(amount.compareTo(p.getMinimumPayout())<0)throw new PMSCustomException(ResponseCode.INVALID_AMOUNT);AffiliatePayout payout=new AffiliatePayout();payout.setPayoutNumber("AFP-"+UUID.randomUUID().toString().substring(0,8).toUpperCase(Locale.ROOT));payout.setAffiliateUserId(p.getUserId());payout.setPaymentAccountId(p.getPayoutAccountId());payout.setAmount(amount);payout.setCurrency(p.getCurrency());payout.setStatus("REQUESTED");payout.setRequestedAt(now());payout.setCreatedBy(p.getUserId());payout.setActive(true);payoutRepo.save(payout);earned.stream().filter(c->p.getCurrency().equals(c.getCurrency())).forEach(c->{c.setStatus("PAYOUT_REQUESTED");c.setPayoutId(payout.getId());commissionRepo.save(c);});return payout;}
 public List<AffiliatePayout> adminPayouts(){requireAdmin();return payoutRepo.findAllByActiveTrueOrderByCreatedOnDesc();}
 @Transactional public AffiliatePayout decidePayout(long id,AffiliateModels.PayoutDecision request){requireAdmin();AffiliatePayout payout=payoutRepo.findById(id).filter(AffiliatePayout::isActive).orElseThrow(this::notFound);String next=normalize(request.status());if(!List.of("PROCESSING","PAID","REJECTED").contains(next))throw invalid();if("PROCESSING".equals(next)&&!"REQUESTED".equals(payout.getStatus()))throw invalid();if(List.of("PAID","REJECTED").contains(next)&&!List.of("REQUESTED","PROCESSING").contains(payout.getStatus()))throw invalid();if("PAID".equals(next)&&StringUtils.isBlank(request.paymentReference()))throw invalid();payout.setStatus(next);payout.setPaymentReference(StringUtils.left(StringUtils.trimToNull(request.paymentReference()),100));payout.setNotes(StringUtils.left(StringUtils.trimToNull(request.notes()),1000));if(List.of("PAID","REJECTED").contains(next))payout.setProcessedAt(now());payoutRepo.save(payout);if(List.of("PAID","REJECTED").contains(next))commissionRepo.findAllByPayoutIdAndActiveTrue(id).forEach(c->{c.setStatus("PAID".equals(next)?"PAID":"EARNED");if("REJECTED".equals(next))c.setPayoutId(null);commissionRepo.save(c);});return payout;}
 private BigDecimal sum(List<AffiliateCommission> rows,String status){return rows.stream().filter(c->status.equals(c.getStatus())).map(AffiliateCommission::getCommissionAmount).reduce(BigDecimal.ZERO,BigDecimal::add);}
 private String uniqueCode(){for(int i=0;i<10;i++){String code="SH-"+UUID.randomUUID().toString().replace("-","").substring(0,8).toUpperCase(Locale.ROOT);if(!profileRepo.existsByReferralCode(code))return code;}throw new IllegalStateException("Could not allocate affiliate code");}
 private String normalize(String code){if(StringUtils.isBlank(code))throw invalid();return code.trim().toUpperCase(Locale.ROOT);}
 private void requireAffiliate(){if(!userDao.hasRole(PMSRole.AFFILIATE)&&!userDao.hasRole(PMSRole.SUPER_ADMIN))throw new PMSCustomException(ResponseCode.INVALID_ROLE);}
 private void requireAdmin(){if(!userDao.hasRole(PMSRole.SUPER_ADMIN))throw new PMSCustomException(ResponseCode.INVALID_ROLE);}
 private ZonedDateTime now(){return ZonedDateTime.now(ZoneId.of("UTC"));}private PMSCustomException invalid(){return new PMSCustomException(ResponseCode.INVALID_FIELD_DATA);}private PMSCustomException notFound(){return new PMSCustomException(ResponseCode.RESOURCE_NOT_FOUND);}
}
