package org.pms.silverocean.service.affiliate;

import jakarta.annotation.PostConstruct;import lombok.RequiredArgsConstructor;import org.apache.commons.lang3.StringUtils;import org.pms.silverocean.common.ResponseCode;import org.pms.silverocean.database.pms.*;import org.pms.silverocean.database.pms.entities.*;import org.pms.silverocean.service.PMSCustomException;import org.pms.silverocean.service.account.dao.AccountDao;import org.pms.silverocean.service.account.enums.AccountCategory;import org.pms.silverocean.service.auth.dao.UserDao;import org.pms.silverocean.service.auth.roles.enums.PMSRole;import org.pms.silverocean.service.payment.invoice.InvoiceDao;import org.springframework.beans.factory.annotation.Value;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.scheduling.annotation.Scheduled;
import java.math.BigDecimal;import java.math.RoundingMode;import java.time.ZoneId;import java.time.ZonedDateTime;import java.util.List;import java.util.Locale;import java.util.UUID;import java.util.regex.Pattern;

@Service @RequiredArgsConstructor
public class AffiliateService {
 private static final Pattern REFERRAL_CODE=Pattern.compile("SH-[A-Z0-9]{8,20}");
 private static final Pattern CAMPAIGN=Pattern.compile("[A-Za-z0-9][A-Za-z0-9._-]{0,99}");
 private final AffiliateProfileRepo profileRepo;private final AffiliateReferralRepo referralRepo;private final AffiliateCommissionRepo commissionRepo;private final AffiliatePayoutRepo payoutRepo;private final UserDao userDao;private final InvoiceDao invoiceDao;private final AccountDao accountDao;
 @Value("${affiliate.commission-rate:25.00}") private BigDecimal defaultRate;
 @Value("${affiliate.eligible-payment-count:3}") private int eligiblePaymentCount;
 @Value("${affiliate.minimum-payout:1000.00}") private BigDecimal defaultMinimumPayout;
 @Value("${affiliate.commission-hold-days:14}") private int commissionHoldDays;

 @PostConstruct void validateConfiguration(){if(defaultRate==null||defaultRate.signum()<=0||defaultRate.compareTo(BigDecimal.valueOf(100))>0||eligiblePaymentCount<=0||eligiblePaymentCount>100||defaultMinimumPayout==null||defaultMinimumPayout.signum()<=0||commissionHoldDays<0||commissionHoldDays>365)throw new IllegalStateException("Invalid affiliate financial configuration");}

 @Transactional public AffiliateProfile ensureProfile(){requireAffiliate();long userId=userDao.getUserId();return profileRepo.findByUserIdAndActiveTrue(userId).orElseGet(()->{AffiliateProfile p=new AffiliateProfile();p.setUserId(userId);p.setCreatedBy(userId);p.setReferralCode(uniqueCode());p.setStatus("ACTIVE");p.setCommissionRate(defaultRate);p.setMinimumPayout(defaultMinimumPayout);p.setCurrency("KES");p.setActive(true);return profileRepo.save(p);});}
 public AffiliateModels.Dashboard dashboard(){AffiliateProfile p=ensureProfile();long id=p.getUserId();long referrals=referralRepo.countByAffiliateUserIdAndActiveTrue(id),conversions=referralRepo.countByAffiliateUserIdAndStatusAndActiveTrue(id,"CONVERTED");BigDecimal earned=commissionRepo.sumByStatus(id,p.getCurrency(),"EARNED"),clawback=commissionRepo.sumByStatus(id,p.getCurrency(),"CLAWBACK_DUE"),available=earned.subtract(clawback);var recentReferrals=referralRepo.findTop100ByAffiliateUserIdAndActiveTrueOrderByCreatedOnDesc(id);var recentCommissions=commissionRepo.findTop100ByAffiliateUserIdAndActiveTrueOrderByCreatedOnDesc(id);var recentPayouts=payoutRepo.findTop100ByAffiliateUserIdAndActiveTrueOrderByCreatedOnDesc(id);BigDecimal rate=referrals==0?BigDecimal.ZERO:BigDecimal.valueOf(conversions).multiply(BigDecimal.valueOf(100)).divide(BigDecimal.valueOf(referrals),2,RoundingMode.HALF_UP);return new AffiliateModels.Dashboard(new AffiliateModels.Profile(p),referrals,conversions,rate,available,commissionRepo.sumByStatus(id,p.getCurrency(),"PENDING"),commissionRepo.lifetime(id),payoutRepo.pending(id),recentReferrals.stream().map(AffiliateModels.Referral::new).toList(),recentCommissions.stream().map(AffiliateModels.Commission::new).toList(),recentPayouts.stream().map(AffiliateModels.Payout::new).toList(),referrals>100||recentCommissions.size()==100||recentPayouts.size()==100);}
 public AffiliateProfile resolve(String raw){String code=normalize(raw);if(!REFERRAL_CODE.matcher(code).matches())throw notFound();return profileRepo.findByReferralCodeAndActiveTrue(code).filter(p->"ACTIVE".equals(p.getStatus())).orElseThrow(this::notFound);}
 @Transactional public void attributeRegistration(String rawCode,long referredUserId,String campaign){if(StringUtils.isBlank(rawCode)||referralRepo.findByReferredUserIdAndActiveTrue(referredUserId).isPresent())return;AffiliateProfile p=resolve(rawCode);if(p.getUserId()==referredUserId)throw invalid();String source=StringUtils.trimToNull(campaign);if(source!=null&&!CAMPAIGN.matcher(source).matches())source=null;AffiliateReferral r=new AffiliateReferral();r.setAffiliateUserId(p.getUserId());r.setReferredUserId(referredUserId);r.setReferralCode(p.getReferralCode());r.setCampaign(source);r.setStatus("REGISTERED");r.setRegisteredAt(now());r.setCreatedBy(p.getUserId());r.setActive(true);referralRepo.save(r);}
 @Transactional public void recordPaidConversion(long invoiceId,String providerReference){if(commissionRepo.existsByInvoiceId(invoiceId))return;PMSInvoice invoice=invoiceDao.getInvoiceById(invoiceId).orElse(null);if(invoice==null||!invoice.isPaid()||invoice.getPendingAmount()>0||!"SUBSCRIPTION".equalsIgnoreCase(invoice.getBillingType())||invoice.getAmount()<=0||StringUtils.isBlank(invoice.getCurrency())||StringUtils.isBlank(invoice.getRef()))return;AffiliateReferral referral=referralRepo.findForCommissionByReferredUserId(invoice.getBilledUserId()).orElse(null);if(referral==null||commissionRepo.existsByInvoiceId(invoiceId))return;AffiliateProfile profile=profileRepo.findByUserIdAndActiveTrue(referral.getAffiliateUserId()).filter(p->"ACTIVE".equals(p.getStatus())).orElse(null);if(profile==null)return;long existing=commissionRepo.countByReferredUserIdAndActiveTrue(invoice.getBilledUserId());if(existing>=eligiblePaymentCount)return;int sequence=Math.toIntExact(existing+1);BigDecimal qualifying=BigDecimal.valueOf(invoice.getAmount()).setScale(2,RoundingMode.HALF_UP);BigDecimal amount=qualifying.multiply(defaultRate).divide(BigDecimal.valueOf(100),2,RoundingMode.HALF_UP);if(amount.signum()<=0)return;AffiliateCommission c=new AffiliateCommission();c.setAffiliateUserId(profile.getUserId());c.setReferredUserId(invoice.getBilledUserId());c.setInvoiceId(invoiceId);c.setInvoiceRef(invoice.getRef());c.setQualifyingAmount(qualifying);c.setCommissionRate(defaultRate);c.setCommissionAmount(amount);c.setCurrency(invoice.getCurrency().toUpperCase(Locale.ROOT));c.setStatus(commissionHoldDays==0?"EARNED":"PENDING");c.setEligibleSequence(sequence);c.setProviderReference(StringUtils.left(StringUtils.trimToNull(providerReference),100));c.setEarnedAt(now());c.setAvailableAt(c.getEarnedAt().plusDays(commissionHoldDays));c.setCreatedBy(profile.getUserId());c.setActive(true);commissionRepo.save(c);referral.setStatus("CONVERTED");if(referral.getConvertedAt()==null)referral.setConvertedAt(now());referralRepo.save(referral);}
 @Scheduled(fixedDelayString="${affiliate.commission-release-delay-ms:60000}")@Transactional public void releaseMaturedCommissions(){var rows=commissionRepo.findTop200ByStatusAndActiveTrueAndAvailableAtLessThanEqualOrderByAvailableAtAsc("PENDING",now());rows.forEach(c->c.setStatus("EARNED"));if(!rows.isEmpty())commissionRepo.saveAll(rows);}
 @Transactional public AffiliateModels.Profile setPayoutAccount(long accountId){AffiliateProfile p=ensureProfile();PaymentAccount a=accountDao.getAccountByIdAndCreatedBy(accountId,p.getUserId());if(!a.isActive()||!a.isVerified()||a.getCategory()==AccountCategory.SLICKHOOD)throw invalid();p.setPayoutAccountId(accountId);return new AffiliateModels.Profile(profileRepo.save(p));}
 @Transactional public AffiliateModels.Payout requestPayout(){AffiliateProfile initial=ensureProfile();AffiliateProfile p=profileRepo.findForUpdateByUserId(initial.getUserId()).orElseThrow(this::notFound);if(!"ACTIVE".equals(p.getStatus())||p.getPayoutAccountId()==null||payoutRepo.existsByAffiliateUserIdAndStatusAndActiveTrue(p.getUserId(),"REQUESTED")||payoutRepo.existsByAffiliateUserIdAndStatusAndActiveTrue(p.getUserId(),"PROCESSING"))throw invalid();PaymentAccount account=accountDao.getAccountByIdAndCreatedBy(p.getPayoutAccountId(),p.getUserId());if(!account.isActive()||!account.isVerified()||account.getCategory()==AccountCategory.SLICKHOOD)throw invalid();BigDecimal amount=commissionRepo.sumByStatus(p.getUserId(),p.getCurrency(),"EARNED").subtract(commissionRepo.sumByStatus(p.getUserId(),p.getCurrency(),"CLAWBACK_DUE"));if(amount.compareTo(p.getMinimumPayout())<0)throw new PMSCustomException(ResponseCode.INVALID_AMOUNT);AffiliatePayout payout=new AffiliatePayout();payout.setPayoutNumber("AFP-"+UUID.randomUUID().toString().replace("-","").substring(0,12).toUpperCase(Locale.ROOT));payout.setAffiliateUserId(p.getUserId());payout.setPaymentAccountId(p.getPayoutAccountId());payout.setPayoutAccountName(StringUtils.left(account.getName(),160));payout.setPayoutChannel(account.getChannel().name());payout.setAmount(amount);payout.setCurrency(p.getCurrency());payout.setStatus("REQUESTED");payout.setRequestedAt(now());payout.setCreatedBy(p.getUserId());payout.setActive(true);payout=payoutRepo.save(payout);commissionRepo.claimEarned(p.getUserId(),p.getCurrency(),payout.getId());commissionRepo.claimClawbacks(p.getUserId(),p.getCurrency(),payout.getId());return new AffiliateModels.Payout(payout);}
 public List<AffiliateModels.AdminPayout> adminPayouts(){requireAdmin();return payoutRepo.findTop200ByActiveTrueOrderByCreatedOnDesc().stream().map(AffiliateModels.AdminPayout::new).toList();}
 @Transactional public AffiliateModels.AdminPayout decidePayout(long id,AffiliateModels.PayoutDecision request){requireAdmin();AffiliatePayout payout=payoutRepo.findForUpdate(id).orElseThrow(this::notFound);String next=normalize(request.status());if(!List.of("PROCESSING","PAID","REJECTED").contains(next))throw invalid();if("PROCESSING".equals(next)&&!"REQUESTED".equals(payout.getStatus()))throw invalid();if(List.of("PAID","REJECTED").contains(next)&&!List.of("REQUESTED","PROCESSING").contains(payout.getStatus()))throw invalid();if("PAID".equals(next)&&StringUtils.isBlank(request.paymentReference())||"REJECTED".equals(next)&&StringUtils.isBlank(request.notes()))throw invalid();payout.setStatus(next);payout.setPaymentReference(StringUtils.left(StringUtils.trimToNull(request.paymentReference()),100));payout.setNotes(StringUtils.left(StringUtils.trimToNull(request.notes()),1000));if(List.of("PAID","REJECTED").contains(next)){payout.setProcessedAt(now());payout.setProcessedByUserId(userDao.getUserId());}payoutRepo.save(payout);if("PAID".equals(next)){commissionRepo.settleEarned(id);commissionRepo.settleClawbacks(id);}else if("REJECTED".equals(next)){commissionRepo.releaseEarned(id);commissionRepo.releaseClawbacks(id);}return new AffiliateModels.AdminPayout(payout);}
 @Transactional public void reverseCommission(long invoiceId,String reason){AffiliateCommission c=commissionRepo.findForUpdateByInvoiceId(invoiceId).orElse(null);if(c==null||List.of("REVERSED","CLAWBACK_DUE","CLAWBACK_SETTLED").contains(c.getStatus()))return;if(List.of("PENDING","EARNED").contains(c.getStatus()))c.setStatus("REVERSED");else if("PAID".equals(c.getStatus()))c.setStatus("CLAWBACK_DUE");else if("PAYOUT_REQUESTED".equals(c.getStatus())){AffiliatePayout payout=payoutRepo.findForUpdate(c.getPayoutId()).orElse(null);if(payout!=null&&List.of("REQUESTED","PROCESSING").contains(payout.getStatus())){BigDecimal revised=payout.getAmount().subtract(c.getCommissionAmount());c.setStatus("REVERSED");if(revised.signum()>0)payout.setAmount(revised);else{payout.setAmount(BigDecimal.ZERO);payout.setStatus("REJECTED");payout.setNotes("Automatically cancelled after the qualifying payment was reversed.");payout.setProcessedAt(now());commissionRepo.saveAndFlush(c);commissionRepo.releaseEarned(payout.getId());commissionRepo.releaseClawbacks(payout.getId());}payoutRepo.save(payout);}else c.setStatus("CLAWBACK_DUE");}c.setReversedAt(now());c.setReversalReason(StringUtils.left(StringUtils.defaultIfBlank(StringUtils.trimToNull(reason),"Qualifying payment reversed"),1000));commissionRepo.save(c);}
 private String uniqueCode(){for(int i=0;i<10;i++){String code="SH-"+UUID.randomUUID().toString().replace("-","").substring(0,16).toUpperCase(Locale.ROOT);if(!profileRepo.existsByReferralCode(code))return code;}throw new IllegalStateException("Could not allocate affiliate code");}
 private String normalize(String code){if(StringUtils.isBlank(code))throw invalid();return code.trim().toUpperCase(Locale.ROOT);}
 private void requireAffiliate(){if(!userDao.hasRole(PMSRole.AFFILIATE)&&!userDao.hasRole(PMSRole.SUPER_ADMIN))throw new PMSCustomException(ResponseCode.INVALID_ROLE);}
 private void requireAdmin(){if(!userDao.hasRole(PMSRole.SUPER_ADMIN))throw new PMSCustomException(ResponseCode.INVALID_ROLE);}
 private ZonedDateTime now(){return ZonedDateTime.now(ZoneId.of("UTC"));}private PMSCustomException invalid(){return new PMSCustomException(ResponseCode.INVALID_FIELD_DATA);}private PMSCustomException notFound(){return new PMSCustomException(ResponseCode.RESOURCE_NOT_FOUND);}
}
