package org.pms.silverocean.service.payment.operations;

import org.junit.jupiter.api.BeforeEach;import org.junit.jupiter.api.Test;import org.junit.jupiter.api.extension.ExtendWith;import org.mockito.Mock;import org.mockito.junit.jupiter.MockitoExtension;
import org.pms.silverocean.database.pms.PaymentOperationRepo;import org.pms.silverocean.database.pms.entities.PMSInvoice;import org.pms.silverocean.database.pms.entities.PMSPayment;import org.pms.silverocean.database.pms.entities.PaymentOperation;import org.pms.silverocean.service.PMSCustomException;import org.pms.silverocean.service.auth.dao.UserDao;import org.pms.silverocean.service.auth.roles.enums.PMSRole;import org.pms.silverocean.service.payment.PaymentDao;import org.pms.silverocean.service.payment.invoice.InvoiceDao;import org.pms.silverocean.service.payment.ledger.FinancialLedgerService;
import java.math.BigDecimal;import java.time.ZonedDateTime;import java.util.List;import java.util.Optional;
import static org.junit.jupiter.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class PaymentOperationServiceTest {
 @Mock PaymentOperationRepo operations;@Mock PaymentDao payments;@Mock InvoiceDao invoices;@Mock FinancialLedgerService ledger;@Mock UserDao users;PaymentOperationService service;
 @BeforeEach void setup(){service=new PaymentOperationService(operations,payments,invoices,ledger,users);when(users.hasRole(PMSRole.FINANCE)).thenReturn(true);}
 @Test void confirmedSettlementRequiresProviderReference(){var request=new PaymentOperationModels.Create("k1","c1",3,PaymentOperationModels.Type.SETTLEMENT,PaymentOperationModels.Status.CONFIRMED,new BigDecimal("50"),"PAYSTACK",null,null);assertThrows(PMSCustomException.class,()->service.append(request));verifyNoInteractions(ledger);}
 @Test void cannotRefundMoreThanOriginalPayment(){stubPayment();when(operations.sumConfirmed(3,"REFUND")).thenReturn(new BigDecimal("80"));when(operations.sumConfirmed(3,"REVERSAL")).thenReturn(BigDecimal.ZERO);when(operations.sumConfirmed(3,"CHARGEBACK")).thenReturn(BigDecimal.ZERO);var request=new PaymentOperationModels.Create("k2","c2",3,PaymentOperationModels.Type.REFUND,PaymentOperationModels.Status.CONFIRMED,new BigDecimal("21"),"PAYSTACK","RF-1",null);assertThrows(PMSCustomException.class,()->service.append(request));}
 @Test void terminalCaseCannotReceiveAnotherEvent(){stubPayment();PaymentOperation terminal=new PaymentOperation("old","c3",3,4,"REFUND","CONFIRMED",new BigDecimal("10"),"KES","PAYSTACK","RF-1",null,ZonedDateTime.now(),1);when(operations.findAllByCaseReferenceOrderByOccurredAtAsc("c3")).thenReturn(List.of(terminal));var request=new PaymentOperationModels.Create("k3","c3",3,PaymentOperationModels.Type.REFUND,PaymentOperationModels.Status.CONFIRMED,new BigDecimal("10"),"PAYSTACK","RF-2",null);assertThrows(PMSCustomException.class,()->service.append(request));}
 private void stubPayment(){PMSPayment payment=new PMSPayment();payment.setId(3L);payment.setAmount(100d);payment.setBillReference("INV-1");when(payments.findPaymentByID(3)).thenReturn(Optional.of(payment));PMSInvoice invoice=new PMSInvoice();invoice.setId(4L);invoice.setRef("INV-1");invoice.setCurrency("KES");when(invoices.getInvoiceByRef("INV-1")).thenReturn(Optional.of(invoice));when(operations.findByIdempotencyKey(anyString())).thenReturn(Optional.empty());when(operations.findAllByCaseReferenceOrderByOccurredAtAsc(anyString())).thenReturn(List.of());}
}
