package org.pms.silverocean.service.kyc;

public enum KycDocumentType {
    NATIONAL_ID_FRONT, NATIONAL_ID_BACK, PASSPORT, ALIEN_ID_FRONT, ALIEN_ID_BACK,
    KRA_PIN_CERTIFICATE, SELFIE, BUSINESS_REGISTRATION_CERTIFICATE, CR12,
    PROFESSIONAL_CERTIFICATE, GOOD_CONDUCT_CERTIFICATE, APPOINTMENT_LETTER,
    PROPERTY_OWNERSHIP_DOCUMENT, PROOF_OF_ADDRESS
}
