package org.pms.silverocean.service.insurance;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.*;
import org.mockito.junit.jupiter.MockitoExtension;
import org.pms.silverocean.database.pms.*;
import org.pms.silverocean.database.pms.entities.InsuranceAgency;
import org.pms.silverocean.database.pms.entities.InsuranceCase;
import org.pms.silverocean.database.pms.entities.InsurancePremiumPayment;
import org.pms.silverocean.database.pms.entities.InsuranceClaim;
import org.pms.silverocean.database.pms.entities.InsurancePolicy;
import org.pms.silverocean.database.pms.entities.InsurancePaymentConfiguration;
import org.pms.silverocean.database.pms.entities.InsuranceQuote;
import org.pms.silverocean.service.I18NService;
import org.pms.silverocean.service.PMSCustomException;
import org.pms.silverocean.service.account.AccountService;
import org.pms.silverocean.service.account.dto.AccountDTO;
import org.pms.silverocean.service.account.enums.AccountCategory;
import org.pms.silverocean.service.auth.dao.UserDao;
import org.pms.silverocean.service.auth.roles.enums.Permission;
import org.pms.silverocean.service.auth.roles.enums.PMSRole;
import org.pms.silverocean.service.filestorage.GarageService;
import org.pms.silverocean.service.filestorage.UploadMalwarePolicy;
import org.pms.silverocean.service.notification.NotificationService;
import org.pms.silverocean.service.payment.wrappers.PaymentChannel;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.test.util.ReflectionTestUtils;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.*;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class InsuranceOperationsSecurityTest {
 @Mock InsuranceAgencyRepo agencies;@Mock InsuranceCompanyRepo companies;@Mock InsuranceCaseRepo cases;@Mock InsuranceQuoteRepo quotes;
 @Mock InsurancePremiumPaymentRepo payments;@Mock InsurancePaymentConfigurationRepo paymentConfigurations;@Mock InsurancePolicyRepo policies;@Mock InsuranceClaimRepo claims;@Mock InsuranceDocumentRepo documents;
 @Mock InsuranceActivityRepo activities;@Mock InsuranceStaffDirectoryService staffDirectory;@Mock UserDao users;@Mock AccountService accountsService;@Mock GarageService garage;@Mock UploadMalwarePolicy malwarePolicy;@Mock NotificationService notifications;@Mock I18NService i18n;
 @InjectMocks InsuranceOperationsService service;

 @Test void customerCannotReadAnotherCustomersCase(){when(users.getUserId()).thenReturn(77L);when(cases.findByIdAndCustomerUserIdAndActiveTrue(15,77)).thenReturn(Optional.empty());assertThatThrownBy(()->service.myCase(15)).isInstanceOf(PMSCustomException.class);verify(cases,never()).findById(15L);}
 @Test void applicationCannotBeAssignedToAnUnapprovedUser(){when(staffDirectory.isEligible(901L)).thenReturn(false);assertThatThrownBy(()->service.assign(8,new InsuranceModels.AssignmentRequest(901))).isInstanceOf(PMSCustomException.class);verify(cases,never()).findByIdForUpdate(anyLong());}
 @Test void documentMustHaveExactlyOneAuthorisedParent(){MultipartFile file=mock(MultipartFile.class);assertThatThrownBy(()->service.upload(1L,2L,null,"KYC",file)).isInstanceOf(PMSCustomException.class);verifyNoInteractions(garage);}
 @Test void quoteCannotBeAddedAfterCustomerHasEnteredPaymentFlow(){InsuranceAgency agency=new InsuranceAgency();agency.setId(1L);InsuranceCase insuranceCase=new InsuranceCase();insuranceCase.setId(8L);insuranceCase.setAgencyId(1L);insuranceCase.setStatus("PAYMENT_PENDING");when(cases.findByIdForUpdate(8L)).thenReturn(Optional.of(insuranceCase));when(agencies.findByCodeAndActiveTrue("SILVERWOOD")).thenReturn(Optional.of(agency));assertThatThrownBy(()->service.addQuote(8L,null)).isInstanceOf(PMSCustomException.class);verifyNoInteractions(companies,quotes);}
 @Test void submittedPaymentProofIsImmutable(){InsurancePremiumPayment payment=new InsurancePremiumPayment();payment.setStatus("PENDING_VERIFICATION");payment.setProofFileRef("insurance/existing-proof.pdf");when(payments.findByIdForUpdate(4L)).thenReturn(Optional.of(payment));assertThatThrownBy(()->service.uploadPaymentProof(4L,mock(MultipartFile.class))).isInstanceOf(PMSCustomException.class);verifyNoInteractions(garage,cases);}
 @Test void customerCaseListUsesBoundedBatchQueries(){when(users.getUserId()).thenReturn(77L);InsuranceCase first=new InsuranceCase();first.setId(1L);InsuranceCase second=new InsuranceCase();second.setId(2L);when(cases.findAllByCustomerUserIdAndActiveTrueOrderByCreatedOnDesc(77)).thenReturn(List.of(first,second));when(quotes.findAllByCaseIdInAndActiveTrueOrderByCaseIdAscTotalPremiumAsc(List.of(1L,2L))).thenReturn(List.of());when(payments.findAllByCaseIdInAndActiveTrueOrderByCaseIdAscCreatedOnDesc(List.of(1L,2L))).thenReturn(List.of());service.mine();verify(quotes,times(1)).findAllByCaseIdInAndActiveTrueOrderByCaseIdAscTotalPremiumAsc(anyCollection());verify(payments,times(1)).findAllByCaseIdInAndActiveTrueOrderByCaseIdAscCreatedOnDesc(anyCollection());verify(quotes,never()).findAllByCaseIdAndActiveTrueOrderByTotalPremiumAsc(anyLong());}
 @Test void customerCannotWithdrawAfterEnteringPaymentFlow(){InsuranceAgency agency=new InsuranceAgency();agency.setId(1L);InsuranceCase insuranceCase=new InsuranceCase();insuranceCase.setId(8L);insuranceCase.setAgencyId(1L);insuranceCase.setCustomerUserId(77L);insuranceCase.setStatus("PAYMENT_PENDING");when(users.getUserId()).thenReturn(77L);when(agencies.findByCodeAndActiveTrue("SILVERWOOD")).thenReturn(Optional.of(agency));when(cases.findByIdForUpdate(8L)).thenReturn(Optional.of(insuranceCase));assertThatThrownBy(()->service.withdraw(8L)).isInstanceOf(PMSCustomException.class);verify(cases,never()).save(any());verifyNoInteractions(activities);}
 @Test void operationsSummaryUsesAgencyScopedCounts(){InsuranceAgency agency=new InsuranceAgency();agency.setId(12L);when(agencies.findByCodeAndActiveTrue("SILVERWOOD")).thenReturn(Optional.of(agency));service.summary();verify(cases).countByAgencyIdAndActiveTrueAndStatusNotIn(eq(12L),anySet());verify(cases).countByAgencyIdAndActiveTrueAndAssignedAdviserIdIsNullAndStatusNotIn(eq(12L),anySet());verify(payments).countByAgencyIdAndStatus(12L,"PENDING_VERIFICATION");verify(claims).countOpenByAgencyId(eq(12L),anySet());verify(policies).countRenewalsByAgencyId(eq(12L),any(),any());}
 @Test void staffCannotMutateAClaimOwnedByAnotherAgency(){InsuranceAgency agency=new InsuranceAgency();agency.setId(12L);InsuranceClaim claim=new InsuranceClaim();claim.setId(5L);claim.setPolicyId(6L);claim.setStatus("SUBMITTED");InsurancePolicy policy=new InsurancePolicy();policy.setId(6L);policy.setCaseId(7L);InsuranceCase foreignCase=new InsuranceCase();foreignCase.setId(7L);foreignCase.setAgencyId(99L);foreignCase.setActive(true);when(agencies.findByCodeAndActiveTrue("SILVERWOOD")).thenReturn(Optional.of(agency));when(claims.findByIdForUpdate(5L)).thenReturn(Optional.of(claim));when(policies.findById(6L)).thenReturn(Optional.of(policy));when(cases.findById(7L)).thenReturn(Optional.of(foreignCase));assertThatThrownBy(()->service.updateClaim(5L,new InsuranceModels.ClaimStatusRequest("ACKNOWLEDGED",null,null))).isInstanceOf(PMSCustomException.class);verify(claims,never()).save(any());verifyNoInteractions(activities);}
 @Test void recordedPaymentIsBoundToTheVerifiedInsurerDestination(){InsuranceAgency agency=new InsuranceAgency();agency.setId(1L);InsuranceCase insuranceCase=new InsuranceCase();insuranceCase.setId(8L);insuranceCase.setAgencyId(1L);insuranceCase.setCustomerUserId(77L);insuranceCase.setStatus("CUSTOMER_SELECTED");insuranceCase.setSelectedQuoteId(9L);InsuranceQuote quote=new InsuranceQuote();quote.setId(9L);quote.setCompanyId(3L);quote.setTotalPremium(new BigDecimal("25000.00"));quote.setCurrency("KES");InsurancePaymentConfiguration configuration=new InsurancePaymentConfiguration();configuration.setId(6L);configuration.setCompanyId(3L);configuration.setPaymentAccountId(12L);configuration.setPaymentChannel(PaymentChannel.MPESA);configuration.setEffectiveFrom(LocalDate.now().minusDays(1));configuration.setActive(true);AccountDTO account=new AccountDTO(12L,"APA Premiums",AccountCategory.INSURANCE,PaymentChannel.MPESA,null,"M-Pesa",true,true,null,List.of());when(users.getUserId()).thenReturn(77L);when(agencies.findByCodeAndActiveTrue("SILVERWOOD")).thenReturn(Optional.of(agency));when(cases.findByIdForUpdate(8L)).thenReturn(Optional.of(insuranceCase));when(quotes.findByIdAndCaseIdAndActiveTrue(9L,8L)).thenReturn(Optional.of(quote));when(paymentConfigurations.findById(6L)).thenReturn(Optional.of(configuration));when(accountsService.getAccountStatus(12L)).thenReturn(account);when(payments.save(any())).thenAnswer(invocation->{InsurancePremiumPayment saved=invocation.getArgument(0);saved.setId(20L);return saved;});InsuranceModels.PaymentView result=service.recordPayment(8L,new InsuranceModels.PaymentRequest(6L,new BigDecimal("25000.00"),"KES","APA-123",LocalDateTime.now()));assertThat(result.paymentConfigurationId()).isEqualTo(6L);verify(payments).save(argThat(payment->Objects.equals(payment.getPaymentConfigurationId(),6L)));}
 @Test void customerCannotOpenAnotherCustomersPaymentEvidence(){InsuranceAgency agency=new InsuranceAgency();agency.setId(1L);InsurancePremiumPayment payment=new InsurancePremiumPayment();payment.setCaseId(8L);payment.setProofFileRef("insurance/private/evidence.pdf");payment.setActive(true);InsuranceCase insuranceCase=new InsuranceCase();insuranceCase.setId(8L);insuranceCase.setAgencyId(1L);insuranceCase.setCustomerUserId(77L);insuranceCase.setActive(true);when(users.getUserId()).thenReturn(99L);when(payments.findByIdAndActiveTrue(4L)).thenReturn(Optional.of(payment));when(cases.findById(8L)).thenReturn(Optional.of(insuranceCase));when(agencies.findByCodeAndActiveTrue("SILVERWOOD")).thenReturn(Optional.of(agency));when(users.hasPermission(Permission.VERIFY_INSURANCE_PAYMENTS)).thenReturn(false);assertThatThrownBy(()->service.paymentProof(4L)).isInstanceOf(PMSCustomException.class);verifyNoInteractions(garage);}
 @Test void authorisedVerifierReceivesOnlyAnExpiringEvidenceUrl(){InsuranceAgency agency=new InsuranceAgency();agency.setId(1L);InsurancePremiumPayment payment=new InsurancePremiumPayment();payment.setCaseId(8L);payment.setProofFileRef("insurance/private/evidence.pdf");payment.setActive(true);InsuranceCase insuranceCase=new InsuranceCase();insuranceCase.setId(8L);insuranceCase.setAgencyId(1L);insuranceCase.setCustomerUserId(77L);insuranceCase.setActive(true);when(users.getUserId()).thenReturn(99L);when(users.hasPermission(Permission.VERIFY_INSURANCE_PAYMENTS)).thenReturn(true);when(payments.findByIdAndActiveTrue(4L)).thenReturn(Optional.of(payment));when(cases.findById(8L)).thenReturn(Optional.of(insuranceCase));when(agencies.findByCodeAndActiveTrue("SILVERWOOD")).thenReturn(Optional.of(agency));when(garage.getPresignedUrlForStoredObject("insurance/private/evidence.pdf")).thenReturn("https://files.example/evidence?expires=60");assertThat(service.paymentProof(4L)).isEqualTo("https://files.example/evidence?expires=60");verify(garage).getPresignedUrlForStoredObject("insurance/private/evidence.pdf");}
 @Test void staffCannotManuallyMarkARenewalPaidWithoutVerifiedEvidence(){assertThatThrownBy(()->service.renewal(4L,new InsuranceModels.RenewalRequest("PAID"))).isInstanceOf(PMSCustomException.class);verifyNoInteractions(policies);}
 @Test void motorProposalAcceptsMultipleVehicles(){assertThatCode(()->ReflectionTestUtils.invokeMethod(service,"validateProposal","MOTOR","VEHICLE",Map.of("vehicles",List.of(Map.of("insuredType","VEHICLE","registrationNumber","KDA 123A","makeModel","Toyota Fielder","driverAge","36"),Map.of("insuredType","PRIME_MOVER","registrationNumber","KDB 456B","makeModel","Mercedes Actros","driverAge","42"))))).doesNotThrowAnyException();}
 @Test void motorProposalRequiresRegistrationNumber(){assertThatThrownBy(()->ReflectionTestUtils.invokeMethod(service,"validateProposal","MOTOR","VEHICLE",Map.of("vehicles",List.of(Map.of("insuredType","VEHICLE","makeModel","Toyota Fielder","driverAge","36"))))).isInstanceOf(PMSCustomException.class);}
 @Test void specialPurposeMotorProposalRequiresEquipmentType(){assertThatThrownBy(()->ReflectionTestUtils.invokeMethod(service,"validateProposal","MOTOR","SPECIAL_TYPE",Map.of("vehicles",List.of(Map.of("insuredType","SPECIAL_TYPE","registrationNumber","KDC 789C","makeModel","Caterpillar 320","driverAge","40"))))).isInstanceOf(PMSCustomException.class);}
 @Test void domesticBuildingsRequireALandlordRole(){when(users.hasRole(PMSRole.LANDLORD)).thenReturn(false);assertThatThrownBy(()->ReflectionTestUtils.invokeMethod(service,"validateProposal","DOMESTIC","PROPERTY",Map.of("domesticItems",List.of(Map.of("propertyLocation","Nairobi","itemDescription","Apartment block"))))).isInstanceOf(PMSCustomException.class);}
 @Test void domesticProposalAcceptsMultipleInsuredItems(){when(users.hasRole(PMSRole.LANDLORD)).thenReturn(true);assertThatCode(()->ReflectionTestUtils.invokeMethod(service,"validateProposal","DOMESTIC","PROPERTY",Map.of("domesticItems",List.of(Map.of("propertyLocation","Nairobi","itemDescription","Main house"),Map.of("propertyLocation","Nairobi","itemDescription","Detached garage"))))).doesNotThrowAnyException();}
 @Test void fireProposalAcceptsMultipleValuedItems(){assertThatCode(()->ReflectionTestUtils.invokeMethod(service,"validateProposal","FIRE_ALLIED","PROPERTY",Map.of("insuredItems",List.of(Map.of("description","Building","value","9000000"),Map.of("description","Equipment","value","1200000"))))).doesNotThrowAnyException();}
 @Test void wibaProposalPersistsTrustedCalculatedPayrollColumns(){Map<String,Object> normalized=ReflectionTestUtils.invokeMethod(service,"normalizedProposal","WIBA_EL",Map.of("workforce",List.of(Map.of("jobDescription","Caretaker","monthlySalary","30000","employeeCount","2"))));Map<?,?> row=(Map<?,?>)((List<?>)normalized.get("workforce")).getFirst();assertThat(row.get("monthlySubtotal")).isEqualTo(new BigDecimal("60000"));assertThat(row.get("annualSalary")).isEqualTo(new BigDecimal("720000"));}
 @Test void wibaProposalAcceptsMultipleJobGroups(){assertThatCode(()->ReflectionTestUtils.invokeMethod(service,"validateProposal","WIBA_EL","EMPLOYEES",Map.of("workforce",List.of(Map.of("jobDescription","Caretaker","monthlySalary","30000","employeeCount","2"),Map.of("jobDescription","Guard","monthlySalary","25000","employeeCount","4"))))).doesNotThrowAnyException();}
 @Test void contractorsProposalAcceptsMultipleProjects(){assertThatCode(()->ReflectionTestUtils.invokeMethod(service,"validateProposal","CONTRACTORS_ALL_RISK","PROJECT",Map.of("projects",List.of(Map.of("projectValue","9000000","projectName","Tower A","projectSiteLocation","Nairobi","constructionType","Residential","thirdPartyLiabilityEstimate","1000000"),Map.of("projectValue","7000000","projectName","Tower B","projectSiteLocation","Nairobi","constructionType","Residential","thirdPartyLiabilityEstimate","800000"))))).doesNotThrowAnyException();}
 @Test void medicalProposalRejectsFreeTextGender(){assertThatThrownBy(()->ReflectionTestUtils.invokeMethod(service,"validateProposal","MEDICAL","FAMILY_INDIVIDUAL",Map.of("clientName","Amina","clientDateOfBirth","1990-01-01","clientGender","Other","inPatientLimit","500000"))).isInstanceOf(PMSCustomException.class);}
 @Test void familyMedicalProposalAcceptsMultipleAdditionalMembers(){assertThatCode(()->ReflectionTestUtils.invokeMethod(service,"validateProposal","MEDICAL","FAMILY_INDIVIDUAL",Map.of("clientDateOfBirth","1990-01-01","clientGender","FEMALE","inPatientLimit","500000","outPatientRequired",false,"otherMembers",List.of(Map.of("fullName","Child One","dateOfBirth","2015-01-01","gender","MALE"),Map.of("fullName","Child Two","dateOfBirth","2018-01-01","gender","FEMALE"))))).doesNotThrowAnyException();}
 @Test void corporateMedicalProposalAcceptsMultipleStaffMembers(){assertThatCode(()->ReflectionTestUtils.invokeMethod(service,"validateProposal","MEDICAL","CORPORATE",Map.of("companyName","Acme Limited","waitingPeriod","NO_WAITING_PERIOD","staffMembers",List.of(Map.of("fullName","Staff One","dateOfBirth","1990-01-01","gender","MALE"),Map.of("fullName","Staff Two","dateOfBirth","1992-02-02","gender","FEMALE"))))).doesNotThrowAnyException();}
 @Test void marineProposalRequiresAnIdfNumber(){assertThatThrownBy(()->ReflectionTestUtils.invokeMethod(service,"validateProposal","MARINE_CARGO","GOODS",Map.of("consignments",List.of(Map.of("transportMode","SEA"))))).isInstanceOf(PMSCustomException.class);}
 @Test void marineProposalAcceptsSeveralConsignments(){assertThatCode(()->ReflectionTestUtils.invokeMethod(service,"validateProposal","MARINE_CARGO","GOODS",Map.of("consignments",List.of(Map.of("idfNumber","IDF-1","transportMode","SEA"),Map.of("idfNumber","IDF-2","transportMode","AIR"))))).doesNotThrowAnyException();}
 @Test void travelProposalAcceptsMultipleTrips(){assertThatCode(()->ReflectionTestUtils.invokeMethod(service,"validateProposal","TRAVEL","PERSON",Map.of("trips",List.of(Map.of("dateOfBirth","1990-01-01","travelDuration","14 days","destination","Rwanda","purpose","Business"),Map.of("dateOfBirth","1990-01-01","travelDuration","7 days","destination","Tanzania","purpose","Holiday"))))).doesNotThrowAnyException();}
 @Test void goodsInTransitRequiresExplicitRiskAnswers(){Map<String,Object> proposal=new HashMap<>();proposal.put("cargoItems",List.of(Map.of("singleCarryValue","100000","annualCarryValue","1000000","cargoDescription","Packaged food")));proposal.put("conveyanceMode","Road");proposal.put("territorialLimits","Kenya");proposal.put("packaging","Sealed cartons");proposal.put("temporaryGarageSafety","Guarded yard");assertThatThrownBy(()->ReflectionTestUtils.invokeMethod(service,"validateProposal","GOODS_IN_TRANSIT","GOODS",proposal)).isInstanceOf(PMSCustomException.class);}
 @Test void goodsInTransitAcceptsSpecifiedPrimeMoverDetails(){Map<String,Object> proposal=new HashMap<>();proposal.put("cargoItems",List.of(Map.of("singleCarryValue","100000","annualCarryValue","1000000","cargoDescription","Packaged food"),Map.of("singleCarryValue","50000","annualCarryValue","300000","cargoDescription","Furniture")));proposal.put("conveyanceMode","Road");proposal.put("territorialLimits","Kenya");proposal.put("packaging","Sealed cartons");proposal.put("temporaryGarageSafety","Guarded yard");proposal.put("usesHiredVehicles","NO");proposal.put("trackingDevices","YES");proposal.put("engineImmobilizers","YES");proposal.put("specifiedVehicleCover","YES");proposal.put("specifiedVehicles",List.of(Map.of("vehicleType","PRIME_MOVER","make","Mercedes","registrationNumber","KDA 123A","tonnage","20","sumInsured","8000000")));assertThatCode(()->ReflectionTestUtils.invokeMethod(service,"validateProposal","GOODS_IN_TRANSIT","GOODS",proposal)).doesNotThrowAnyException();}
 @Test void marineQuoteCannotBeSentWithoutItsCommercialInvoice(){InsuranceAgency agency=new InsuranceAgency();agency.setId(1L);InsuranceCase insuranceCase=new InsuranceCase();insuranceCase.setId(8L);insuranceCase.setAgencyId(1L);insuranceCase.setProductCode("MARINE_CARGO");insuranceCase.setActive(true);when(agencies.findByCodeAndActiveTrue("SILVERWOOD")).thenReturn(Optional.of(agency));when(cases.findById(8L)).thenReturn(Optional.of(insuranceCase));when(documents.findAllByCaseIdAndActiveTrueOrderByCreatedOnDesc(8L)).thenReturn(List.of());assertThatThrownBy(()->service.requestInsurerQuote(8L,new InsuranceModels.QuoteDispatchRequest("APA"))).isInstanceOf(PMSCustomException.class);}
}
