package org.pms.silverocean.service.insurance;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.*;
import org.mockito.junit.jupiter.MockitoExtension;
import org.pms.silverocean.database.pms.*;
import org.pms.silverocean.database.pms.entities.InsuranceAgency;
import org.pms.silverocean.database.pms.entities.InsuranceCase;
import org.pms.silverocean.database.pms.entities.InsurancePremiumPayment;
import org.pms.silverocean.database.pms.entities.InsuranceClaim;
import org.pms.silverocean.database.pms.entities.InsurancePolicy;
import org.pms.silverocean.database.pms.entities.InsurancePaymentConfiguration;
import org.pms.silverocean.database.pms.entities.InsuranceQuote;
import org.pms.silverocean.service.I18NService;
import org.pms.silverocean.service.PMSCustomException;
import org.pms.silverocean.service.account.AccountService;
import org.pms.silverocean.service.account.dto.AccountDTO;
import org.pms.silverocean.service.account.enums.AccountCategory;
import org.pms.silverocean.service.auth.dao.UserDao;
import org.pms.silverocean.service.auth.roles.enums.Permission;
import org.pms.silverocean.service.filestorage.GarageService;
import org.pms.silverocean.service.filestorage.UploadMalwarePolicy;
import org.pms.silverocean.service.notification.NotificationService;
import org.pms.silverocean.service.payment.wrappers.PaymentChannel;
import org.springframework.web.multipart.MultipartFile;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.*;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class InsuranceOperationsSecurityTest {
 @Mock InsuranceAgencyRepo agencies;@Mock InsuranceCompanyRepo companies;@Mock InsuranceCaseRepo cases;@Mock InsuranceQuoteRepo quotes;
 @Mock InsurancePremiumPaymentRepo payments;@Mock InsurancePaymentConfigurationRepo paymentConfigurations;@Mock InsurancePolicyRepo policies;@Mock InsuranceClaimRepo claims;@Mock InsuranceDocumentRepo documents;
 @Mock InsuranceActivityRepo activities;@Mock InsuranceStaffDirectoryService staffDirectory;@Mock UserDao users;@Mock AccountService accountsService;@Mock GarageService garage;@Mock UploadMalwarePolicy malwarePolicy;@Mock NotificationService notifications;@Mock I18NService i18n;
 @InjectMocks InsuranceOperationsService service;

 @Test void customerCannotReadAnotherCustomersCase(){when(users.getUserId()).thenReturn(77L);when(cases.findByIdAndCustomerUserIdAndActiveTrue(15,77)).thenReturn(Optional.empty());assertThatThrownBy(()->service.myCase(15)).isInstanceOf(PMSCustomException.class);verify(cases,never()).findById(15L);}
 @Test void applicationCannotBeAssignedToAnUnapprovedUser(){when(staffDirectory.isEligible(901L)).thenReturn(false);assertThatThrownBy(()->service.assign(8,new InsuranceModels.AssignmentRequest(901))).isInstanceOf(PMSCustomException.class);verify(cases,never()).findByIdForUpdate(anyLong());}
 @Test void documentMustHaveExactlyOneAuthorisedParent(){MultipartFile file=mock(MultipartFile.class);assertThatThrownBy(()->service.upload(1L,2L,null,"KYC",file)).isInstanceOf(PMSCustomException.class);verifyNoInteractions(garage);}
 @Test void quoteCannotBeAddedAfterCustomerHasEnteredPaymentFlow(){InsuranceAgency agency=new InsuranceAgency();agency.setId(1L);InsuranceCase insuranceCase=new InsuranceCase();insuranceCase.setId(8L);insuranceCase.setAgencyId(1L);insuranceCase.setStatus("PAYMENT_PENDING");when(cases.findByIdForUpdate(8L)).thenReturn(Optional.of(insuranceCase));when(agencies.findByCodeAndActiveTrue("SILVERWOOD")).thenReturn(Optional.of(agency));assertThatThrownBy(()->service.addQuote(8L,null)).isInstanceOf(PMSCustomException.class);verifyNoInteractions(companies,quotes);}
 @Test void submittedPaymentProofIsImmutable(){InsurancePremiumPayment payment=new InsurancePremiumPayment();payment.setStatus("PENDING_VERIFICATION");payment.setProofFileRef("insurance/existing-proof.pdf");when(payments.findByIdForUpdate(4L)).thenReturn(Optional.of(payment));assertThatThrownBy(()->service.uploadPaymentProof(4L,mock(MultipartFile.class))).isInstanceOf(PMSCustomException.class);verifyNoInteractions(garage,cases);}
 @Test void customerCaseListUsesBoundedBatchQueries(){when(users.getUserId()).thenReturn(77L);InsuranceCase first=new InsuranceCase();first.setId(1L);InsuranceCase second=new InsuranceCase();second.setId(2L);when(cases.findAllByCustomerUserIdAndActiveTrueOrderByCreatedOnDesc(77)).thenReturn(List.of(first,second));when(quotes.findAllByCaseIdInAndActiveTrueOrderByCaseIdAscTotalPremiumAsc(List.of(1L,2L))).thenReturn(List.of());when(payments.findAllByCaseIdInAndActiveTrueOrderByCaseIdAscCreatedOnDesc(List.of(1L,2L))).thenReturn(List.of());service.mine();verify(quotes,times(1)).findAllByCaseIdInAndActiveTrueOrderByCaseIdAscTotalPremiumAsc(anyCollection());verify(payments,times(1)).findAllByCaseIdInAndActiveTrueOrderByCaseIdAscCreatedOnDesc(anyCollection());verify(quotes,never()).findAllByCaseIdAndActiveTrueOrderByTotalPremiumAsc(anyLong());}
 @Test void customerCannotWithdrawAfterEnteringPaymentFlow(){InsuranceAgency agency=new InsuranceAgency();agency.setId(1L);InsuranceCase insuranceCase=new InsuranceCase();insuranceCase.setId(8L);insuranceCase.setAgencyId(1L);insuranceCase.setCustomerUserId(77L);insuranceCase.setStatus("PAYMENT_PENDING");when(users.getUserId()).thenReturn(77L);when(agencies.findByCodeAndActiveTrue("SILVERWOOD")).thenReturn(Optional.of(agency));when(cases.findByIdForUpdate(8L)).thenReturn(Optional.of(insuranceCase));assertThatThrownBy(()->service.withdraw(8L)).isInstanceOf(PMSCustomException.class);verify(cases,never()).save(any());verifyNoInteractions(activities);}
 @Test void operationsSummaryUsesAgencyScopedCounts(){InsuranceAgency agency=new InsuranceAgency();agency.setId(12L);when(agencies.findByCodeAndActiveTrue("SILVERWOOD")).thenReturn(Optional.of(agency));service.summary();verify(cases).countByAgencyIdAndActiveTrueAndStatusNotIn(eq(12L),anySet());verify(cases).countByAgencyIdAndActiveTrueAndAssignedAdviserIdIsNullAndStatusNotIn(eq(12L),anySet());verify(payments).countByAgencyIdAndStatus(12L,"PENDING_VERIFICATION");verify(claims).countOpenByAgencyId(eq(12L),anySet());verify(policies).countRenewalsByAgencyId(eq(12L),any(),any());}
 @Test void staffCannotMutateAClaimOwnedByAnotherAgency(){InsuranceAgency agency=new InsuranceAgency();agency.setId(12L);InsuranceClaim claim=new InsuranceClaim();claim.setId(5L);claim.setPolicyId(6L);claim.setStatus("SUBMITTED");InsurancePolicy policy=new InsurancePolicy();policy.setId(6L);policy.setCaseId(7L);InsuranceCase foreignCase=new InsuranceCase();foreignCase.setId(7L);foreignCase.setAgencyId(99L);foreignCase.setActive(true);when(agencies.findByCodeAndActiveTrue("SILVERWOOD")).thenReturn(Optional.of(agency));when(claims.findByIdForUpdate(5L)).thenReturn(Optional.of(claim));when(policies.findById(6L)).thenReturn(Optional.of(policy));when(cases.findById(7L)).thenReturn(Optional.of(foreignCase));assertThatThrownBy(()->service.updateClaim(5L,new InsuranceModels.ClaimStatusRequest("ACKNOWLEDGED",null,null))).isInstanceOf(PMSCustomException.class);verify(claims,never()).save(any());verifyNoInteractions(activities);}
 @Test void recordedPaymentIsBoundToTheVerifiedInsurerDestination(){InsuranceAgency agency=new InsuranceAgency();agency.setId(1L);InsuranceCase insuranceCase=new InsuranceCase();insuranceCase.setId(8L);insuranceCase.setAgencyId(1L);insuranceCase.setCustomerUserId(77L);insuranceCase.setStatus("CUSTOMER_SELECTED");insuranceCase.setSelectedQuoteId(9L);InsuranceQuote quote=new InsuranceQuote();quote.setId(9L);quote.setCompanyId(3L);quote.setTotalPremium(new BigDecimal("25000.00"));quote.setCurrency("KES");InsurancePaymentConfiguration configuration=new InsurancePaymentConfiguration();configuration.setId(6L);configuration.setCompanyId(3L);configuration.setPaymentAccountId(12L);configuration.setPaymentChannel(PaymentChannel.MPESA);configuration.setEffectiveFrom(LocalDate.now().minusDays(1));configuration.setActive(true);AccountDTO account=new AccountDTO(12L,"APA Premiums",AccountCategory.INSURANCE,PaymentChannel.MPESA,null,"M-Pesa",true,true,null,List.of());when(users.getUserId()).thenReturn(77L);when(agencies.findByCodeAndActiveTrue("SILVERWOOD")).thenReturn(Optional.of(agency));when(cases.findByIdForUpdate(8L)).thenReturn(Optional.of(insuranceCase));when(quotes.findByIdAndCaseIdAndActiveTrue(9L,8L)).thenReturn(Optional.of(quote));when(paymentConfigurations.findById(6L)).thenReturn(Optional.of(configuration));when(accountsService.getAccount(12L)).thenReturn(account);when(payments.save(any())).thenAnswer(invocation->{InsurancePremiumPayment saved=invocation.getArgument(0);saved.setId(20L);return saved;});InsuranceModels.PaymentView result=service.recordPayment(8L,new InsuranceModels.PaymentRequest(6L,new BigDecimal("25000.00"),"KES","APA-123",LocalDateTime.now()));assertThat(result.paymentConfigurationId()).isEqualTo(6L);verify(payments).save(argThat(payment->Objects.equals(payment.getPaymentConfigurationId(),6L)));}
 @Test void customerCannotOpenAnotherCustomersPaymentEvidence(){InsuranceAgency agency=new InsuranceAgency();agency.setId(1L);InsurancePremiumPayment payment=new InsurancePremiumPayment();payment.setCaseId(8L);payment.setProofFileRef("insurance/private/evidence.pdf");payment.setActive(true);InsuranceCase insuranceCase=new InsuranceCase();insuranceCase.setId(8L);insuranceCase.setAgencyId(1L);insuranceCase.setCustomerUserId(77L);insuranceCase.setActive(true);when(users.getUserId()).thenReturn(99L);when(payments.findByIdAndActiveTrue(4L)).thenReturn(Optional.of(payment));when(cases.findById(8L)).thenReturn(Optional.of(insuranceCase));when(agencies.findByCodeAndActiveTrue("SILVERWOOD")).thenReturn(Optional.of(agency));when(users.hasPermission(Permission.VERIFY_INSURANCE_PAYMENTS)).thenReturn(false);assertThatThrownBy(()->service.paymentProof(4L)).isInstanceOf(PMSCustomException.class);verifyNoInteractions(garage);}
 @Test void authorisedVerifierReceivesOnlyAnExpiringEvidenceUrl(){InsuranceAgency agency=new InsuranceAgency();agency.setId(1L);InsurancePremiumPayment payment=new InsurancePremiumPayment();payment.setCaseId(8L);payment.setProofFileRef("insurance/private/evidence.pdf");payment.setActive(true);InsuranceCase insuranceCase=new InsuranceCase();insuranceCase.setId(8L);insuranceCase.setAgencyId(1L);insuranceCase.setCustomerUserId(77L);insuranceCase.setActive(true);when(users.getUserId()).thenReturn(99L);when(users.hasPermission(Permission.VERIFY_INSURANCE_PAYMENTS)).thenReturn(true);when(payments.findByIdAndActiveTrue(4L)).thenReturn(Optional.of(payment));when(cases.findById(8L)).thenReturn(Optional.of(insuranceCase));when(agencies.findByCodeAndActiveTrue("SILVERWOOD")).thenReturn(Optional.of(agency));when(garage.getPresignedUrlForStoredObject("insurance/private/evidence.pdf")).thenReturn("https://files.example/evidence?expires=60");assertThat(service.paymentProof(4L)).isEqualTo("https://files.example/evidence?expires=60");verify(garage).getPresignedUrlForStoredObject("insurance/private/evidence.pdf");}
 @Test void staffCannotManuallyMarkARenewalPaidWithoutVerifiedEvidence(){assertThatThrownBy(()->service.renewal(4L,new InsuranceModels.RenewalRequest("PAID"))).isInstanceOf(PMSCustomException.class);verifyNoInteractions(policies);}
}
