package org.pms.silverocean.service.insurance;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.*;
import org.mockito.junit.jupiter.MockitoExtension;
import org.pms.silverocean.database.pms.*;
import org.pms.silverocean.database.pms.entities.InsuranceAgency;
import org.pms.silverocean.database.pms.entities.InsuranceCase;
import org.pms.silverocean.database.pms.entities.InsuranceDocument;
import org.pms.silverocean.database.pms.entities.InsurancePremiumPayment;
import org.pms.silverocean.database.pms.entities.InsuranceClaim;
import org.pms.silverocean.database.pms.entities.InsurancePolicy;
import org.pms.silverocean.database.pms.entities.InsurancePaymentConfiguration;
import org.pms.silverocean.database.pms.entities.InsuranceQuote;
import org.pms.silverocean.service.I18NService;
import org.pms.silverocean.service.PMSCustomException;
import org.pms.silverocean.service.account.AccountService;
import org.pms.silverocean.service.account.dto.AccountDTO;
import org.pms.silverocean.service.account.enums.AccountCategory;
import org.pms.silverocean.service.auth.dao.UserDao;
import org.pms.silverocean.service.auth.roles.enums.Permission;
import org.pms.silverocean.service.auth.roles.enums.PMSRole;
import org.pms.silverocean.service.filestorage.GarageService;
import org.pms.silverocean.service.filestorage.UploadMalwarePolicy;
import org.pms.silverocean.service.notification.NotificationService;
import org.pms.silverocean.service.security.DecryptDTO;
import org.pms.silverocean.service.security.EncryptionService;
import org.pms.silverocean.service.payment.wrappers.PaymentChannel;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.test.util.ReflectionTestUtils;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.*;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class InsuranceOperationsSecurityTest {
 @Mock InsuranceAgencyRepo agencies;@Mock InsuranceCompanyRepo companies;@Mock InsuranceCaseRepo cases;@Mock InsuranceQuoteRepo quotes;
 @Mock InsurancePremiumPaymentRepo payments;@Mock InsurancePaymentConfigurationRepo paymentConfigurations;@Mock InsurancePolicyRepo policies;@Mock InsuranceClaimRepo claims;@Mock InsuranceDocumentRepo documents;
 @Mock InsuranceActivityRepo activities;@Mock InsuranceStaffDirectoryService staffDirectory;@Mock UserDao users;@Mock UserRoleRepo userRoles;@Mock AccountService accountsService;@Mock GarageService garage;@Mock UploadMalwarePolicy malwarePolicy;@Mock MarineIdfOcrProvider marineIdfOcr;@Mock EncryptionService encryptionService;@Mock com.fasterxml.jackson.databind.ObjectMapper objectMapper;@Mock NotificationService notifications;@Mock I18NService i18n;
 @Mock InsuranceCorrespondenceService correspondenceService;@Mock InsuranceEmailExchangeRepo emailExchanges;
 @InjectMocks InsuranceOperationsService service;

 @Test void customerCannotReadAnotherCustomersCase(){when(users.getUserId()).thenReturn(77L);when(cases.findByIdAndCustomerUserIdAndActiveTrue(15,77)).thenReturn(Optional.empty());assertThatThrownBy(()->service.myCase(15)).isInstanceOf(PMSCustomException.class);verify(cases,never()).findById(15L);}
 @Test void applicationCannotBeAssignedToAnUnapprovedUser(){when(staffDirectory.isEligible(901L)).thenReturn(false);assertThatThrownBy(()->service.assign(8,new InsuranceModels.AssignmentRequest(901))).isInstanceOf(PMSCustomException.class);verify(cases,never()).findByIdForUpdate(anyLong());}
 @Test void assignmentRequiresAdviserAcceptanceBeforeWorkBegins(){InsuranceAgency agency=new InsuranceAgency();agency.setId(1L);InsuranceCase insuranceCase=new InsuranceCase();insuranceCase.setId(8L);insuranceCase.setAgencyId(1L);insuranceCase.setStatus("SUBMITTED");when(staffDirectory.isEligible(19L)).thenReturn(true);when(agencies.findByCodeAndActiveTrue("SILVERWOOD")).thenReturn(Optional.of(agency));when(cases.findByIdForUpdate(8L)).thenReturn(Optional.of(insuranceCase));when(users.getUserId()).thenReturn(7L);InsuranceModels.CaseView result=service.assign(8L,new InsuranceModels.AssignmentRequest(19L));assertThat(result.status()).isEqualTo("ASSIGNMENT_PENDING");assertThat(result.assignedAdviserId()).isEqualTo(19L);assertThat(result.assignmentOfferedAt()).isNotNull();assertThat(result.adviserAcceptedAt()).isNull();verify(activities).save(argThat(activity->"CASE_ASSIGNMENT_OFFERED".equals(activity.getEventType())));}
 @Test void assignedAdviserCanAcceptAssignment(){InsuranceCase insuranceCase=pendingAssignment(19L);when(users.getUserId()).thenReturn(19L);InsuranceModels.CaseView result=service.decideAssignment(8L,new InsuranceModels.AdviserAssignmentDecision("ACCEPTED",null));assertThat(result.status()).isEqualTo("ADVISER_ASSIGNED");assertThat(result.adviserAcceptedAt()).isNotNull();verify(activities).save(argThat(activity->"CASE_ASSIGNMENT_ACCEPTED".equals(activity.getEventType())));}
 @Test void anotherAdviserCannotAcceptAssignment(){pendingAssignment(19L);when(users.getUserId()).thenReturn(20L);assertThatThrownBy(()->service.decideAssignment(8L,new InsuranceModels.AdviserAssignmentDecision("ACCEPTED",null))).isInstanceOf(PMSCustomException.class);verify(cases,never()).save(any());verifyNoInteractions(activities);}
 @Test void adviserDeclineRequiresReasonAndReturnsCaseToQueue(){InsuranceCase insuranceCase=pendingAssignment(19L);when(users.getUserId()).thenReturn(19L);assertThatThrownBy(()->service.decideAssignment(8L,new InsuranceModels.AdviserAssignmentDecision("DECLINED","  "))).isInstanceOf(PMSCustomException.class);InsuranceModels.CaseView result=service.decideAssignment(8L,new InsuranceModels.AdviserAssignmentDecision("DECLINED","Workload capacity"));assertThat(result.status()).isEqualTo("SUBMITTED");assertThat(result.assignedAdviserId()).isNull();assertThat(result.adviserDeclinedAt()).isNotNull();assertThat(result.adviserDeclineReason()).isEqualTo("Workload capacity");}
 @Test void documentMustHaveExactlyOneAuthorisedParent(){MultipartFile file=mock(MultipartFile.class);assertThatThrownBy(()->service.upload(1L,2L,null,"KYC",file)).isInstanceOf(PMSCustomException.class);verifyNoInteractions(garage);}
 @Test void quoteCannotBeAddedAfterCustomerHasEnteredPaymentFlow(){InsuranceAgency agency=new InsuranceAgency();agency.setId(1L);InsuranceCase insuranceCase=new InsuranceCase();insuranceCase.setId(8L);insuranceCase.setAgencyId(1L);insuranceCase.setStatus("PAYMENT_PENDING");when(cases.findByIdForUpdate(8L)).thenReturn(Optional.of(insuranceCase));when(agencies.findByCodeAndActiveTrue("SILVERWOOD")).thenReturn(Optional.of(agency));assertThatThrownBy(()->service.addQuote(8L,null)).isInstanceOf(PMSCustomException.class);verifyNoInteractions(companies,quotes);}
 @Test void submittedPaymentProofIsImmutable(){InsurancePremiumPayment payment=new InsurancePremiumPayment();payment.setStatus("PENDING_VERIFICATION");payment.setProofFileRef("insurance/existing-proof.pdf");when(payments.findByIdForUpdate(4L)).thenReturn(Optional.of(payment));assertThatThrownBy(()->service.uploadPaymentProof(4L,mock(MultipartFile.class))).isInstanceOf(PMSCustomException.class);verifyNoInteractions(garage,cases);}
 @Test void customerCaseListUsesBoundedBatchQueries(){when(users.getUserId()).thenReturn(77L);InsuranceCase first=new InsuranceCase();first.setId(1L);InsuranceCase second=new InsuranceCase();second.setId(2L);when(cases.findAllByCustomerUserIdAndActiveTrueOrderByCreatedOnDesc(77)).thenReturn(List.of(first,second));when(quotes.findAllByCaseIdInAndActiveTrueOrderByCaseIdAscTotalPremiumAsc(List.of(1L,2L))).thenReturn(List.of());when(payments.findAllByCaseIdInAndActiveTrueOrderByCaseIdAscCreatedOnDesc(List.of(1L,2L))).thenReturn(List.of());service.mine();verify(quotes,times(1)).findAllByCaseIdInAndActiveTrueOrderByCaseIdAscTotalPremiumAsc(anyCollection());verify(payments,times(1)).findAllByCaseIdInAndActiveTrueOrderByCaseIdAscCreatedOnDesc(anyCollection());verify(quotes,never()).findAllByCaseIdAndActiveTrueOrderByTotalPremiumAsc(anyLong());}
 @Test void customerCannotWithdrawAfterEnteringPaymentFlow(){InsuranceAgency agency=new InsuranceAgency();agency.setId(1L);InsuranceCase insuranceCase=new InsuranceCase();insuranceCase.setId(8L);insuranceCase.setAgencyId(1L);insuranceCase.setCustomerUserId(77L);insuranceCase.setStatus("PAYMENT_PENDING");when(users.getUserId()).thenReturn(77L);when(agencies.findByCodeAndActiveTrue("SILVERWOOD")).thenReturn(Optional.of(agency));when(cases.findByIdForUpdate(8L)).thenReturn(Optional.of(insuranceCase));assertThatThrownBy(()->service.withdraw(8L)).isInstanceOf(PMSCustomException.class);verify(cases,never()).save(any());verifyNoInteractions(activities);}
 @Test void operationsSummaryUsesAgencyScopedCounts(){InsuranceAgency agency=new InsuranceAgency();agency.setId(12L);when(agencies.findByCodeAndActiveTrue("SILVERWOOD")).thenReturn(Optional.of(agency));service.summary();verify(cases).countByAgencyIdAndActiveTrueAndStatusNotIn(eq(12L),anySet());verify(cases).countByAgencyIdAndActiveTrueAndAssignedAdviserIdIsNullAndStatusNotIn(eq(12L),anySet());verify(payments).countByAgencyIdAndStatus(12L,"PENDING_VERIFICATION");verify(claims).countOpenByAgencyId(eq(12L),anySet());verify(policies).countRenewalsByAgencyId(eq(12L),any(),any());}
 @Test void staffCannotMutateAClaimOwnedByAnotherAgency(){InsuranceAgency agency=new InsuranceAgency();agency.setId(12L);InsuranceClaim claim=new InsuranceClaim();claim.setId(5L);claim.setPolicyId(6L);claim.setStatus("SUBMITTED");InsurancePolicy policy=new InsurancePolicy();policy.setId(6L);policy.setCaseId(7L);InsuranceCase foreignCase=new InsuranceCase();foreignCase.setId(7L);foreignCase.setAgencyId(99L);foreignCase.setActive(true);when(agencies.findByCodeAndActiveTrue("SILVERWOOD")).thenReturn(Optional.of(agency));when(claims.findByIdForUpdate(5L)).thenReturn(Optional.of(claim));when(policies.findById(6L)).thenReturn(Optional.of(policy));when(cases.findById(7L)).thenReturn(Optional.of(foreignCase));assertThatThrownBy(()->service.updateClaim(5L,new InsuranceModels.ClaimStatusRequest("ACKNOWLEDGED",null,null))).isInstanceOf(PMSCustomException.class);verify(claims,never()).save(any());verifyNoInteractions(activities);}
 @Test void recordedPaymentIsBoundToTheVerifiedInsurerDestination(){InsuranceAgency agency=new InsuranceAgency();agency.setId(1L);InsuranceCase insuranceCase=new InsuranceCase();insuranceCase.setId(8L);insuranceCase.setAgencyId(1L);insuranceCase.setCustomerUserId(77L);insuranceCase.setStatus("CUSTOMER_SELECTED");insuranceCase.setSelectedQuoteId(9L);InsuranceQuote quote=new InsuranceQuote();quote.setId(9L);quote.setCompanyId(3L);quote.setTotalPremium(new BigDecimal("25000.00"));quote.setCurrency("KES");InsurancePaymentConfiguration configuration=new InsurancePaymentConfiguration();configuration.setId(6L);configuration.setCompanyId(3L);configuration.setPaymentAccountId(12L);configuration.setPaymentChannel(PaymentChannel.MPESA);configuration.setEffectiveFrom(LocalDate.now().minusDays(1));configuration.setActive(true);AccountDTO account=new AccountDTO(12L,"APA Premiums",AccountCategory.INSURANCE,PaymentChannel.MPESA,null,"M-Pesa",true,true,null,List.of());when(users.getUserId()).thenReturn(77L);when(agencies.findByCodeAndActiveTrue("SILVERWOOD")).thenReturn(Optional.of(agency));when(cases.findByIdForUpdate(8L)).thenReturn(Optional.of(insuranceCase));when(quotes.findByIdAndCaseIdAndActiveTrue(9L,8L)).thenReturn(Optional.of(quote));when(paymentConfigurations.findById(6L)).thenReturn(Optional.of(configuration));when(accountsService.getAccountStatus(12L)).thenReturn(account);when(payments.save(any())).thenAnswer(invocation->{InsurancePremiumPayment saved=invocation.getArgument(0);saved.setId(20L);return saved;});InsuranceModels.PaymentView result=service.recordPayment(8L,new InsuranceModels.PaymentRequest(6L,new BigDecimal("25000.00"),"KES","APA-123",LocalDateTime.now()));assertThat(result.paymentConfigurationId()).isEqualTo(6L);verify(payments).save(argThat(payment->Objects.equals(payment.getPaymentConfigurationId(),6L)));}
 @Test void customerCannotOpenAnotherCustomersPaymentEvidence(){InsuranceAgency agency=new InsuranceAgency();agency.setId(1L);InsurancePremiumPayment payment=new InsurancePremiumPayment();payment.setCaseId(8L);payment.setProofFileRef("insurance/private/evidence.pdf");payment.setActive(true);InsuranceCase insuranceCase=new InsuranceCase();insuranceCase.setId(8L);insuranceCase.setAgencyId(1L);insuranceCase.setCustomerUserId(77L);insuranceCase.setActive(true);when(users.getUserId()).thenReturn(99L);when(payments.findByIdAndActiveTrue(4L)).thenReturn(Optional.of(payment));when(cases.findById(8L)).thenReturn(Optional.of(insuranceCase));when(agencies.findByCodeAndActiveTrue("SILVERWOOD")).thenReturn(Optional.of(agency));when(users.hasPermission(Permission.VERIFY_INSURANCE_PAYMENTS)).thenReturn(false);assertThatThrownBy(()->service.paymentProof(4L)).isInstanceOf(PMSCustomException.class);verifyNoInteractions(garage);}
 @Test void authorisedVerifierReceivesOnlyAnExpiringEvidenceUrl(){InsuranceAgency agency=new InsuranceAgency();agency.setId(1L);InsurancePremiumPayment payment=new InsurancePremiumPayment();payment.setCaseId(8L);payment.setProofFileRef("insurance/private/evidence.pdf");payment.setActive(true);InsuranceCase insuranceCase=new InsuranceCase();insuranceCase.setId(8L);insuranceCase.setAgencyId(1L);insuranceCase.setCustomerUserId(77L);insuranceCase.setActive(true);when(users.getUserId()).thenReturn(99L);when(users.hasPermission(Permission.VERIFY_INSURANCE_PAYMENTS)).thenReturn(true);when(payments.findByIdAndActiveTrue(4L)).thenReturn(Optional.of(payment));when(cases.findById(8L)).thenReturn(Optional.of(insuranceCase));when(agencies.findByCodeAndActiveTrue("SILVERWOOD")).thenReturn(Optional.of(agency));when(garage.getPresignedUrlForStoredObject("insurance/private/evidence.pdf")).thenReturn("https://files.example/evidence?expires=60");assertThat(service.paymentProof(4L)).isEqualTo("https://files.example/evidence?expires=60");verify(garage).getPresignedUrlForStoredObject("insurance/private/evidence.pdf");}
 @Test void staffCannotManuallyMarkARenewalPaidWithoutVerifiedEvidence(){assertThatThrownBy(()->service.renewal(4L,new InsuranceModels.RenewalRequest("PAID"))).isInstanceOf(PMSCustomException.class);verifyNoInteractions(policies);}
 @Test void motorProposalAcceptsMultipleVehicles(){assertThatCode(()->ReflectionTestUtils.invokeMethod(service,"validateProposal","MOTOR","VEHICLE",Map.of("vehicles",List.of(Map.of("insuredType","VEHICLE","registrationNumber","KDA 123A","makeModel","Toyota Fielder","driverAge","36","estimatedValue","1500000"),Map.of("insuredType","PRIME_MOVER","registrationNumber","KDB 456B","makeModel","Mercedes Actros","driverAge","42","estimatedValue","8000000"))))).doesNotThrowAnyException();}
 @Test void motorProposalRequiresRegistrationNumber(){assertThatThrownBy(()->ReflectionTestUtils.invokeMethod(service,"validateProposal","MOTOR","VEHICLE",Map.of("vehicles",List.of(Map.of("insuredType","VEHICLE","makeModel","Toyota Fielder","driverAge","36","estimatedValue","1500000"))))).isInstanceOf(PMSCustomException.class);}
 @Test void specialPurposeMotorProposalRequiresEquipmentType(){assertThatThrownBy(()->ReflectionTestUtils.invokeMethod(service,"validateProposal","MOTOR","SPECIAL_TYPE",Map.of("vehicles",List.of(Map.of("insuredType","SPECIAL_TYPE","registrationNumber","KDC 789C","makeModel","Caterpillar 320","driverAge","40","estimatedValue","12000000"))))).isInstanceOf(PMSCustomException.class);}
 @Test void domesticBuildingsRequireAnAssignedLandlordRole(){when(users.getUserId()).thenReturn(77L);when(userRoles.findByUserId(77L)).thenReturn(Set.of());assertThatThrownBy(()->ReflectionTestUtils.invokeMethod(service,"validateProposal","DOMESTIC","PROPERTY",Map.of("domesticItems",List.of(Map.of("propertyLocation","Nairobi","itemDescription","Apartment block","value","25000000"))))).isInstanceOf(PMSCustomException.class);}
 @Test void domesticProposalUsesAllAssignedRolesRatherThanOnlyTheActiveRole(){org.pms.silverocean.database.pms.entities.Role landlord=new org.pms.silverocean.database.pms.entities.Role();landlord.setName(PMSRole.LANDLORD.getName());when(users.getUserId()).thenReturn(77L);when(userRoles.findByUserId(77L)).thenReturn(Set.of(landlord));assertThatCode(()->ReflectionTestUtils.invokeMethod(service,"validateProposal","DOMESTIC","PROPERTY",Map.of("domesticItems",List.of(Map.of("propertyLocation","Nairobi","itemDescription","Main house","value","20000000"),Map.of("propertyLocation","Nairobi","itemDescription","Detached garage","value","3000000"))))).doesNotThrowAnyException();verify(users,never()).hasRole(any());}
 @Test void motorTotalIsCalculatedFromEveryItem(){Map<String,Object> proposal=Map.of("vehicles",List.of(Map.of("estimatedValue","1500000"),Map.of("estimatedValue","8000000")));BigDecimal total=ReflectionTestUtils.invokeMethod(service,"calculatedSumInsured","MOTOR",proposal);assertThat(total).isEqualByComparingTo("9500000");}
 @Test void normalizedFireProposalStoresItsCalculatedTotal(){Map<String,Object> normalized=ReflectionTestUtils.invokeMethod(service,"normalizedProposal","FIRE_ALLIED",Map.of("insuredItems",List.of(Map.of("description","Building","value","9000000"),Map.of("description","Equipment","value","1200000"))));assertThat(normalized.get("totalEstimatedValue")).isEqualTo(new BigDecimal("10200000"));}
 @Test void fireProposalAcceptsMultipleValuedItems(){assertThatCode(()->ReflectionTestUtils.invokeMethod(service,"validateProposal","FIRE_ALLIED","PROPERTY",Map.of("insuredItems",List.of(Map.of("description","Building","value","9000000"),Map.of("description","Equipment","value","1200000"))))).doesNotThrowAnyException();}
 @Test void wibaProposalPersistsTrustedCalculatedPayrollColumns(){Map<String,Object> normalized=ReflectionTestUtils.invokeMethod(service,"normalizedProposal","WIBA_EL",Map.of("workforce",List.of(Map.of("jobDescription","Caretaker","monthlySalary","30000","employeeCount","2"))));Map<?,?> row=(Map<?,?>)((List<?>)normalized.get("workforce")).getFirst();assertThat(row.get("monthlySubtotal")).isEqualTo(new BigDecimal("60000"));assertThat(row.get("annualSalary")).isEqualTo(new BigDecimal("720000"));}
 @Test void wibaProposalAcceptsMultipleJobGroups(){assertThatCode(()->ReflectionTestUtils.invokeMethod(service,"validateProposal","WIBA_EL","EMPLOYEES",Map.of("workforce",List.of(Map.of("jobDescription","Caretaker","monthlySalary","30000","employeeCount","2"),Map.of("jobDescription","Guard","monthlySalary","25000","employeeCount","4"))))).doesNotThrowAnyException();}
 @Test void contractorsProposalAcceptsMultipleProjects(){assertThatCode(()->ReflectionTestUtils.invokeMethod(service,"validateProposal","CONTRACTORS_ALL_RISK","PROJECT",Map.of("projects",List.of(Map.of("projectValue","9000000","projectName","Tower A","projectSiteLocation","Nairobi","constructionType","Residential","thirdPartyLiabilityEstimate","1000000"),Map.of("projectValue","7000000","projectName","Tower B","projectSiteLocation","Nairobi","constructionType","Residential","thirdPartyLiabilityEstimate","800000"))))).doesNotThrowAnyException();}
 @Test void medicalProposalRejectsFreeTextGender(){assertThatThrownBy(()->ReflectionTestUtils.invokeMethod(service,"validateProposal","MEDICAL","FAMILY_INDIVIDUAL",Map.of("clientName","Amina","clientDateOfBirth","1990-01-01","clientGender","Other","inPatientLimit","500000"))).isInstanceOf(PMSCustomException.class);}
 @Test void familyMedicalProposalAcceptsMultipleAdditionalMembers(){assertThatCode(()->ReflectionTestUtils.invokeMethod(service,"validateProposal","MEDICAL","FAMILY_INDIVIDUAL",Map.of("clientDateOfBirth","1990-01-01","clientGender","FEMALE","inPatientLimit","500000","outPatientRequired",false,"otherMembers",List.of(Map.of("fullName","Child One","dateOfBirth","2015-01-01","gender","MALE"),Map.of("fullName","Child Two","dateOfBirth","2018-01-01","gender","FEMALE"))))).doesNotThrowAnyException();}
 @Test void corporateMedicalProposalAcceptsMultipleStaffMembers(){assertThatCode(()->ReflectionTestUtils.invokeMethod(service,"validateProposal","MEDICAL","CORPORATE",Map.of("companyName","Acme Limited","waitingPeriod","NO_WAITING_PERIOD","staffMembers",List.of(Map.of("fullName","Staff One","dateOfBirth","1990-01-01","gender","MALE"),Map.of("fullName","Staff Two","dateOfBirth","1992-02-02","gender","FEMALE"))))).doesNotThrowAnyException();}
 @Test void marineProposalRequiresAnIdfNumber(){assertThatThrownBy(()->ReflectionTestUtils.invokeMethod(service,"validateProposal","MARINE_CARGO","GOODS",Map.of("consignments",List.of(Map.of("transportMode","SEA"))))).isInstanceOf(PMSCustomException.class);}
 @Test void marineProposalAcceptsSeveralConsignments(){assertThatCode(()->ReflectionTestUtils.invokeMethod(service,"validateProposal","MARINE_CARGO","GOODS",Map.of("consignments",List.of(marineRow("IDF-1","SEA","500000"),marineRow("IDF-2","AIR","750000"))))).doesNotThrowAnyException();}
 @Test void marineTotalUsesDeclaredFobValues(){Map<String,Object> normalized=ReflectionTestUtils.invokeMethod(service,"normalizedProposal","MARINE_CARGO",Map.of("consignments",List.of(marineRow("IDF-1","SEA","500000"),marineRow("IDF-2","AIR","750000"))));assertThat(normalized.get("totalFobValue")).isEqualTo(new BigDecimal("1250000"));}
 @Test void marineOcrReferenceRejectsChangedDeclarationValues()throws Exception{Map<String,Object> trusted=marineRow("IDF-1","SEA","500000");Map<String,Object> row=new LinkedHashMap<>(trusted);row.put("extractionReference",Base64.getUrlEncoder().withoutPadding().encodeToString(new byte[]{1,2,3}));when(users.getUserId()).thenReturn(77L);when(encryptionService.decrypt(any(byte[].class))).thenReturn(new DecryptDTO(false,"trusted-claim"));when(objectMapper.readValue(eq("trusted-claim"),ArgumentMatchers.<com.fasterxml.jackson.core.type.TypeReference<Map<String,Object>>>any())).thenReturn(Map.of("userId",77,"expiresAt",java.time.Instant.now().plusSeconds(3600).toString(),"fields",trusted));assertThatCode(()->ReflectionTestUtils.invokeMethod(service,"validateMarineOcrReferences",Map.of("consignments",List.of(row)))).doesNotThrowAnyException();row.put("fobValue","1");assertThatThrownBy(()->ReflectionTestUtils.invokeMethod(service,"validateMarineOcrReferences",Map.of("consignments",List.of(row)))).isInstanceOf(PMSCustomException.class);}
 @Test void travelProposalAcceptsMultipleTrips(){assertThatCode(()->ReflectionTestUtils.invokeMethod(service,"validateProposal","TRAVEL","PERSON",Map.of("trips",List.of(Map.of("dateOfBirth","1990-01-01","travelDuration","14 days","destination","Rwanda","purpose","Business"),Map.of("dateOfBirth","1990-01-01","travelDuration","7 days","destination","Tanzania","purpose","Holiday"))))).doesNotThrowAnyException();}
 @Test void goodsInTransitRequiresExplicitRiskAnswers(){Map<String,Object> proposal=new HashMap<>();proposal.put("cargoItems",List.of(Map.of("singleCarryValue","100000","annualCarryValue","1000000","cargoDescription","Packaged food")));proposal.put("conveyanceMode","Road");proposal.put("territorialLimits","Kenya");proposal.put("packaging","Sealed cartons");proposal.put("temporaryGarageSafety","Guarded yard");assertThatThrownBy(()->ReflectionTestUtils.invokeMethod(service,"validateProposal","GOODS_IN_TRANSIT","GOODS",proposal)).isInstanceOf(PMSCustomException.class);}
 @Test void goodsInTransitAcceptsSpecifiedPrimeMoverDetails(){Map<String,Object> proposal=new HashMap<>();proposal.put("cargoItems",List.of(Map.of("singleCarryValue","100000","annualCarryValue","1000000","cargoDescription","Packaged food"),Map.of("singleCarryValue","50000","annualCarryValue","300000","cargoDescription","Furniture")));proposal.put("conveyanceMode","Road");proposal.put("territorialLimits","Kenya");proposal.put("packaging","Sealed cartons");proposal.put("temporaryGarageSafety","Guarded yard");proposal.put("usesHiredVehicles","NO");proposal.put("trackingDevices","YES");proposal.put("engineImmobilizers","YES");proposal.put("specifiedVehicleCover","YES");proposal.put("specifiedVehicles",List.of(Map.of("vehicleType","PRIME_MOVER","make","Mercedes","registrationNumber","KDA 123A","tonnage","20","sumInsured","8000000")));assertThatCode(()->ReflectionTestUtils.invokeMethod(service,"validateProposal","GOODS_IN_TRANSIT","GOODS",proposal)).doesNotThrowAnyException();}
 @Test void marineQuoteCannotBeSentWithoutItsCommercialInvoice(){InsuranceDocument idf=new InsuranceDocument();idf.setCategory("PROPOSAL");stubMarineCaseDocuments(List.of(idf));assertThatThrownBy(()->service.requestInsurerQuote(8L,new InsuranceModels.QuoteDispatchRequest("APA"))).isInstanceOf(PMSCustomException.class);verifyNoInteractions(companies,correspondenceService);}
 @Test void marineQuoteCannotBeSentWithoutItsIdfDocument(){InsuranceDocument invoice=new InsuranceDocument();invoice.setCategory("INVOICE");stubMarineCaseDocuments(List.of(invoice));assertThatThrownBy(()->service.requestInsurerQuote(8L,new InsuranceModels.QuoteDispatchRequest("APA"))).isInstanceOf(PMSCustomException.class);verifyNoInteractions(companies,correspondenceService);}
 @Test void batchQuoteRequestRequiresAtLeastThreeDistinctInsurers(){assertThatThrownBy(()->service.requestInsurerQuotes(8L,new InsuranceModels.QuoteDispatchBatchRequest(List.of("APA","APA","BRITAM")))).isInstanceOf(PMSCustomException.class);verifyNoInteractions(cases,companies,correspondenceService);}
 @Test void quoteCanBeBoundOnlyToTheVerifiedResponseForThatCaseAndInsurer(){InsuranceAgency agency=new InsuranceAgency();agency.setId(1L);InsuranceCase insuranceCase=new InsuranceCase();insuranceCase.setId(8L);insuranceCase.setAgencyId(1L);insuranceCase.setReference("INS-8");insuranceCase.setStatus("SUBMITTED");org.pms.silverocean.database.pms.entities.InsuranceCompany company=new org.pms.silverocean.database.pms.entities.InsuranceCompany();company.setId(3L);company.setAgencyId(1L);company.setCode("APA");company.setName("APA Insurance");company.setActive(true);org.pms.silverocean.database.pms.entities.InsuranceEmailExchange response=new org.pms.silverocean.database.pms.entities.InsuranceEmailExchange();response.setId(41L);response.setCompanyId(3L);response.setCaseReference("INS-8");response.setMessageType("QUOTATION_REQUEST");response.setDirection("INBOUND");response.setStatus("RECEIVED_VERIFIED");response.setActive(true);when(cases.findByIdForUpdate(8L)).thenReturn(Optional.of(insuranceCase));when(agencies.findByCodeAndActiveTrue("SILVERWOOD")).thenReturn(Optional.of(agency));when(companies.findById(3L)).thenReturn(Optional.of(company));when(emailExchanges.findById(41L)).thenReturn(Optional.of(response));when(users.getUserId()).thenReturn(19L);when(quotes.save(any())).thenAnswer(invocation->{InsuranceQuote saved=invocation.getArgument(0);saved.setId(51L);return saved;});InsuranceModels.QuoteView saved=service.addQuote(8L,new InsuranceModels.QuoteRequest(3L,"APA-001","KES",new BigDecimal("1000"),new BigDecimal("50"),new BigDecimal("1050"),null,"Comprehensive cover",null,LocalDate.now().plusDays(14),41L));assertThat(saved.sourceExchangeId()).isEqualTo(41L);verify(quotes).save(argThat(value->Objects.equals(value.getSourceExchangeId(),41L)));}
 @Test void unverifiedEmailResponseCannotBecomeACustomerQuote(){InsuranceAgency agency=new InsuranceAgency();agency.setId(1L);InsuranceCase insuranceCase=new InsuranceCase();insuranceCase.setId(8L);insuranceCase.setAgencyId(1L);insuranceCase.setReference("INS-8");insuranceCase.setStatus("SUBMITTED");org.pms.silverocean.database.pms.entities.InsuranceCompany company=new org.pms.silverocean.database.pms.entities.InsuranceCompany();company.setId(3L);company.setAgencyId(1L);company.setActive(true);org.pms.silverocean.database.pms.entities.InsuranceEmailExchange response=new org.pms.silverocean.database.pms.entities.InsuranceEmailExchange();response.setId(41L);response.setCompanyId(3L);response.setCaseReference("INS-8");response.setMessageType("QUOTATION_REQUEST");response.setDirection("INBOUND");response.setStatus("RECEIVED_UNVERIFIED");response.setActive(true);when(cases.findByIdForUpdate(8L)).thenReturn(Optional.of(insuranceCase));when(agencies.findByCodeAndActiveTrue("SILVERWOOD")).thenReturn(Optional.of(agency));when(companies.findById(3L)).thenReturn(Optional.of(company));when(emailExchanges.findById(41L)).thenReturn(Optional.of(response));assertThatThrownBy(()->service.addQuote(8L,new InsuranceModels.QuoteRequest(3L,"APA-001","KES",new BigDecimal("1000"),new BigDecimal("50"),new BigDecimal("1050"),null,"Comprehensive cover",null,LocalDate.now().plusDays(14),41L))).isInstanceOf(PMSCustomException.class);verify(quotes,never()).save(any());}
 private Map<String,Object> marineRow(String idf,String mode,String fob){return Map.ofEntries(Map.entry("idfNumber",idf),Map.entry("importerName","Example Importer Limited"),Map.entry("importerPin","P051234567A"),Map.entry("origin","China"),Map.entry("portOfDischarge","Mombasa"),Map.entry("hsCode","8703.23.90"),Map.entry("descriptionAndApplication","Motor vehicle spare parts"),Map.entry("fobValue",fob),Map.entry("transportMode",mode),Map.entry("netMass","1500"),Map.entry("quantity","12"),Map.entry("unitOfMeasure","PCS"));}
 private InsuranceCase pendingAssignment(long adviserId){InsuranceAgency agency=new InsuranceAgency();agency.setId(1L);InsuranceCase insuranceCase=new InsuranceCase();insuranceCase.setId(8L);insuranceCase.setAgencyId(1L);insuranceCase.setStatus("ASSIGNMENT_PENDING");insuranceCase.setAssignedAdviserId(adviserId);insuranceCase.setAssignmentOfferedAt(LocalDateTime.now().minusMinutes(5));when(agencies.findByCodeAndActiveTrue("SILVERWOOD")).thenReturn(Optional.of(agency));when(cases.findByIdForUpdate(8L)).thenReturn(Optional.of(insuranceCase));return insuranceCase;}
 private void stubMarineCaseDocuments(List<InsuranceDocument> caseDocuments){InsuranceAgency agency=new InsuranceAgency();agency.setId(1L);InsuranceCase insuranceCase=new InsuranceCase();insuranceCase.setId(8L);insuranceCase.setAgencyId(1L);insuranceCase.setProductCode("MARINE_CARGO");insuranceCase.setActive(true);when(agencies.findByCodeAndActiveTrue("SILVERWOOD")).thenReturn(Optional.of(agency));when(cases.findById(8L)).thenReturn(Optional.of(insuranceCase));when(documents.findAllByCaseIdAndActiveTrueOrderByCreatedOnDesc(8L)).thenReturn(caseDocuments);}
}
