package org.pms.silverocean.service.maintenance;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.pms.silverocean.database.pms.MaintenanceWorkOrderRepo;
import org.pms.silverocean.database.pms.MaintenanceAttachmentRepo;
import org.pms.silverocean.database.pms.UnitRepo;
import org.pms.silverocean.database.pms.entities.MaintenanceWorkOrder;
import org.pms.silverocean.database.pms.entities.Unit;
import org.pms.silverocean.service.PMSCustomException;
import org.pms.silverocean.service.auth.dao.UserDao;
import org.pms.silverocean.service.filestorage.GarageService;
import org.pms.silverocean.service.filestorage.UploadMalwarePolicy;
import org.pms.silverocean.service.notification.NotificationService;
import org.pms.silverocean.service.property.wrappers.DbUnitDTO;
import org.springframework.mock.web.MockMultipartFile;
import java.util.Optional;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
@ExtendWith(MockitoExtension.class)
class MaintenanceServiceTest{
 @Mock MaintenanceWorkOrderRepo orders;@Mock MaintenanceAttachmentRepo attachments;@Mock UnitRepo units;@Mock UserDao users;@Mock GarageService garage;@Mock UploadMalwarePolicy malwarePolicy;@Mock NotificationService notifications;
 private MaintenanceService service(){return new MaintenanceService(orders,attachments,units,users,garage,malwarePolicy,notifications);}
 @Test void staffCanCompleteWorkOrder(){MaintenanceService service=service();MaintenanceWorkOrder w=order("IN_PROGRESS");when(users.getUserId()).thenReturn(7L);when(orders.findAccessible(1,7)).thenReturn(Optional.of(w));when(units.findByIdAndStaffOrOwner(5L,7)).thenReturn(Optional.of(new Unit()));when(orders.save(w)).thenReturn(w);var result=service.update(1,new MaintenanceModels.Update(MaintenanceModels.Status.COMPLETED,null,null,null,null,"KES","Fixed"));assertEquals("COMPLETED",result.status());assertNotNull(result.completedAt());}
 @Test void finalWorkOrderCannotBeReopened(){MaintenanceService service=service();MaintenanceWorkOrder w=order("COMPLETED");when(users.getUserId()).thenReturn(7L);when(orders.findAccessible(1,7)).thenReturn(Optional.of(w));when(units.findByIdAndStaffOrOwner(5L,7)).thenReturn(Optional.of(new Unit()));assertThrows(PMSCustomException.class,()->service.update(1,new MaintenanceModels.Update(MaintenanceModels.Status.OPEN,null,null,null,null,null,null)));}
 @Test void ownershipScopedUserCanCreateAWorkOrder(){MaintenanceService service=service();Unit unit=new Unit();unit.setId(5L);unit.setPropertyId(2L);unit.setCurrency("KES");unit.setActive(true);when(users.getUserId()).thenReturn(9L);when(units.findByIdAndStaffOrOwnerOrTenant(5L,9L)).thenReturn(Optional.of(mock(DbUnitDTO.class)));when(units.findById(5L)).thenReturn(Optional.of(unit));when(orders.save(any())).thenAnswer(invocation->invocation.getArgument(0));var result=service.create(new MaintenanceModels.Create(5L,"Kitchen leak","Water under the sink",MaintenanceModels.Category.PLUMBING,MaintenanceModels.Priority.HIGH));assertEquals(9L,result.requestedByUserId());assertEquals(2L,result.propertyId());assertEquals("OPEN",result.status());}
 @Test void homeownerCannotCancelAnotherUsersRequest(){MaintenanceService service=service();MaintenanceWorkOrder w=order("OPEN");when(users.getUserId()).thenReturn(7L);when(orders.findAccessible(1,7)).thenReturn(Optional.of(w));when(units.findByIdAndStaffOrOwner(5L,7)).thenReturn(Optional.empty());assertThrows(PMSCustomException.class,()->service.update(1,new MaintenanceModels.Update(MaintenanceModels.Status.CANCELLED,null,null,null,null,null,null)));verify(orders,never()).save(any());}
 @Test void requesterCanUploadValidRequestEvidence()throws Exception{MaintenanceWorkOrder w=order("OPEN");when(users.getUserId()).thenReturn(9L);when(orders.findAccessible(1,9)).thenReturn(Optional.of(w));when(units.findByIdAndStaffOrOwner(5L,9)).thenReturn(Optional.empty());when(attachments.countByWorkOrderIdAndActiveTrue(1)).thenReturn(0L);when(attachments.save(any())).thenAnswer(invocation->{var value=(org.pms.silverocean.database.pms.entities.MaintenanceAttachment)invocation.getArgument(0);value.setId(4L);return value;});when(garage.getPresignedUrlForStoredObject(anyString())).thenReturn("https://signed.example/evidence");byte[] jpeg={(byte)0xff,(byte)0xd8,(byte)0xff,1};var result=service().uploadAttachment(1,MaintenanceModels.AttachmentCategory.REQUEST_EVIDENCE,new MockMultipartFile("file","leak.jpg","image/jpeg",jpeg));assertEquals("REQUEST_EVIDENCE",result.category());assertEquals(4L,result.id());verify(garage).uploadBytes(startsWith("maintenance/2/1/"),eq(jpeg),eq("image/jpeg"));}
 @Test void requesterCannotUploadInvoice() {MaintenanceWorkOrder w=order("OPEN");when(users.getUserId()).thenReturn(9L);when(orders.findAccessible(1,9)).thenReturn(Optional.of(w));when(units.findByIdAndStaffOrOwner(5L,9)).thenReturn(Optional.empty());assertThrows(PMSCustomException.class,()->service().uploadAttachment(1,MaintenanceModels.AttachmentCategory.INVOICE,new MockMultipartFile("file","invoice.pdf","application/pdf","%PDF-1".getBytes())));verifyNoInteractions(garage);}
 @Test void assignedProviderCanUploadInvoice()throws Exception{MaintenanceWorkOrder w=order("IN_PROGRESS");when(users.getUserId()).thenReturn(12L);when(orders.findAccessible(1,12)).thenReturn(Optional.of(w));when(units.findByIdAndStaffOrOwner(5L,12)).thenReturn(Optional.empty());when(orders.isAssignedProvider(1,12)).thenReturn(true);when(attachments.countByWorkOrderIdAndActiveTrue(1)).thenReturn(0L);when(attachments.save(any())).thenAnswer(invocation->{var value=(org.pms.silverocean.database.pms.entities.MaintenanceAttachment)invocation.getArgument(0);value.setId(8L);return value;});when(garage.getPresignedUrlForStoredObject(anyString())).thenReturn("https://signed.example/invoice");var result=service().uploadAttachment(1,MaintenanceModels.AttachmentCategory.INVOICE,new MockMultipartFile("file","invoice.pdf","application/pdf","%PDF-1".getBytes()));assertEquals("INVOICE",result.category());verify(garage).uploadBytes(startsWith("maintenance/2/1/"),any(),eq("application/pdf"));}
 @Test void inaccessibleWorkOrderDoesNotRevealAttachments(){when(users.getUserId()).thenReturn(44L);when(orders.findAccessible(1,44)).thenReturn(Optional.empty());assertThrows(PMSCustomException.class,()->service().attachments(1));verifyNoInteractions(attachments,garage);}
 @Test void spoofedFileSignatureIsRejected(){MaintenanceWorkOrder w=order("OPEN");when(users.getUserId()).thenReturn(9L);when(orders.findAccessible(1,9)).thenReturn(Optional.of(w));when(units.findByIdAndStaffOrOwner(5L,9)).thenReturn(Optional.empty());when(attachments.countByWorkOrderIdAndActiveTrue(1)).thenReturn(0L);assertThrows(PMSCustomException.class,()->service().uploadAttachment(1,MaintenanceModels.AttachmentCategory.REQUEST_EVIDENCE,new MockMultipartFile("file","fake.jpg","image/jpeg","not-an-image".getBytes())));verifyNoInteractions(garage);}
 private MaintenanceWorkOrder order(String status){MaintenanceWorkOrder w=new MaintenanceWorkOrder();w.setId(1L);w.setUnitId(5);w.setPropertyId(2);w.setRequestedByUserId(9);w.setWorkOrderNumber("WO-1");w.setTitle("Leak");w.setDescription("Leak");w.setCategory("PLUMBING");w.setPriority("HIGH");w.setStatus(status);w.setActive(true);return w;}
}
