package org.pms.silverocean.service.affiliate;

import org.junit.jupiter.api.BeforeEach;import org.junit.jupiter.api.Test;import org.junit.jupiter.api.extension.ExtendWith;import org.mockito.Mock;import org.mockito.junit.jupiter.MockitoExtension;import org.pms.silverocean.database.pms.*;import org.pms.silverocean.database.pms.entities.*;import org.pms.silverocean.service.account.dao.AccountDao;import org.pms.silverocean.service.auth.dao.UserDao;import org.pms.silverocean.service.payment.invoice.InvoiceDao;import org.springframework.test.util.ReflectionTestUtils;import java.math.BigDecimal;import java.util.Optional;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.ArgumentMatchers.any;import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class AffiliateServiceTest {@Mock AffiliateProfileRepo profiles;@Mock AffiliateReferralRepo referrals;@Mock AffiliateCommissionRepo commissions;@Mock AffiliatePayoutRepo payouts;@Mock UserDao users;@Mock InvoiceDao invoices;@Mock AccountDao accounts;AffiliateService service;
 @BeforeEach void setup(){service=new AffiliateService(profiles,referrals,commissions,payouts,users,invoices,accounts);ReflectionTestUtils.setField(service,"defaultRate",BigDecimal.TEN);ReflectionTestUtils.setField(service,"defaultMinimumPayout",BigDecimal.valueOf(1000));}
 @Test void paidReferredSubscriptionCreatesCommissionOnce(){PMSInvoice invoice=new PMSInvoice();invoice.setId(10L);invoice.setRef("INV-A");invoice.setBilledUserId(8L);invoice.setAmount(3500);invoice.setCurrency("KES");invoice.setBillingType("SUBSCRIPTION");invoice.setPaid(true);invoice.setPendingAmount(0);AffiliateReferral referral=new AffiliateReferral();referral.setAffiliateUserId(4L);referral.setReferredUserId(8L);referral.setStatus("REGISTERED");referral.setActive(true);AffiliateProfile profile=new AffiliateProfile();profile.setUserId(4L);profile.setStatus("ACTIVE");profile.setCommissionRate(BigDecimal.TEN);profile.setActive(true);when(invoices.getInvoiceById(10L)).thenReturn(Optional.of(invoice));when(referrals.findByReferredUserIdAndActiveTrue(8L)).thenReturn(Optional.of(referral));when(profiles.findByUserIdAndActiveTrue(4L)).thenReturn(Optional.of(profile));when(commissions.save(any())).thenAnswer(i->i.getArgument(0));service.recordPaidConversion(10L,"PAY-1");verify(commissions).save(argThat(c->c.getCommissionAmount().compareTo(BigDecimal.valueOf(350).setScale(2))==0&&"EARNED".equals(c.getStatus())));assertEquals("CONVERTED",referral.getStatus());when(commissions.existsByInvoiceId(10L)).thenReturn(true);service.recordPaidConversion(10L,"PAY-1");verify(commissions,times(1)).save(any());}
 @Test void nonSubscriptionPaymentDoesNotEarnCommission(){PMSInvoice invoice=new PMSInvoice();invoice.setId(10L);invoice.setBilledUserId(8L);invoice.setAmount(3500);invoice.setCurrency("KES");invoice.setBillingType("SOKO");invoice.setPaid(true);when(invoices.getInvoiceById(10L)).thenReturn(Optional.of(invoice));service.recordPaidConversion(10L,"PAY-1");verifyNoInteractions(referrals);verify(commissions,never()).save(any());}
}
