package org.pms.silverocean.service.affiliate;

import org.junit.jupiter.api.BeforeEach;import org.junit.jupiter.api.Test;import org.junit.jupiter.api.extension.ExtendWith;import org.mockito.Mock;import org.mockito.junit.jupiter.MockitoExtension;import org.pms.silverocean.database.pms.*;import org.pms.silverocean.database.pms.entities.*;import org.pms.silverocean.service.account.dao.AccountDao;import org.pms.silverocean.service.auth.dao.UserDao;import org.pms.silverocean.service.payment.invoice.InvoiceDao;import org.springframework.test.util.ReflectionTestUtils;import java.math.BigDecimal;import java.util.Optional;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.ArgumentMatchers.any;import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class AffiliateServiceTest {@Mock AffiliateProfileRepo profiles;@Mock AffiliateReferralRepo referrals;@Mock AffiliateCommissionRepo commissions;@Mock AffiliatePayoutRepo payouts;@Mock UserDao users;@Mock InvoiceDao invoices;@Mock AccountDao accounts;AffiliateService service;
 @BeforeEach void setup(){service=new AffiliateService(profiles,referrals,commissions,payouts,users,invoices,accounts);ReflectionTestUtils.setField(service,"defaultRate",BigDecimal.valueOf(25));ReflectionTestUtils.setField(service,"eligiblePaymentCount",3);ReflectionTestUtils.setField(service,"defaultMinimumPayout",BigDecimal.valueOf(1000));}
 @Test void paidReferredSubscriptionCreatesCommissionOnce(){PMSInvoice invoice=new PMSInvoice();invoice.setId(10L);invoice.setRef("INV-A");invoice.setBilledUserId(8L);invoice.setAmount(3500);invoice.setCurrency("KES");invoice.setBillingType("SUBSCRIPTION");invoice.setPaid(true);invoice.setPendingAmount(0);AffiliateReferral referral=new AffiliateReferral();referral.setAffiliateUserId(4L);referral.setReferredUserId(8L);referral.setStatus("REGISTERED");referral.setActive(true);AffiliateProfile profile=new AffiliateProfile();profile.setUserId(4L);profile.setStatus("ACTIVE");profile.setCommissionRate(BigDecimal.valueOf(25));profile.setActive(true);when(invoices.getInvoiceById(10L)).thenReturn(Optional.of(invoice));when(referrals.findForCommissionByReferredUserId(8L)).thenReturn(Optional.of(referral));when(profiles.findByUserIdAndActiveTrue(4L)).thenReturn(Optional.of(profile));when(commissions.save(any())).thenAnswer(i->i.getArgument(0));service.recordPaidConversion(10L,"PAY-1");verify(commissions).save(argThat(c->c.getCommissionAmount().compareTo(BigDecimal.valueOf(875).setScale(2))==0&&c.getEligibleSequence()==1&&"EARNED".equals(c.getStatus())));assertEquals("CONVERTED",referral.getStatus());when(commissions.existsByInvoiceId(10L)).thenReturn(true);service.recordPaidConversion(10L,"PAY-1");verify(commissions,times(1)).save(any());}
 @Test void nonSubscriptionPaymentDoesNotEarnCommission(){PMSInvoice invoice=new PMSInvoice();invoice.setId(10L);invoice.setBilledUserId(8L);invoice.setAmount(3500);invoice.setCurrency("KES");invoice.setBillingType("SOKO");invoice.setPaid(true);when(invoices.getInvoiceById(10L)).thenReturn(Optional.of(invoice));service.recordPaidConversion(10L,"PAY-1");verifyNoInteractions(referrals);verify(commissions,never()).save(any());}
 @Test void fourthEligiblePaymentDoesNotEarnCommission(){PMSInvoice invoice=new PMSInvoice();invoice.setId(14L);invoice.setRef("INV-D");invoice.setBilledUserId(8L);invoice.setAmount(3500);invoice.setCurrency("KES");invoice.setBillingType("SUBSCRIPTION");invoice.setPaid(true);invoice.setPendingAmount(0);AffiliateReferral referral=new AffiliateReferral();referral.setAffiliateUserId(4L);referral.setReferredUserId(8L);referral.setActive(true);AffiliateProfile profile=new AffiliateProfile();profile.setUserId(4L);profile.setStatus("ACTIVE");profile.setActive(true);when(invoices.getInvoiceById(14L)).thenReturn(Optional.of(invoice));when(referrals.findForCommissionByReferredUserId(8L)).thenReturn(Optional.of(referral));when(profiles.findByUserIdAndActiveTrue(4L)).thenReturn(Optional.of(profile));when(commissions.findAllByReferredUserIdAndActiveTrueOrderByEarnedAtAsc(8L)).thenReturn(java.util.List.of(new AffiliateCommission(),new AffiliateCommission(),new AffiliateCommission()));service.recordPaidConversion(14L,"PAY-4");verify(commissions,never()).save(any());}
 @Test void reversedSubscriptionPaymentReversesUnpaidCommission(){AffiliateCommission commission=new AffiliateCommission();commission.setStatus("EARNED");when(commissions.findByInvoiceId(10L)).thenReturn(Optional.of(commission));service.reverseCommission(10L,"Refunded");assertEquals("REVERSED",commission.getStatus());assertNotNull(commission.getReversedAt());assertEquals("Refunded",commission.getReversalReason());verify(commissions).save(commission);}
 @Test void reversalRemovesCommissionFromPendingPayout(){AffiliateCommission commission=new AffiliateCommission();commission.setStatus("PAYOUT_REQUESTED");commission.setPayoutId(20L);commission.setCommissionAmount(BigDecimal.valueOf(875));AffiliatePayout payout=new AffiliatePayout();payout.setId(20L);payout.setAmount(BigDecimal.valueOf(1500));payout.setStatus("REQUESTED");payout.setActive(true);when(commissions.findByInvoiceId(10L)).thenReturn(Optional.of(commission));when(payouts.findById(20L)).thenReturn(Optional.of(payout));service.reverseCommission(10L,"Refunded");assertEquals("REVERSED",commission.getStatus());assertNull(commission.getPayoutId());assertEquals(0,BigDecimal.valueOf(625).compareTo(payout.getAmount()));verify(payouts).save(payout);verify(commissions).save(commission);}
}
