UPDATE pms_help_article
SET body = 'Choose the business area that matches the work you are doing. One active property subscription covers Landlord/Property Management, Estate Management and Property Sales; a user does not need three subscriptions for those areas. The plan unit allowance is shared across the combined property inventory, so changing role or business area does not create a second allowance. Permissions, workspace membership, property classification and assigned-property scope still control which functions and records are visible. Each property must have its intended verified receiving account before payment-dependent setup can be completed.',
    keywords = 'property subscription shared plan unit allowance landlord estate management property sales receiving account workspace role',
    last_modified_date = NOW(6), published = 1, active = 1
WHERE slug = 'property-setup';

INSERT INTO pms_help_article
(uuid,created_on,active,created_by,last_modified_date,slug,title,category,body,keywords,audience_roles,published)
VALUES
(UUID_TO_BIN(UUID()),NOW(6),1,NULL,NOW(6),'property-management-journey','Property Management: setup to collections and maintenance','Property management',
 'Start in the Landlord/Property Management business area with completed verification and an active property subscription that has available shared unit allowance. Create the rental property and attach the property owner receiving account required by the setup form. Add correctly classified rental units with unique references and allowed unit types. Invite the intended tenant by email, allow registration and KYC to complete, then prepare the governed lease from an approved template. Both required signatures and activation checks must complete before treating the unit as occupied. Create invoices, use only verified payment callbacks as confirmation, issue receipts after reconciliation, and retain statements. Record maintenance requests and completion evidence through their governed workflow. Team members see only functions permitted by their active role, workspace and assigned properties. Do not create duplicate properties, manually mark payments paid, or copy a tenant or signed lease into similar units.',
 'property manager landlord rental property unit receiving payment account tenant invitation KYC lease invoice rent collection statement maintenance',NULL,1),
(UUID_TO_BIN(UUID()),NOW(6),1,NULL,NOW(6),'estate-management-journey','Estate Management: setup, homeowners, charges and operations','Estate management',
 'Start in Estate Management with an active property subscription and available shared unit allowance. Create or select a SERVICE_CHARGE estate property, add its homes, and attach the estate verified operating or receiving account. Confirm setup readiness, including ownership records and any required approved current-year budget. Invite each homeowner from the exact home; the homeowner completes registration and KYC using that email. Prepare the Estate Residential Agreement from the ownership record, preserve document versions and obtain the required signatures. Create service-charge invoices against the correct home and ownership, confirm payments only after reconciliation, and preserve ownership history when a home changes hands. Use the governed meeting, budget, work-order, service-request and visitor functions for estate operations. Homeowners see only authorised homes and history; an estate agreement does not create a rental tenancy or property-sale reservation.',
 'estate manager service charge estate property home homeowner invitation ownership agreement budget meeting work order receiving account',NULL,1),
(UUID_TO_BIN(UUID()),NOW(6),1,NULL,NOW(6),'property-sales-journey','Property Sales: listing, buyer, agreements and completion','Property sales',
 'Start in Property Sale Management with an active property subscription and available shared unit allowance. Create correctly classified SALE property and unit inventory, attach the seller or sales recipient verified account, and publish an accurate moderated listing. Keep reserved or completed units out of freely available inventory. Record the prospective sale, invite the buyer using the correct email, and require registration and KYC before buyer-addressed documents are generated. Progress authorised lead, viewing and offer stages; create a versioned letter of offer with amount, currency and deadline, issue it and retain both signatures. A signed offer is not a completed sale. Complete due diligence, issue and sign the separate sale agreement, create the linked buyer invoice with the correct payee account, and wait for reconciled funding. Record transfer and handover evidence before completion, preserve previous ownership history, and never force completion by manually changing payment or milestone status.',
 'property sales sale listing buyer invitation KYC offer letter sale agreement invoice reconciliation transfer handover ownership',NULL,1),
(UUID_TO_BIN(UUID()),NOW(6),1,NULL,NOW(6),'shared-property-subscription','One property subscription across rental, estate and sales','Subscriptions',
 'One active SlickHood property subscription supplies the property capabilities for Landlord/Property Management, Estate Management and Property Sales. Adding or switching among those business areas does not require a separate subscription for each one. The plan unit quota is enforced across the combined rental, estate and sale inventory rather than being reset per role. Role permissions, workspace membership, property assignments, verification status and property classification remain separate controls. Upgrade the shared property plan when its combined unit allowance is exhausted; do not buy another area-specific plan merely to bypass the quota.',
 'one property subscription shared landlord estate sales unit quota allowance combined inventory upgrade business area',NULL,1)
ON DUPLICATE KEY UPDATE
 title=VALUES(title), category=VALUES(category), body=VALUES(body), keywords=VALUES(keywords),
 audience_roles=VALUES(audience_roles), published=1, active=1, last_modified_date=NOW(6);
