-- Replace the earlier high-level marketplace note with operational journeys
-- and publish the governed affiliate lifecycle. WhatsApp is deliberately not
-- represented as live while the production readiness status remains on hold.

UPDATE pms_help_article
SET title = 'Marketplace: services and Soko customer journey',
    body = 'Marketplace contains professional services and the Soko grocery catalogue. For a service, choose the approved category and provider, review the service description and price, submit the booking for the correct property or location, and track its recorded status. For Soko, choose an active merchant, select the grocery product and exact variation, confirm quantity, delivery address, price and the merchant payment destination captured on the order, then place the order. Delivery must use a registered SlickHood rider whose verification and availability permit assignment; an unverified one-off courier must not be used. Track assignment, acceptance, collection and delivery in the order. Give the delivery code only at the correct handover and use the controlled recovery process if the code expires or is lost. A message, screenshot or uploaded proof does not override the recorded order and payment states. Raise service quality, missing-item, failed-delivery or payment disputes through the relevant complaint or support process and never share an OTP, PIN or card credential.',
    keywords = 'marketplace customer service booking provider Soko grocery merchant product variation order payment destination registered verified rider assignment collection delivery code recovery proof complaint dispute',
    audience_roles = NULL,
    published = 1,
    active = 1,
    last_modified_date = NOW(6)
WHERE slug = 'marketplace-and-soko';

INSERT INTO pms_help_article
(uuid,created_on,active,created_by,last_modified_date,slug,title,category,body,keywords,audience_roles,published)
VALUES
(UUID_TO_BIN(UUID()),NOW(6),1,NULL,NOW(6),'service-provider-journey','Service provider journey: verification, services and bookings','Marketplace',
 'Select the Service Provider role, complete common personal or company KYC, and provide the professional or business evidence required for each intended service category. Create an accurate provider profile and submit services under the correct active categories with their scope, price and availability. A visible draft or submitted service is not automatically approved: wait for the recorded review decision before offering it as an approved Marketplace service. Keep category evidence current and respond to requests for clarification through the governed review process. Use the provider workspace to receive and progress bookings, record fulfilment evidence and handle complaints. Do not move a booking off-platform merely to bypass status, evidence or dispute controls. Suspension, unresolved complaints, expired evidence or blacklisting can prevent new Marketplace work while historical records remain available for authorised review.',
 'service provider journey category KYC professional certificate business evidence profile service approval booking fulfilment complaint suspension blacklist marketplace',
 'ServiceProvider',1),
(UUID_TO_BIN(UUID()),NOW(6),1,NULL,NOW(6),'soko-merchant-journey','Soko merchant journey: store, catalogue, orders and delivery','Marketplace',
 'Complete the required merchant KYC before operating a Soko store. Configure the store and its verified receiving account, then publish only supported grocery categories. Create accurate products and variations with current prices and stock; inactive or unsupported catalogue items must not be sold as current inventory. Review each order against the exact items, variation, quantity, address and payment destination captured when it was placed. Prepare the order and assign only a registered SlickHood rider whose verification status is approved and whose availability allows delivery. Track rider acceptance, collection, delivery exceptions, returns and final delivery. Do not treat a merchant message, rider claim or proof upload as a substitute for the governed order state. Keep the original order and payment destination for audit, and escalate disputed payment or delivery outcomes through support rather than recreating the order.',
 'Soko merchant journey store merchant KYC grocery catalogue product variation price stock order verified receiving account registered rider delivery exception return audit',
 NULL,1),
(UUID_TO_BIN(UUID()),NOW(6),1,NULL,NOW(6),'soko-rider-journey','Soko rider journey: verification, assignment and handover','Marketplace',
 'A delivery rider must use a registered SlickHood account and complete common KYC plus the required rider evidence, including a valid certificate of good conduct where required. Upload rider evidence through the rider checklist and wait for authorised review. Registration alone does not permit assignment: the rider record must be verified, active and available. Review each assigned order before accepting it, confirm collection only after receiving the correct parcel, and keep order details and customer information confidential. Record failed delivery or return with an accurate reason. At handover, use the current delivery code and the governed confirmation process; do not ask the customer for a payment PIN or account OTP. If the delivery code is unavailable or locked, use the controlled recovery or authorised reissue process. A delivery is complete only when the system records the valid confirmation, not when a rider sends a chat message or photograph.',
 'Soko rider journey registered rider KYC good conduct credential verification active availability assignment accept collection failed delivery return delivery code recovery reissue handover privacy',
 NULL,1),
(UUID_TO_BIN(UUID()),NOW(6),1,NULL,NOW(6),'affiliate-journey','Affiliate journey: approval, commissions and payout','Affiliates',
 'Select the Affiliate role and submit the application. Affiliate access is not a paid subscription role, but referral and payout functions remain locked while the profile is pending Superadmin approval. After approval, use the assigned referral code or link and monitor referrals in the affiliate workspace. A registration alone does not earn commission. Commission is created only from an eligible, reconciled subscription payment under the current Superadmin-managed policy, which controls the commission rate, number of eligible payments, holding period and minimum payout. Pending commission becomes earned only after its holding period and may be reversed or clawed back if the qualifying payment is reversed. Before requesting payout, add an active verified Affiliate payment account and ensure the available balance meets the minimum. A payout request moves through requested, processing and paid or rejected states; paid status requires a unique payment reference. Suspended, blacklisted, inactive or rejected affiliates cannot create new referrals, earn new commissions or request payouts, although authorised historical records remain available. Contact support about a disputed decision; do not create another account to bypass a restriction.',
 'affiliate journey application superadmin approval referral code conversion eligible subscription payment commission policy rate holding period matured earned reversal clawback verified payout account minimum payout processing paid rejected suspended blacklisted',
 'Affiliate,Superadmin,Support',1)
ON DUPLICATE KEY UPDATE
 title=VALUES(title), category=VALUES(category), body=VALUES(body), keywords=VALUES(keywords),
 audience_roles=VALUES(audience_roles), published=1, active=1, last_modified_date=NOW(6);
