-- Publish operational journeys for the next verified Help Desk knowledge batch.
-- Guidance is deliberately limited to enabled channels and recorded system states.

UPDATE pms_help_article
SET title = 'Insurance journey: request, quotations, cover and claims',
    body = 'Insurance is arranged through Silverwood Insurance Agency. A visitor to the public Insurance Hub may request a one-time code by an available email or SMS channel, verify the code, and submit a quotation request without creating a SlickHood account. The secure request link is time limited. Provide accurate risk information and upload only the requested documents. For Marine Cargo Insurance, upload every Import Declaration Form (IDF/IM0), review the extracted consignment details, and attach the supplier commercial invoice separately; the invoice must be PDF, JPG or PNG and no larger than 10 MB. Submission does not mean that cover exists. An authorised Silverwood adviser reviews the request, obtains or records insurer quotations, and the customer selects a quotation before using the verified insurer payment destination shown for that case. A payment record, policy issue, renewal or claim becomes complete only when its corresponding system state is updated by authorised operations staff. CIC Insurance is a participating insurer; its logo does not mean the risk was accepted. Never send payment PINs, OTPs or full card details in a proposal or Help Desk message. Escalate urgent claims, disputed payments and policy decisions to Silverwood.',
    keywords = 'insurance Silverwood quote quotation OTP email SMS request cover policy premium claim renewal marine cargo MCI IDF IM0 commercial invoice CIC adviser insurer payment',
    audience_roles = NULL,
    published = 1,
    active = 1,
    last_modified_date = NOW(6)
WHERE slug = 'insurance-support';

INSERT INTO pms_help_article
(uuid,created_on,active,created_by,last_modified_date,slug,title,category,body,keywords,audience_roles,published)
VALUES
(UUID_TO_BIN(UUID()),NOW(6),1,NULL,NOW(6),'payment-journey','Payments: invoices, approved channels and confirmation','Payments',
 'Open the relevant invoice and confirm its reference, amount, currency, property or service context and receiving account before paying. Use only a payment channel currently offered on that invoice. Depending on the verified receiving account and enabled production configuration, the system may show M-Pesa, M-Pesa through a bank Paybill, PesaLink or Paystack instructions. Follow the exact Paybill, account, bank or hosted-checkout details shown; do not reuse details copied from another property or invoice. A checkout start, browser return, bank message, screenshot or uploaded proof is not final confirmation. The payment becomes successful only after SlickHood records the verified provider callback or an authorised manual-payment decision, applies the amount to the intended invoice and makes the receipt available. Pending, failed, reversed and duplicate callbacks must not be treated as settled. If the status remains pending, keep the invoice reference and provider receipt, avoid paying again without checking, and ask the authorised property or finance team to reconcile it. Never share a card PIN, M-Pesa PIN, OTP, secret key or webhook credential.',
 'payment journey invoice reference amount currency receiving account M-Pesa Paybill PesaLink Paystack callback pending failed reversed duplicate reconciliation receipt',
 NULL,1),
(UUID_TO_BIN(UUID()),NOW(6),1,NULL,NOW(6),'notification-preferences-journey','Notification preferences: in-app, email, SMS and WhatsApp','Notifications',
 'Open Profile or Settings and choose Notification Preferences. Important in-app account activity remains enabled. Set email, SMS and WhatsApp separately for billing, property, marketplace and delivery, security, and marketing. SMS and WhatsApp require a verified phone number. WhatsApp also requires explicit consent and is selectable only for a category that has an approved and configured Meta template; if it is unavailable, keep email or SMS enabled rather than assuming WhatsApp delivery. Security codes continue through the verification channel offered by the relevant screen and are not changed merely by enabling general notifications. Save all five categories together. If another session changed the preferences, reload the current values before saving again. Consent changes and delivery attempts are recorded for audit. A sent or accepted status is not the same as handset delivery; check the recorded delivery status and use an available controlled fallback when necessary.',
 'notification preferences in-app email SMS WhatsApp consent verified phone billing property marketplace delivery security marketing Meta template delivery status fallback audit',
 NULL,1),
(UUID_TO_BIN(UUID()),NOW(6),1,NULL,NOW(6),'visitor-host-journey','Visitor Hub: resident and host journey','Visitor Hub',
 'Use the Visitor Hub for the correct property and unit. Register an expected visitor with accurate identity, contact, vehicle and visit details, then review the recorded status. Where host approval is required, approve or deny the pending request in the system; a private message to a guard does not replace the decision. The host or other authorised user may view the scoped visitor list and cancel a visit that has not progressed beyond an allowed pre-arrival state. Share only the visitor instructions or access details produced for that visit. Do not reuse an old visit, share another resident’s visitor record or ask a guard to bypass an expired, denied or cancelled status. Arrival and departure notifications follow the host’s available notification settings, while the visitor status and gate event remain the authoritative record.',
 'visitor hub resident host expected visitor pre-register approve deny pending property unit vehicle cancel expired arrival departure access status',
 'Tenant,Homeowner,Landlord,EstateManager,PropertyManager,WorkspaceAdmin',1),
(UUID_TO_BIN(UUID()),NOW(6),1,NULL,NOW(6),'visitor-guard-journey','Visitor Hub: guard check-in and check-out journey','Visitor Hub',
 'Work only in the assigned property and gate scope. Search or register a walk-in using accurate visitor, host, unit and vehicle details. If the visit requires approval, keep it pending until the authorised host decision is recorded. Before entry, confirm that the visit is approved or otherwise eligible and that it is not expired, cancelled, denied or already checked in. Record check-in at actual entry and check-out at actual exit; do not use a chat message, paper note or photograph as a substitute for the status update. A configured smart-gate device must use its own enabled device identity and signed request, and every decision is recorded as a gate event. Do not share device credentials or override anti-passback, invalid-signature, stale-request or replay protections. Escalate a mismatch to the Security Supervisor or authorised estate operations team.',
 'visitor guard walk-in host approval check-in check-out property gate smart gate device signed request event anti-passback replay expired cancelled denied security supervisor',
 'Guard,SecuritySupervisor,EstateOperationsManager,EstateManager,WorkspaceAdmin',1)
ON DUPLICATE KEY UPDATE
 title=VALUES(title), category=VALUES(category), body=VALUES(body), keywords=VALUES(keywords),
 audience_roles=VALUES(audience_roles), published=1, active=1, last_modified_date=NOW(6);
