-- Publish operational guidance for Wealth, governed documents, Tax Assist and reports.

UPDATE pms_help_article
SET title = 'My Wealth journey: assets, finance, obligations and goals',
    body = 'Open My Wealth in an authorised role and begin with Assets. Choose an active asset category, enter a clear name, currency, acquisition details and valuation date, then provide the fields required for that category. Use manual valuation for a value you maintain yourself. Use market pricing only for a supported exchange and instrument symbol; a quote can be unavailable or stale, so the displayed source, timestamp and fallback value must be reviewed before making a decision. Link a property only from the scoped property options available to the current user. Add valuations to preserve history rather than overwriting evidence, and record income, expenses and liabilities against the correct asset so yield, debt and equity calculations remain meaningful. Use Lifecycle for compliance obligations, Document vault for supporting records, and Goals and projections for scenarios. Projections and adviser scores are decision-support information, not guaranteed returns or regulated investment advice. Archive incorrect records instead of assuming history was destroyed, and verify currency, dates, quantity and unit cost when the form identifies invalid field data.',
    keywords = 'wealth assets category manual valuation market quote exchange symbol fallback stale property link income expense liability debt equity lifecycle obligation vault goals projection archive currency',
    audience_roles = 'Landlord,AssetPortfolioManager,Homeowner',
    published = 1,
    active = 1,
    last_modified_date = NOW(6)
WHERE slug = 'wealth-overview';

INSERT INTO pms_help_article
(uuid,created_on,active,created_by,last_modified_date,slug,title,category,body,keywords,audience_roles,published)
VALUES
(UUID_TO_BIN(UUID()),NOW(6),1,NULL,NOW(6),'document-template-journey','Document templates, issued documents and version visibility','Documents',
 'Use Documents and Notices in the active property, estate or sales workspace. An authorised issuer selects the appropriate current template for the transaction, confirms the linked lease, sale, property, unit and recipient, and generates a draft. Review the rendered wording and dates before issuing it. The recipient then follows the allowed acknowledge, reject or sign action, and the recorded status is authoritative. Cancelling a draft does not cancel an already issued document. Standard users see only the latest active template for each document type; historical template versions are restricted to Superadmin and SlickHood Support for governance and investigation. Creating a new template produces a new immutable version and does not rewrite documents already generated from an earlier version. Use the PDF generated for the scoped record and do not upload or circulate edited copies as though they were the governed document.',
 'document template current latest version history lease sale offer estate agreement notice draft issue acknowledge reject sign PDF superadmin support immutable',
 NULL,1),
(UUID_TO_BIN(UUID()),NOW(6),1,NULL,NOW(6),'document-storage-journey','Secure document upload, access and retention','Documents',
 'Upload a document only in the workflow that requested it and confirm the supported file type and size shown there. The system stores a private object reference, checksum and document metadata; authorised retrieval uses a time-limited link rather than a public permanent URL. Access remains limited by the owner, workspace, transaction or staff permission for that document. Keep filenames descriptive but do not place passwords, PINs, OTPs or unnecessary identity numbers in a filename or note. A successful upload does not by itself mean KYC approval, insurer acceptance, lease signature or payment confirmation. Replace incorrect evidence through the workflow’s new-version or archive action where available instead of editing an issued record. Expired download links should be requested again from the authorised screen. Report an unexpected document, access link or permission immediately to SlickHood Support.',
 'document storage upload private checksum metadata expiring link access permission owner workspace archive version file type size security support',
 NULL,1),
(UUID_TO_BIN(UUID()),NOW(6),1,NULL,NOW(6),'tax-assist-journey','Tax Assist: MRI and property-sale CGT estimates','Tax Assist',
 'Tax Assist provides private estimates using the approved rule version effective for the selected period or transfer date. For residential Monthly Rental Income, enter actual rent received, projected annual rent, taxpayer status, any election and supported withholding credits. For property-sale Capital Gains Tax, enter transfer value and supported acquisition, enhancement and transfer costs, then identify any potential exemption or property-dealer treatment. Read the outcome and explanation: some answers require the annual regime or specialist review, and a zero estimate does not prove that no filing obligation exists. Each calculation preserves its input and rule snapshot in the user’s history. Tax Assist does not automatically file with KRA, eTIMS, iTax or GavaConnect. A connection request is a separate consented process and remains only in its recorded environment and status until reviewed. Confirm source documents, exemptions, CGT timing and current KRA requirements with a qualified adviser before filing or paying.',
 'tax assist KRA MRI monthly rental income CGT capital gains property sale estimate rule version history withholding exemption transfer filing eTIMS iTax GavaConnect adviser',
 NULL,1),
(UUID_TO_BIN(UUID()),NOW(6),1,NULL,NOW(6),'reports-journey','Reports, date ranges, workspace scope and CSV export','Reports',
 'Open Reports in the role and workspace whose activity you need to review. The catalogue shows only reports available to the active role. Select the relevant report and an allowed date range; historical and forward-looking reports validate their dates, while snapshot reports use the current state. Financial reports are restricted to the selected workspace, assigned properties and authorised role scope; changing role or workspace changes the accessible data. Review the report metrics and rows, then use CSV export when required. Screen results are bounded and CSV exports are capped, so a truncated indicator means the date range should be narrowed and additional exports taken. Exports contain operational or financial data: store them securely and do not share them outside the authorised team. Empty results can mean that no matching records exist in the selected scope or period; they do not authorise switching to another customer workspace. Reconcile payment and statement reports against the underlying invoice, receipt and immutable ledger records.',
 'reports analytics dashboard catalog role workspace scope property date range snapshot historical forward CSV export truncated invoice payment statement reconciliation security',
 NULL,1)
ON DUPLICATE KEY UPDATE
 title=VALUES(title), category=VALUES(category), body=VALUES(body), keywords=VALUES(keywords),
 audience_roles=VALUES(audience_roles), published=1, active=1, last_modified_date=NOW(6);
