CREATE TABLE pms_lease_document_template (
    id BIGINT NOT NULL AUTO_INCREMENT,
    uuid BINARY(16) NOT NULL,
    created_on DATETIME(6),
    active BIT NOT NULL,
    created_by BIGINT,
    last_modified_date DATETIME(6),
    document_type VARCHAR(60) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    version INT NOT NULL,
    body_html MEDIUMTEXT NOT NULL,
    legal_review_required BIT NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_document_template_uuid (uuid),
    KEY idx_document_template_type_active (document_type, active)
);

CREATE TABLE pms_lease_document (
    id BIGINT NOT NULL AUTO_INCREMENT,
    uuid BINARY(16) NOT NULL,
    created_on DATETIME(6),
    active BIT NOT NULL,
    created_by BIGINT,
    last_modified_date DATETIME(6),
    lease_id BIGINT,
    property_id BIGINT,
    unit_id BIGINT,
    template_id BIGINT NOT NULL,
    template_version INT NOT NULL,
    document_type VARCHAR(60) NOT NULL,
    status VARCHAR(30) NOT NULL,
    name VARCHAR(255) NOT NULL,
    rendered_html LONGTEXT NOT NULL,
    issuer_user_id BIGINT NOT NULL,
    recipient_user_id BIGINT NOT NULL,
    effective_date DATE,
    response_due_date DATE,
    amount DECIMAL(19,2),
    currency VARCHAR(12),
    reason VARCHAR(1000),
    delivery_channel VARCHAR(40),
    legal_review_required BIT NOT NULL,
    issued_at DATETIME(6),
    acknowledged_at DATETIME(6),
    issuer_signed_at DATETIME(6),
    recipient_signed_at DATETIME(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_lease_document_uuid (uuid),
    KEY idx_document_lease (lease_id, active),
    KEY idx_document_property (property_id, active),
    KEY idx_document_parties (issuer_user_id, recipient_user_id, active),
    CONSTRAINT fk_document_template FOREIGN KEY (template_id) REFERENCES pms_lease_document_template (id)
);
