ALTER TABLE pms_invoice ADD COLUMN payment_account_id BIGINT NULL;
ALTER TABLE pms_invoice ADD CONSTRAINT fk_invoice_payment_account FOREIGN KEY (payment_account_id) REFERENCES pms_payment_account(id);
CREATE INDEX idx_invoice_payment_account ON pms_invoice(payment_account_id);

CREATE TABLE pms_community_fund (
    id BIGINT NOT NULL AUTO_INCREMENT,
    uuid BINARY(16) NOT NULL,
    property_id BIGINT NOT NULL,
    name VARCHAR(180) NOT NULL,
    fund_type VARCHAR(30) NOT NULL,
    contributor_scope VARCHAR(30) NOT NULL,
    description VARCHAR(2000) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    target_amount DECIMAL(19,2) NOT NULL,
    default_contribution DECIMAL(19,2) NOT NULL,
    opens_on DATE NOT NULL,
    due_date DATE NOT NULL,
    closes_on DATE NULL,
    status VARCHAR(24) NOT NULL,
    payment_account_id BIGINT NOT NULL,
    custodian_user_id BIGINT NOT NULL,
    dual_approval_required BIT NOT NULL DEFAULT 1,
    active BIT NOT NULL DEFAULT 1,
    created_by BIGINT NULL,
    created_on DATETIME(6) NULL,
    last_modified_date DATETIME(6) NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_community_fund_uuid UNIQUE (uuid),
    CONSTRAINT fk_community_fund_property FOREIGN KEY (property_id) REFERENCES pms_property(id),
    CONSTRAINT fk_community_fund_payment_account FOREIGN KEY (payment_account_id) REFERENCES pms_payment_account(id),
    INDEX idx_community_fund_property (property_id, active, status),
    INDEX idx_community_fund_creator (created_by, active)
);

CREATE TABLE pms_community_fund_contribution (
    id BIGINT NOT NULL AUTO_INCREMENT,
    uuid BINARY(16) NOT NULL,
    fund_id BIGINT NOT NULL,
    contributor_user_id BIGINT NOT NULL,
    unit_id BIGINT NOT NULL,
    assessed_amount DECIMAL(19,2) NOT NULL,
    paid_amount DECIMAL(19,2) NOT NULL DEFAULT 0,
    invoice_id BIGINT NULL,
    status VARCHAR(24) NOT NULL,
    paid_at DATETIME(6) NULL,
    payment_reference VARCHAR(120) NULL,
    active BIT NOT NULL DEFAULT 1,
    created_by BIGINT NULL,
    created_on DATETIME(6) NULL,
    last_modified_date DATETIME(6) NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_fund_contribution_uuid UNIQUE (uuid),
    CONSTRAINT fk_fund_contribution_fund FOREIGN KEY (fund_id) REFERENCES pms_community_fund(id),
    CONSTRAINT fk_fund_contribution_unit FOREIGN KEY (unit_id) REFERENCES pms_unit(id),
    CONSTRAINT fk_fund_contribution_invoice FOREIGN KEY (invoice_id) REFERENCES pms_invoice(id),
    CONSTRAINT uk_fund_contributor_unit UNIQUE (fund_id, contributor_user_id, unit_id),
    INDEX idx_fund_contribution_user (contributor_user_id, active),
    INDEX idx_fund_contribution_invoice (invoice_id)
);

CREATE TABLE pms_community_fund_expenditure (
    id BIGINT NOT NULL AUTO_INCREMENT,
    uuid BINARY(16) NOT NULL,
    fund_id BIGINT NOT NULL,
    purpose VARCHAR(1000) NOT NULL,
    category VARCHAR(60) NOT NULL,
    amount DECIMAL(19,2) NOT NULL,
    beneficiary_type VARCHAR(30) NOT NULL,
    beneficiary_user_id BIGINT NULL,
    beneficiary_name VARCHAR(200) NOT NULL,
    beneficiary_reference VARCHAR(120) NULL,
    status VARCHAR(24) NOT NULL,
    approved_by BIGINT NULL,
    approved_at DATETIME(6) NULL,
    paid_by BIGINT NULL,
    paid_at DATETIME(6) NULL,
    payment_reference VARCHAR(120) NULL,
    evidence_file_ref VARCHAR(800) NULL,
    rejection_reason VARCHAR(1000) NULL,
    active BIT NOT NULL DEFAULT 1,
    created_by BIGINT NULL,
    created_on DATETIME(6) NULL,
    last_modified_date DATETIME(6) NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_fund_expenditure_uuid UNIQUE (uuid),
    CONSTRAINT fk_fund_expenditure_fund FOREIGN KEY (fund_id) REFERENCES pms_community_fund(id),
    INDEX idx_fund_expenditure_fund (fund_id, active, status)
);

CREATE TABLE pms_community_fund_transaction (
    id BIGINT NOT NULL AUTO_INCREMENT,
    uuid BINARY(16) NOT NULL,
    fund_id BIGINT NOT NULL,
    event_key VARCHAR(190) NOT NULL,
    transaction_type VARCHAR(30) NOT NULL,
    amount DECIMAL(19,2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    source_type VARCHAR(40) NULL,
    source_id BIGINT NULL,
    contributor_user_id BIGINT NULL,
    beneficiary_user_id BIGINT NULL,
    beneficiary_name VARCHAR(200) NULL,
    external_reference VARCHAR(120) NULL,
    occurred_at DATETIME(6) NOT NULL,
    active BIT NOT NULL DEFAULT 1,
    created_by BIGINT NULL,
    created_on DATETIME(6) NULL,
    last_modified_date DATETIME(6) NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_fund_transaction_uuid UNIQUE (uuid),
    CONSTRAINT fk_fund_transaction_fund FOREIGN KEY (fund_id) REFERENCES pms_community_fund(id),
    CONSTRAINT uk_fund_transaction_event UNIQUE (event_key),
    INDEX idx_fund_transaction_fund (fund_id, occurred_at)
);
