package org.pms.silverocean.service.estateops;

import org.junit.jupiter.api.*;import org.junit.jupiter.api.extension.ExtendWith;import org.mockito.Mock;import org.mockito.junit.jupiter.MockitoExtension;
import org.pms.silverocean.database.pms.*;import org.pms.silverocean.database.pms.entities.*;import org.pms.silverocean.service.PMSCustomException;
import org.pms.silverocean.service.auth.dao.UserDao;import org.pms.silverocean.service.auth.roles.enums.PMSRole;import org.pms.silverocean.service.auth.roles.enums.Permission;import org.springframework.data.domain.*;
import java.math.BigDecimal;import java.util.*;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.ArgumentMatchers.any;import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class EstateOperationsServiceTest {
 @Mock EstateBudgetRepo budgets;@Mock EstateBudgetLineRepo lines;@Mock EstateMeetingRepo meetings;@Mock EstateResolutionRepo resolutions;@Mock EstateWorkOrderRepo works;@Mock PropertyRepo properties;@Mock UserDao users;
 EstateOperationsService service;Property property;
 @BeforeEach void setup(){service=new EstateOperationsService(budgets,lines,meetings,resolutions,works,properties,users);property=new Property();property.setId(4L);property.setActive(true);lenient().when(users.getUserId()).thenReturn(2L);lenient().when(users.getActiveRole()).thenReturn(PMSRole.ESTATE_MANAGER);lenient().when(users.hasPermission(Permission.MANAGE_ESTATE)).thenReturn(true);lenient().when(users.hasPermission(Permission.VIEW_ESTATE)).thenReturn(true);lenient().when(properties.findByIdAndStaffOrOwner(4L,2L)).thenReturn(Optional.of(property));}

 @Test void emptyBudgetCannotBeApproved(){EstateBudget b=budget("DRAFT");when(budgets.findById(7L)).thenReturn(Optional.of(b));when(lines.findAllByBudgetIdAndActiveTrueOrderById(7L)).thenReturn(List.of());assertThrows(PMSCustomException.class,()->service.approve(7L));}
 @Test void annualBudgetCreationIsSerializedAndCannotDuplicate(){when(properties.findAndLockById(4L)).thenReturn(Optional.of(property));when(budgets.countByPropertyIdAndBudgetYearAndActiveTrue(4L,2026)).thenReturn(1L);var r=new EstateOperationsModels.BudgetCreate(4L,2026,"Operations","KES");assertThrows(PMSCustomException.class,()->service.createBudget(r));verify(budgets,never()).save(any());}
 @Test void meetingRequiresQuorumAndMinutes(){EstateMeeting m=meeting("SCHEDULED",4);m.setQuorumRequired(5);when(meetings.findById(8L)).thenReturn(Optional.of(m));var r=new EstateOperationsModels.MeetingUpdate(EstateOperationsModels.MeetingStatus.HELD,4,"Minutes");assertThrows(PMSCustomException.class,()->service.updateMeeting(8L,r));}
 @Test void resolutionCannotBeCreatedBeforeMeetingIsHeld(){when(meetings.findById(8L)).thenReturn(Optional.of(meeting("SCHEDULED",0)));var r=new EstateOperationsModels.ResolutionCreate("Repair roof","Approved",null);assertThrows(PMSCustomException.class,()->service.createResolution(8L,r));verify(resolutions,never()).save(any());}
 @Test void votesCannotExceedRecordedAttendance(){EstateResolution x=new EstateResolution();x.setId(10L);x.setMeetingId(8L);x.setStatus("PROPOSED");x.setActive(true);when(resolutions.findById(10L)).thenReturn(Optional.of(x));when(meetings.findById(8L)).thenReturn(Optional.of(meeting("HELD",5)));var r=new EstateOperationsModels.ResolutionUpdate(EstateOperationsModels.ResolutionStatus.PASSED,5,1,0,"Approved");assertThrows(PMSCustomException.class,()->service.updateResolution(10L,r));}
 @Test void completedWorkOrderCannotReopen(){EstateWorkOrder w=work("COMPLETED");when(works.findById(9L)).thenReturn(Optional.of(w));var r=new EstateOperationsModels.WorkUpdate(EstateOperationsModels.WorkStatus.OPEN,null,null,null,null,null);assertThrows(PMSCustomException.class,()->service.updateWork(9L,r));}
 @Test void partialWorkTransitionPreservesAssignmentAndCost(){EstateWorkOrder w=work("ACKNOWLEDGED");w.setAssignedProviderServiceId(44L);w.setEstimatedCost(new BigDecimal("2500.00"));when(works.findById(9L)).thenReturn(Optional.of(w));when(works.save(w)).thenReturn(w);var r=new EstateOperationsModels.WorkUpdate(EstateOperationsModels.WorkStatus.IN_PROGRESS,null,null,null,null,"Provider on site");EstateWorkOrder saved=service.updateWork(9L,r);assertEquals(44L,saved.getAssignedProviderServiceId());assertEquals(new BigDecimal("2500.00"),saved.getEstimatedCost());assertEquals("Provider on site",saved.getResolutionNotes());}
 @Test void delegatedEstateManagerCanManageAssignedProperty(){when(users.getActiveRole()).thenReturn(PMSRole.ESTATE_OPERATIONS_MANAGER);EstateWorkOrder saved=work("OPEN");when(works.save(any())).thenReturn(saved);var r=new EstateOperationsModels.WorkCreate(4L,"Lobby","Replace light","Lamp failed","ELECTRICAL","MEDIUM","KES");assertSame(saved,service.createWork(r));verify(properties).findByIdAndStaffOrOwner(4L,2L);}
 @Test void homeownerReadDoesNotInheritDormantSuperAdminScope(){when(users.getActiveRole()).thenReturn(PMSRole.HOMEOWNER);when(properties.findByIdAndHomeowner(4L,2L)).thenReturn(Optional.empty());assertThrows(PMSCustomException.class,()->service.meetingList(4L,PageRequest.of(0,20)));verify(users,never()).hasRole(PMSRole.SUPER_ADMIN);verify(properties,never()).findById(4L);}
 @Test void homeownerPageIsCappedAndBudgetLinesUseOneQuery(){when(users.getActiveRole()).thenReturn(PMSRole.HOMEOWNER);when(properties.findByIdAndHomeowner(4L,2L)).thenReturn(Optional.of(property));EstateBudget first=budget("APPROVED"),second=budget("CLOSED");second.setId(8L);PageRequest bounded=PageRequest.of(0,100);when(budgets.findAllByPropertyIdAndActiveTrue(4L,bounded)).thenReturn(new PageImpl<>(List.of(first,second),bounded,2));when(lines.findAllByBudgetIdInAndActiveTrueOrderByBudgetIdAscIdAsc(List.of(7L,8L))).thenReturn(List.of());service.budgetList(4L,PageRequest.of(0,500));verify(lines).findAllByBudgetIdInAndActiveTrueOrderByBudgetIdAscIdAsc(List.of(7L,8L));verify(lines,never()).findAllByBudgetIdAndActiveTrueOrderById(anyLong());}

 private EstateBudget budget(String status){EstateBudget b=new EstateBudget();b.setId(7L);b.setPropertyId(4L);b.setStatus(status);b.setActive(true);return b;}
 private EstateMeeting meeting(String status,int attendees){EstateMeeting m=new EstateMeeting();m.setId(8L);m.setPropertyId(4L);m.setStatus(status);m.setAttendeeCount(attendees);m.setActive(true);return m;}
 private EstateWorkOrder work(String status){EstateWorkOrder w=new EstateWorkOrder();w.setId(9L);w.setPropertyId(4L);w.setStatus(status);w.setActive(true);return w;}
}
