package org.pms.silverocean.service.estateops;
import lombok.RequiredArgsConstructor;import org.apache.commons.lang3.StringUtils;import org.pms.silverocean.common.*;import org.pms.silverocean.database.pms.*;import org.pms.silverocean.database.pms.entities.*;import org.pms.silverocean.service.PMSCustomException;import org.pms.silverocean.service.auth.dao.UserDao;import org.pms.silverocean.service.auth.roles.enums.PMSRole;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.data.domain.Page;import org.springframework.data.domain.Pageable;import java.math.BigDecimal;import java.time.ZonedDateTime;import java.util.*;
import org.pms.silverocean.service.auth.roles.enums.Permission;import org.springframework.data.domain.PageRequest;
@Service @RequiredArgsConstructor public class EstateOperationsService{private final EstateBudgetRepo budgets;private final EstateBudgetLineRepo lines;private final EstateMeetingRepo meetings;private final EstateResolutionRepo resolutions;private final EstateWorkOrderRepo workOrders;private final PropertyRepo properties;private final UserDao users;
 @Transactional public EstateBudget createBudget(EstateOperationsModels.BudgetCreate r){manage(r.propertyId());properties.findAndLockById(r.propertyId()).filter(Property::isActive).orElseThrow(this::invalid);if(budgets.countByPropertyIdAndBudgetYearAndActiveTrue(r.propertyId(),r.budgetYear())>0)throw invalid();EstateBudget b=new EstateBudget();b.setPropertyId(r.propertyId());b.setBudgetYear(r.budgetYear());b.setName(r.name().trim());b.setCurrency(r.currency().trim().toUpperCase());b.setStatus("DRAFT");creator(b);return budgets.save(b);}
 @Transactional public EstateBudgetLine addLine(long budgetId,EstateOperationsModels.BudgetLineCreate r){EstateBudget b=budgetForManagement(budgetId);if(!"DRAFT".equals(b.getStatus()))throw invalid();EstateBudgetLine l=new EstateBudgetLine();l.setBudgetId(budgetId);l.setCategory(r.category().trim());l.setDescription(StringUtils.trimToNull(r.description()));l.setPlannedAmount(r.plannedAmount());creator(l);return lines.save(l);}
 @Transactional public EstateBudget approve(long id){EstateBudget b=budgetForManagement(id);if(!"DRAFT".equals(b.getStatus())||lines.findAllByBudgetIdAndActiveTrueOrderById(id).isEmpty())throw invalid();b.setStatus("APPROVED");b.setApprovedAt(now());b.setApprovedBy(users.getUserId());return budgets.save(b);}
 @Transactional public EstateBudget close(long id){EstateBudget b=budgetForManagement(id);if(!"APPROVED".equals(b.getStatus()))throw invalid();b.setStatus("CLOSED");return budgets.save(b);}
 @Transactional public EstateBudgetLine actual(long lineId,EstateOperationsModels.Actual r){EstateBudgetLine l=lines.findById(lineId).filter(EstateBudgetLine::isActive).orElseThrow(this::invalid);EstateBudget b=budgetForManagement(l.getBudgetId());if(!"APPROVED".equals(b.getStatus()))throw invalid();l.setActualAmount(r.actualAmount());return lines.save(l);}
 public Page<EstateOperationsModels.BudgetView> budgetList(long propertyId,Pageable pageable){view(propertyId);Page<EstateBudget> page=budgets.findAllByPropertyIdAndActiveTrue(propertyId,bounded(pageable));Map<Long,List<EstateBudgetLine>> byBudget=lines.findAllByBudgetIdInAndActiveTrueOrderByBudgetIdAscIdAsc(page.getContent().stream().map(EstateBudget::getId).toList()).stream().collect(java.util.stream.Collectors.groupingBy(EstateBudgetLine::getBudgetId,LinkedHashMap::new,java.util.stream.Collectors.toList()));return page.map(b->budgetView(b,byBudget.getOrDefault(b.getId(),List.of())));}
 private EstateOperationsModels.BudgetView budgetView(EstateBudget b){List<EstateBudgetLine> ls=lines.findAllByBudgetIdAndActiveTrueOrderById(b.getId());return new EstateOperationsModels.BudgetView(b,ls,ls.stream().map(EstateBudgetLine::getPlannedAmount).reduce(BigDecimal.ZERO,BigDecimal::add),ls.stream().map(EstateBudgetLine::getActualAmount).reduce(BigDecimal.ZERO,BigDecimal::add));}
 private EstateOperationsModels.BudgetView budgetView(EstateBudget b,List<EstateBudgetLine> ls){return new EstateOperationsModels.BudgetView(b,ls,ls.stream().map(EstateBudgetLine::getPlannedAmount).reduce(BigDecimal.ZERO,BigDecimal::add),ls.stream().map(EstateBudgetLine::getActualAmount).reduce(BigDecimal.ZERO,BigDecimal::add));}
 @Transactional public EstateMeeting createMeeting(EstateOperationsModels.MeetingCreate r){manage(r.propertyId());EstateMeeting m=new EstateMeeting();m.setPropertyId(r.propertyId());m.setTitle(r.title().trim());m.setScheduledAt(r.scheduledAt());m.setVenue(StringUtils.trimToNull(r.venue()));m.setStatus("SCHEDULED");m.setQuorumRequired(r.quorumRequired());creator(m);return meetings.save(m);}
 @Transactional public EstateMeeting updateMeeting(long id,EstateOperationsModels.MeetingUpdate r){EstateMeeting m=meetings.findById(id).filter(EstateMeeting::isActive).orElseThrow(this::invalid);manage(m.getPropertyId());if(!"SCHEDULED".equals(m.getStatus()))throw invalid();if(r.status()==EstateOperationsModels.MeetingStatus.HELD&&(r.attendeeCount()<m.getQuorumRequired()||StringUtils.isBlank(r.minutes())))throw invalid();m.setStatus(r.status().name());m.setAttendeeCount(r.attendeeCount());m.setMinutes(StringUtils.trimToNull(r.minutes()));return meetings.save(m);}
 public Page<EstateMeeting> meetingList(long propertyId,Pageable pageable){view(propertyId);return meetings.findAllByPropertyIdAndActiveTrue(propertyId,bounded(pageable));}
 @Transactional public EstateResolution createResolution(long meetingId,EstateOperationsModels.ResolutionCreate r){EstateMeeting m=meetingForManagement(meetingId);if(!"HELD".equals(m.getStatus()))throw invalid();EstateResolution x=new EstateResolution();x.setMeetingId(meetingId);x.setTitle(r.title().trim());x.setDecision(StringUtils.trimToNull(r.decision()));x.setDueDate(r.dueDate());x.setStatus("PROPOSED");creator(x);return resolutions.save(x);}
 @Transactional public EstateResolution updateResolution(long id,EstateOperationsModels.ResolutionUpdate r){EstateResolution x=resolutions.findById(id).filter(EstateResolution::isActive).orElseThrow(this::invalid);EstateMeeting m=meetingForManagement(x.getMeetingId());String current=x.getStatus(),next=r.status().name();boolean allowed="PROPOSED".equals(current)&&List.of("PASSED","REJECTED").contains(next)||"PASSED".equals(current)&&"IMPLEMENTED".equals(next);long voteTotal=(long)r.votesFor()+r.votesAgainst()+r.votesAbstain();if(!allowed||voteTotal>m.getAttendeeCount()||("PASSED".equals(next)&&(r.votesFor()<=r.votesAgainst()||!"HELD".equals(m.getStatus()))))throw invalid();x.setStatus(next);x.setVotesFor(r.votesFor());x.setVotesAgainst(r.votesAgainst());x.setVotesAbstain(r.votesAbstain());if(StringUtils.isNotBlank(r.decision()))x.setDecision(r.decision().trim());if("IMPLEMENTED".equals(next))x.setImplementedAt(now());return resolutions.save(x);}
 public Page<EstateResolution> resolutionList(long meetingId,Pageable pageable){EstateMeeting m=meetings.findById(meetingId).filter(EstateMeeting::isActive).orElseThrow(this::invalid);view(m.getPropertyId());return resolutions.findAllByMeetingIdAndActiveTrue(meetingId,bounded(pageable));}
 @Transactional public EstateWorkOrder createWork(EstateOperationsModels.WorkCreate r){manage(r.propertyId());EstateWorkOrder w=new EstateWorkOrder();w.setWorkOrderNumber("EWO-"+UUID.randomUUID().toString().substring(0,8).toUpperCase());w.setPropertyId(r.propertyId());w.setAreaName(r.areaName().trim());w.setTitle(r.title().trim());w.setDescription(r.description().trim());w.setCategory(r.category().trim().toUpperCase());w.setPriority(r.priority().trim().toUpperCase());w.setStatus("OPEN");w.setCurrency(StringUtils.upperCase(StringUtils.trimToNull(r.currency())));creator(w);return workOrders.save(w);}
 @Transactional public EstateWorkOrder updateWork(long id,EstateOperationsModels.WorkUpdate r){EstateWorkOrder w=workOrders.findById(id).filter(EstateWorkOrder::isActive).orElseThrow(this::invalid);manage(w.getPropertyId());String c=w.getStatus(),n=r.status().name();boolean allowed="OPEN".equals(c)&&List.of("ACKNOWLEDGED","CANCELLED").contains(n)||"ACKNOWLEDGED".equals(c)&&List.of("IN_PROGRESS","CANCELLED").contains(n)||"IN_PROGRESS".equals(c)&&List.of("COMPLETED","CANCELLED").contains(n);if(!allowed||("COMPLETED".equals(n)&&StringUtils.isBlank(r.resolutionNotes())))throw invalid();w.setStatus(n);if(r.assignedProviderServiceId()!=null)w.setAssignedProviderServiceId(r.assignedProviderServiceId());if(r.scheduledAt()!=null)w.setScheduledAt(r.scheduledAt());if(r.estimatedCost()!=null)w.setEstimatedCost(r.estimatedCost());if(r.actualCost()!=null)w.setActualCost(r.actualCost());if(StringUtils.isNotBlank(r.resolutionNotes()))w.setResolutionNotes(r.resolutionNotes().trim());if("COMPLETED".equals(n))w.setCompletedAt(now());return workOrders.save(w);}
 public Page<EstateWorkOrder> workList(long propertyId,Pageable pageable){view(propertyId);return workOrders.findAllByPropertyIdAndActiveTrue(propertyId,bounded(pageable));}
 private EstateBudget budgetForManagement(long id){EstateBudget b=budgets.findById(id).filter(EstateBudget::isActive).orElseThrow(this::invalid);manage(b.getPropertyId());return b;}private EstateMeeting meetingForManagement(long id){EstateMeeting m=meetings.findById(id).filter(EstateMeeting::isActive).orElseThrow(this::invalid);manage(m.getPropertyId());return m;}
 private Property manage(long id){PMSRole role=users.getActiveRole();if(role==PMSRole.SUPER_ADMIN)return properties.findById(id).filter(Property::isActive).orElseThrow(this::invalid);if(role==PMSRole.LANDLORD||users.hasPermission(Permission.MANAGE_ESTATE))return properties.findByIdAndStaffOrOwner(id,users.getUserId()).orElseThrow(this::invalid);throw invalid();}private Property view(long id){PMSRole role=users.getActiveRole();if(role==PMSRole.SUPER_ADMIN)return properties.findById(id).filter(Property::isActive).orElseThrow(this::invalid);if(role==PMSRole.HOMEOWNER)return properties.findByIdAndHomeowner(id,users.getUserId()).orElseThrow(this::invalid);if(role==PMSRole.LANDLORD||users.hasPermission(Permission.VIEW_ESTATE))return properties.findByIdAndStaffOrOwner(id,users.getUserId()).orElseThrow(this::invalid);throw invalid();}
 private Pageable bounded(Pageable pageable){return PageRequest.of(Math.max(0,pageable.getPageNumber()),Math.min(100,Math.max(1,pageable.getPageSize())),pageable.getSort());}
 private void creator(org.pms.silverocean.database.pms.entities.base.BaseCreatorEntity e){e.setCreatedBy(users.getUserId());e.setActive(true);}private ZonedDateTime now(){return ZonedDateTime.now(PMSUtils.getZoneId());}private PMSCustomException invalid(){return new PMSCustomException(ResponseCode.INVALID_FIELD_DATA);}}
