package org.pms.silverocean.service.insurance;

import lombok.RequiredArgsConstructor;
import org.apache.commons.lang3.StringUtils;
import org.pms.silverocean.common.ResponseCode;
import org.pms.silverocean.database.pms.*;
import org.pms.silverocean.database.pms.entities.*;
import org.pms.silverocean.service.*;
import org.pms.silverocean.service.account.AccountService;
import org.pms.silverocean.service.account.dto.AccountDTO;
import org.pms.silverocean.service.account.enums.AccountCategory;
import org.pms.silverocean.service.auth.dao.UserDao;
import org.pms.silverocean.service.auth.roles.enums.Permission;
import org.pms.silverocean.service.filestorage.GarageService;
import org.pms.silverocean.service.filestorage.UploadMalwarePolicy;
import org.pms.silverocean.service.notification.*;
import org.pms.silverocean.service.notification.common.NotificationType;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.util.HtmlUtils;

import java.io.IOException;
import java.security.MessageDigest;
import java.time.*;
import java.util.*;
import java.util.stream.Collectors;
import static org.pms.silverocean.service.insurance.InsuranceModels.*;

@Service @RequiredArgsConstructor
public class InsuranceRenewalService {
 private static final long MAX_FILE=10L*1024*1024; private static final Set<String> TYPES=Set.of("application/pdf","image/jpeg","image/png");
 private final InsuranceAgencyRepo agencies; private final InsuranceCaseRepo cases; private final InsurancePolicyRepo policies; private final InsuranceCompanyRepo companies;
 private final InsuranceRenewalOfferRepo offers; private final InsuranceRenewalPaymentRepo payments; private final InsurancePaymentConfigurationRepo configurations;
 private final AccountService accountService; private final UserDao users; private final GarageService garage; private final UploadMalwarePolicy malwarePolicy; private final NotificationService notifications; private final I18NService i18n;
 @Value("${app.public-url:https://slickhood.com}") private String publicUrl;

 public List<RenewalJourneyView> mine(){return journeys(policies.findAllByCustomerUserIdAndActiveTrueOrderByEndDateDesc(uid()));}
 public List<RenewalJourneyView> queue(){long agency=agency().getId();return journeys(policies.findRenewalsByAgencyId(agency,LocalDate.now().minusDays(30),LocalDate.now().plusDays(90),PageRequest.of(0,100)).getContent());}

 @Transactional("pmsDBTransactionManager") public RenewalJourneyView request(long policyId){InsurancePolicy p=ownedLocked(policyId);if(!Set.of("UPCOMING","RENEWED").contains(p.getRenewalStatus())||p.getEndDate().isAfter(LocalDate.now().plusDays(90))||p.getEndDate().isBefore(LocalDate.now()))throw invalid();p.setRenewalStatus("CONTACTED");p.setRenewalContactedAt(LocalDateTime.now());policies.save(p);InsuranceCase c=cases.findById(p.getCaseId()).orElseThrow(this::notFound);String link=renewalLink(p.getId());notify(c.getEmail(),p.getPolicyNumber(),"REQUESTED",link);InsuranceAgency a=agency();if(StringUtils.isNotBlank(a.getSupportEmail()))notify(a.getSupportEmail(),p.getPolicyNumber(),"CUSTOMER REQUESTED RENEWAL",link);return journey(p);}

 @Transactional("pmsDBTransactionManager") public RenewalOfferView publishOffer(long policyId,RenewalOfferRequest r){InsurancePolicy p=staffLocked(policyId);if(!Set.of("UPCOMING","CONTACTED","RENEWED").contains(p.getRenewalStatus())||r.totalPremium().compareTo(r.basePremium().add(r.taxesLevies()))!=0||!r.coverStartDate().equals(p.getEndDate().plusDays(1))||r.coverEndDate().isBefore(r.coverStartDate())||r.validUntil().isAfter(r.coverStartDate()))throw invalid();offers.findFirstByPolicyIdAndActiveTrueOrderByCreatedOnDesc(policyId).filter(x->!Set.of("COMPLETED","LAPSED","EXPIRED").contains(x.getStatus())).ifPresent(x->{throw invalid();});InsuranceRenewalOffer o=new InsuranceRenewalOffer();o.setPolicyId(policyId);o.setQuoteNumber(r.quoteNumber().trim());o.setCurrency(r.currency());o.setBasePremium(r.basePremium());o.setTaxesLevies(r.taxesLevies());o.setTotalPremium(r.totalPremium());o.setCoverageSummary(r.coverageSummary().trim());o.setExclusions(StringUtils.trimToNull(r.exclusions()));o.setValidUntil(r.validUntil());o.setCoverStartDate(r.coverStartDate());o.setCoverEndDate(r.coverEndDate());o.setStatus("PUBLISHED");o.setApprovedBy(uid());o.setApprovedAt(LocalDateTime.now());stamp(o);o=offers.save(o);p.setRenewalStatus("RENEWAL_QUOTED");policies.save(p);InsuranceCase c=cases.findById(p.getCaseId()).orElseThrow(this::notFound);notify(c.getEmail(),p.getPolicyNumber(),"RENEWAL QUOTE READY - "+r.currency()+" "+r.totalPremium(),renewalLink(p.getId()));return offerView(o);}

 @Transactional("pmsDBTransactionManager") public RenewalJourneyView accept(long policyId){InsurancePolicy p=ownedLocked(policyId);if(!"ACTIVE".equals(p.getStatus())||p.getEndDate().isBefore(LocalDate.now())||!"RENEWAL_QUOTED".equals(p.getRenewalStatus()))throw invalid();InsuranceRenewalOffer o=currentOffer(policyId);if(!"PUBLISHED".equals(o.getStatus())||o.getValidUntil().isBefore(LocalDate.now()))throw invalid();o.setStatus("ACCEPTED");o.setAcceptedAt(LocalDateTime.now());offers.save(o);p.setRenewalStatus("ACCEPTED");policies.save(p);return journey(p);}

 @Transactional("pmsDBTransactionManager") public RenewalPaymentView recordPayment(long policyId,RenewalPaymentRequest r){InsurancePolicy p=ownedLocked(policyId);if(!"ACTIVE".equals(p.getStatus())||p.getEndDate().isBefore(LocalDate.now())||!"ACCEPTED".equals(p.getRenewalStatus())||r.paidAt().isAfter(LocalDateTime.now().plusMinutes(5)))throw invalid();InsuranceRenewalOffer o=currentOffer(policyId);if(!"ACCEPTED".equals(o.getStatus())||o.getAcceptedAt()==null||r.paidAt().isBefore(o.getAcceptedAt()))throw invalid();if(payments.findFirstByRenewalOfferIdAndActiveTrueOrderByCreatedOnDesc(o.getId()).filter(x->!"REJECTED".equals(x.getStatus())).isPresent())throw invalid();InsurancePaymentConfiguration cfg=configuration(p,r.paymentConfigurationId(),r.paidAt().toLocalDate());InsuranceRenewalPayment payment=new InsuranceRenewalPayment();payment.setPolicyId(policyId);payment.setRenewalOfferId(o.getId());payment.setPaymentConfigurationId(cfg.getId());payment.setAmount(o.getTotalPremium());payment.setCurrency(o.getCurrency());payment.setPaymentReference(r.paymentReference().trim());payment.setPaidAt(r.paidAt());payment.setStatus("PENDING_VERIFICATION");stamp(payment);payment=payments.save(payment);o.setStatus("PAYMENT_PENDING");offers.save(o);return paymentView(payment);}

 @Transactional("pmsDBTransactionManager") public RenewalPaymentView uploadProof(long id,MultipartFile file)throws IOException{InsuranceRenewalPayment p=payments.findByIdForUpdate(id).orElseThrow(this::notFound);if(!"PENDING_VERIFICATION".equals(p.getStatus())||StringUtils.isNotBlank(p.getProofFileRef()))throw invalid();owned(p.getPolicyId());byte[] bytes=validate(file);String ext=extension(file.getOriginalFilename());String ref="insurance/silverwood/"+uid()+"/renewals/"+UUID.randomUUID()+ext;garage.uploadBytes(ref,bytes,file.getContentType());p.setProofFileRef(ref);p.setProofContentType(file.getContentType());p.setProofFileSize((long)bytes.length);p.setProofChecksum(hash(bytes));return paymentView(payments.save(p));}
 public String proof(long id){InsuranceRenewalPayment p=payments.findByIdAndActiveTrue(id).orElseThrow(this::notFound);if(StringUtils.isBlank(p.getProofFileRef()))throw notFound();InsurancePolicy policy=policies.findById(p.getPolicyId()).filter(x->x.isActive()).orElseThrow(this::notFound);long user=uid();if(policy.getCustomerUserId()!=user){if(!users.hasPermission(Permission.VERIFY_INSURANCE_PAYMENTS))throw forbidden();cases.findById(policy.getCaseId()).filter(x->x.isActive()&&Objects.equals(x.getAgencyId(),agency().getId())).orElseThrow(this::notFound);}return garage.getPresignedUrlForStoredObject(p.getProofFileRef());}

 @Transactional("pmsDBTransactionManager") public RenewalPaymentView decide(long id,PaymentDecisionRequest r){InsuranceRenewalPayment p=payments.findByIdForUpdate(id).orElseThrow(this::notFound);if(!"PENDING_VERIFICATION".equals(p.getStatus())||"VERIFIED".equals(r.status())&&StringUtils.isBlank(p.getProofFileRef()))throw invalid();InsurancePolicy policy=staffLocked(p.getPolicyId());InsuranceRenewalOffer offer=offers.findByIdForUpdate(p.getRenewalOfferId()).orElseThrow(this::notFound);p.setStatus(r.status());p.setRejectionReason("REJECTED".equals(r.status())?StringUtils.trimToNull(r.reason()):null);if("VERIFIED".equals(r.status())){p.setVerifiedBy(uid());p.setVerifiedAt(LocalDateTime.now());offer.setStatus("PAID");policy.setRenewalStatus("PAID");}else{offer.setStatus("ACCEPTED");policy.setRenewalStatus("ACCEPTED");}offers.save(offer);policies.save(policy);InsuranceCase c=cases.findById(policy.getCaseId()).orElseThrow(this::notFound);notify(c.getEmail(),policy.getPolicyNumber(),"PAYMENT "+r.status(),renewalLink(policy.getId()));return paymentView(payments.save(p));}
 @Transactional("pmsDBTransactionManager") public RenewalPaymentView remit(long id,RemittanceRequest r){InsuranceRenewalPayment p=payments.findByIdForUpdate(id).orElseThrow(this::notFound);if(!"VERIFIED".equals(p.getStatus()))throw invalid();staffLocked(p.getPolicyId());InsuranceRenewalOffer offer=offers.findByIdForUpdate(p.getRenewalOfferId()).orElseThrow(this::notFound);p.setStatus("REMITTED");p.setRemittanceReference(r.reference().trim());p.setRemittedAt(LocalDateTime.now());offer.setStatus("REMITTED");offers.save(offer);return paymentView(payments.save(p));}
 @Transactional("pmsDBTransactionManager") public RenewalJourneyView complete(long policyId,RenewalCompleteRequest r){InsurancePolicy p=staffLocked(policyId);InsuranceRenewalOffer o=currentOffer(policyId);InsuranceRenewalPayment payment=payments.findFirstByRenewalOfferIdAndActiveTrueOrderByCreatedOnDesc(o.getId()).orElseThrow(this::notFound);if(!"PAID".equals(p.getRenewalStatus())||!"REMITTED".equals(o.getStatus())||!"REMITTED".equals(payment.getStatus())||policies.existsByPolicyNumberAndActiveTrueAndIdNot(r.policyNumber().trim(),policyId))throw invalid();p.setPolicyNumber(r.policyNumber().trim());p.setStartDate(o.getCoverStartDate());p.setEndDate(o.getCoverEndDate());p.setStatus("ACTIVE");p.setRenewalStatus("RENEWED");policies.save(p);o.setStatus("COMPLETED");o.setCompletedAt(LocalDateTime.now());offers.save(o);InsuranceCase c=cases.findById(p.getCaseId()).orElseThrow(this::notFound);notify(c.getEmail(),p.getPolicyNumber(),"RENEWED THROUGH "+p.getEndDate(),renewalLink(p.getId()));return journey(p);}

 private List<RenewalJourneyView> journeys(List<InsurancePolicy> list){if(list.isEmpty())return List.of();List<Long> ids=list.stream().map(InsurancePolicy::getId).toList();Map<Long,InsuranceRenewalOffer> latest=new LinkedHashMap<>();offers.findAllByPolicyIdInAndActiveTrueOrderByCreatedOnDesc(ids).forEach(o->latest.putIfAbsent(o.getPolicyId(),o));Map<Long,InsuranceRenewalPayment> paid=new HashMap<>();List<Long> offerIds=latest.values().stream().map(InsuranceRenewalOffer::getId).toList();if(!offerIds.isEmpty())payments.findAllByRenewalOfferIdInAndActiveTrueOrderByCreatedOnDesc(offerIds).forEach(p->paid.putIfAbsent(p.getRenewalOfferId(),p));Map<Long,String> codes=companies.findAllById(list.stream().map(InsurancePolicy::getCompanyId).distinct().toList()).stream().collect(Collectors.toMap(InsuranceCompany::getId,InsuranceCompany::getCode));return list.stream().map(p->{InsuranceRenewalOffer o=latest.get(p.getId());return new RenewalJourneyView(p.getId(),codes.get(p.getCompanyId()),o==null?null:offerView(o),o==null||paid.get(o.getId())==null?null:paymentView(paid.get(o.getId())));}).toList();}
 private RenewalJourneyView journey(InsurancePolicy p){return journeys(List.of(p)).getFirst();}
 private RenewalOfferView offerView(InsuranceRenewalOffer o){return new RenewalOfferView(o.getId(),o.getPolicyId(),o.getQuoteNumber(),o.getCurrency(),o.getBasePremium(),o.getTaxesLevies(),o.getTotalPremium(),o.getCoverageSummary(),o.getExclusions(),o.getValidUntil(),o.getCoverStartDate(),o.getCoverEndDate(),o.getStatus());}
 private RenewalPaymentView paymentView(InsuranceRenewalPayment p){return new RenewalPaymentView(p.getId(),p.getPolicyId(),p.getRenewalOfferId(),p.getPaymentConfigurationId(),p.getAmount(),p.getCurrency(),p.getPaymentReference(),p.getPaidAt(),p.getStatus(),p.getRejectionReason(),p.getRemittanceReference(),p.getRemittedAt(),StringUtils.isNotBlank(p.getProofFileRef()),p.getProofContentType());}
 private InsuranceRenewalOffer currentOffer(long policyId){return offers.findFirstByPolicyIdAndActiveTrueOrderByCreatedOnDesc(policyId).orElseThrow(this::notFound);}
 private InsurancePolicy owned(long id){return policies.findByIdAndCustomerUserIdAndActiveTrue(id,uid()).orElseThrow(this::notFound);} private InsurancePolicy ownedLocked(long id){InsurancePolicy p=policies.findByIdForUpdate(id).orElseThrow(this::notFound);if(p.getCustomerUserId()!=uid())throw notFound();return p;}
 private InsurancePolicy staffLocked(long id){InsurancePolicy p=policies.findByIdForUpdate(id).orElseThrow(this::notFound);InsuranceCase c=cases.findById(p.getCaseId()).filter(x->x.isActive()&&Objects.equals(x.getAgencyId(),agency().getId())).orElseThrow(this::notFound);return p;}
 private InsurancePaymentConfiguration configuration(InsurancePolicy p,long id,LocalDate paidOn){InsurancePaymentConfiguration c=configurations.findById(id).filter(InsurancePaymentConfiguration::isActive).filter(x->x.getCompanyId()==p.getCompanyId()).filter(x->!x.getEffectiveFrom().isAfter(paidOn)).filter(x->x.getEffectiveTo()==null||!x.getEffectiveTo().isBefore(paidOn)).orElseThrow(this::notFound);AccountDTO a=accountService.getAccount(c.getPaymentAccountId());if(!a.active()||!a.verified()||a.category()!=AccountCategory.INSURANCE||a.channel()!=c.getPaymentChannel())throw invalid();return c;}
 private InsuranceAgency agency(){return agencies.findByCodeAndActiveTrue("SILVERWOOD").orElseThrow(this::notFound);} private long uid(){return users.getUserId();}
 private void stamp(org.pms.silverocean.database.pms.entities.base.BaseCreatorEntity e){e.setCreatedBy(uid());e.setActive(true);} private String renewalLink(long id){return StringUtils.removeEnd(publicUrl,"/")+"/dashboard/insurance?tab=policies&policyId="+id;}
 private void notify(String email,String policy,String state,String link){String body=String.format(i18n.getLocalizedMessage(NotificationType.INSURANCE_RENEWAL_EMAIL.getBody()),HtmlUtils.htmlEscape(policy),HtmlUtils.htmlEscape(state),HtmlUtils.htmlEscape(link));notifications.queueNotification(new NotificationDTO(body,email,NotificationType.INSURANCE_RENEWAL_EMAIL));}
 private byte[] validate(MultipartFile f)throws IOException{if(f==null||f.isEmpty()||f.getSize()>MAX_FILE||!TYPES.contains(f.getContentType()))throw new PMSCustomException(ResponseCode.UNSUPPORTED_MEDIA_TYPE);byte[] b=f.getBytes();boolean ok="application/pdf".equals(f.getContentType())?b.length>4&&b[0]=='%'&&b[1]=='P'&&b[2]=='D'&&b[3]=='F':"image/png".equals(f.getContentType())?b.length>8&&(b[0]&255)==0x89&&b[1]=='P'&&b[2]=='N'&&b[3]=='G':b.length>3&&(b[0]&255)==0xff&&(b[1]&255)==0xd8;if(!ok)throw new PMSCustomException(ResponseCode.UNSUPPORTED_MEDIA_TYPE);malwarePolicy.requireSafe(b);return b;}
 private String extension(String n){String safe=StringUtils.defaultString(n);int dot=safe.lastIndexOf('.');return dot<0?"":safe.substring(dot).toLowerCase(Locale.ROOT).replaceAll("[^.a-z0-9]","");} private String hash(byte[] b){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(b));}catch(Exception e){throw new IllegalStateException(e);}}
 private PMSCustomException invalid(){return new PMSCustomException(ResponseCode.INVALID_FIELD_DATA);} private PMSCustomException notFound(){return new PMSCustomException(ResponseCode.RESOURCE_NOT_FOUND);} private PMSCustomException forbidden(){return new PMSCustomException(ResponseCode.FORBIDDEN_ACCESS);}
}
