package org.pms.silverocean.service.insurance;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import org.apache.commons.lang3.StringUtils;
import org.pms.silverocean.common.ResponseCode;
import org.pms.silverocean.database.pms.*;
import org.pms.silverocean.database.pms.entities.*;
import org.pms.silverocean.service.PMSCustomException;
import org.pms.silverocean.service.I18NService;
import org.pms.silverocean.service.auth.dao.UserDao;
import org.pms.silverocean.service.account.AccountService;
import org.pms.silverocean.service.account.dto.AccountDTO;
import org.pms.silverocean.service.account.enums.AccountCategory;
import org.pms.silverocean.service.auth.roles.enums.Permission;
import org.pms.silverocean.service.auth.roles.enums.PMSRole;
import org.pms.silverocean.service.filestorage.GarageService;
import org.pms.silverocean.service.filestorage.UploadMalwarePolicy;
import org.pms.silverocean.service.notification.NotificationDTO;
import org.pms.silverocean.service.notification.NotificationService;
import org.pms.silverocean.service.notification.common.NotificationType;
import org.springframework.data.domain.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.util.HtmlUtils;

import java.io.IOException;
import java.math.BigDecimal;
import java.security.MessageDigest;
import java.time.*;
import java.util.*;
import java.util.stream.Collectors;

import static org.pms.silverocean.service.insurance.InsuranceModels.*;

@Service @RequiredArgsConstructor
public class InsuranceOperationsService {
 private static final String AGENCY="SILVERWOOD";
 private static final long MAX_FILE=10L*1024*1024;
 private static final Set<String> TYPES=Set.of("application/pdf","image/jpeg","image/png");
 private static final Set<String> CATEGORIES=Set.of("PROPOSAL","KYC","QUOTATION","PAYMENT_EVIDENCE","INSURER_RECEIPT","POLICY_SCHEDULE","CERTIFICATE","POLICY_WORDING","CLAIM_EVIDENCE","ASSESSMENT","RENEWAL_DOCUMENT");
 private final InsuranceAgencyRepo agencyRepo; private final InsuranceCompanyRepo companyRepo; private final InsuranceCaseRepo caseRepo;
 private final InsuranceQuoteRepo quoteRepo; private final InsurancePremiumPaymentRepo paymentRepo; private final InsurancePaymentConfigurationRepo paymentConfigurationRepo; private final InsurancePolicyRepo policyRepo;
 private final InsuranceClaimRepo claimRepo; private final InsuranceDocumentRepo documentRepo; private final InsuranceActivityRepo activityRepo;
 private final InsuranceStaffDirectoryService staffDirectory;
 private final ObjectMapper objectMapper;
 private final InsuranceCorrespondenceService correspondenceService;
 private final UserDao userDao; private final UserRoleRepo userRoleRepo; private final AccountService accountService; private final GarageService garageService; private final UploadMalwarePolicy malwarePolicy; private final NotificationService notifications; private final I18NService i18n;
 @Value("${app.public-url:https://slickhood.com}") private String publicUrl;

 public AgencyView agency(){var a=agencyEntity();return new AgencyView(a.getCode(),a.getName(),a.getSupportEmail(),a.getSupportPhone(),a.getLogoUrl());}
 public List<ProductView> products(){return List.of(
  new ProductView("MOTOR","Motor Insurance","Vehicles, trailers, prime movers, PSV and special-purpose equipment.",List.of("VEHICLE","TRAILER","PRIME_MOVER","BUS","PSV","TOUR_VAN","SPECIAL_TYPE")),
  new ProductView("DOMESTIC","Domestic Package","Buildings for landlords and household contents for landlords or tenants.",List.of("PROPERTY","HOUSEHOLD_ITEMS")),
  new ProductView("FIRE_ALLIED","Fire & Allied Perils","Itemised property and asset cover against fire and allied risks.",List.of("PROPERTY")),
  new ProductView("WIBA_EL","WIBA","Employee injury cover based on the declared employee payroll schedule.",List.of("EMPLOYEES")),
  new ProductView("CONTRACTORS_ALL_RISK","Contractors' All Risk","Construction works and third-party liability protection.",List.of("PROJECT")),
  new ProductView("MEDICAL","Medical","Individual, family and corporate medical cover.",List.of("FAMILY_INDIVIDUAL","CORPORATE")),
  new ProductView("MARINE_CARGO","Marine Cargo","Commercial-invoice based sea or air cargo protection.",List.of("GOODS")),
  new ProductView("TRAVEL","Travel","Medical emergencies and travel disruption cover.",List.of("TRIP")),
  new ProductView("GOODS_IN_TRANSIT","Goods in Transit","Protection for goods carried by owned or hired vehicles.",List.of("GOODS")));
 }

 @Transactional("pmsDBTransactionManager") public CaseView create(CaseRequest r){
  if(!Boolean.TRUE.equals(r.consent())||r.coverStartDate()!=null&&r.coverStartDate().isBefore(LocalDate.now()))throw invalid();
  validateProposal(r.productCode(),r.subjectType(),r.proposalData());
  Map<String,Object> normalizedProposal=normalizedProposal(r.productCode(),r.proposalData());String proposalJson=proposalJson(normalizedProposal);if(proposalJson.length()>100_000)throw invalid();
  InsuranceCase c=new InsuranceCase();c.setAgencyId(agencyEntity().getId());c.setCustomerUserId(uid());c.setReference(ref("INS"));c.setProductCode(r.productCode());
  c.setStatus("SUBMITTED");c.setFullName(r.fullName().trim());c.setEmail(r.email().trim().toLowerCase(Locale.ROOT));c.setPhone(r.phone().trim());c.setSubjectType(r.subjectType());
  c.setSubjectDescription(r.subjectDescription().trim());c.setSumInsured(calculatedSumInsured(r.productCode(),normalizedProposal));c.setCurrency(r.currency());c.setCoverStartDate(r.coverStartDate());
  c.setRiskDetails(StringUtils.trimToNull(r.riskDetails()));c.setProposalDataJson(proposalJson);c.setConsentAt(LocalDateTime.now());c.setSubmittedAt(LocalDateTime.now());stamp(c);caseRepo.save(c);activity(c.getId(),null,"CASE_SUBMITTED",null,c.getStatus(),null);notifyEmail(c.getEmail(),NotificationType.INSURANCE_APPLICATION_EMAIL,c.getReference());String agencyEmail=agencyEntity().getSupportEmail();if(StringUtils.isNotBlank(agencyEmail))notifyEmail(agencyEmail,NotificationType.INSURANCE_NEW_PROPOSAL_EMAIL,c.getReference(),c.getProductCode());return view(c);
 }
 public List<CaseView> mine(){return caseViews(caseRepo.findAllByCustomerUserIdAndActiveTrueOrderByCreatedOnDesc(uid()));}
 public CaseView myCase(long id){return view(ownedCase(id));}
 public Page<CaseView> queue(String status,Pageable pageable){Pageable p=PageRequest.of(Math.max(0,pageable.getPageNumber()),Math.min(100,Math.max(1,pageable.getPageSize())),Sort.by(Sort.Direction.ASC,"createdOn"));long a=agencyEntity().getId();Page<InsuranceCase> page=StringUtils.isBlank(status)?caseRepo.findAllByAgencyIdAndActiveTrue(a,p):caseRepo.findAllByAgencyIdAndStatusAndActiveTrue(a,status.toUpperCase(Locale.ROOT),p);return new PageImpl<>(caseViews(page.getContent()),p,page.getTotalElements());}
 @Transactional("pmsDBTransactionManager") public CaseView assign(long id,AssignmentRequest r){if(!staffDirectory.isEligible(r.adviserUserId()))throw invalid();InsuranceCase c=lockedCase(id);c.setAssignedAdviserId(r.adviserUserId());if("SUBMITTED".equals(c.getStatus()))transition(c,"ADVISER_ASSIGNED","CASE_ASSIGNED",null);else caseRepo.save(c);return view(c);}
 @Transactional("pmsDBTransactionManager") public CaseView withdraw(long id){InsuranceCase c=lockedOwnedCase(id);if(!InsuranceStateMachine.canCustomerWithdraw(c.getStatus()))throw invalid();transition(c,"WITHDRAWN","CUSTOMER_WITHDREW",null);return view(c);}
 @Transactional("pmsDBTransactionManager") public CaseView updateCaseStatus(long id,CaseStatusRequest r){InsuranceCase c=lockedCase(id);if(!InsuranceStateMachine.canMoveCase(c.getStatus(),r.status()))throw invalid();transition(c,r.status(),"CASE_STATUS_CHANGED",r.note());return view(c);}

 @Transactional("pmsDBTransactionManager") public QuoteView addQuote(long caseId,QuoteRequest r){InsuranceCase c=lockedCase(caseId);if(!InsuranceStateMachine.canReceiveQuote(c.getStatus())||!Objects.equals(c.getAgencyId(),agencyEntity().getId()))throw invalid();InsuranceCompany company=companyRepo.findById(r.companyId()).filter(x->x.isActive()&&x.getAgencyId()==c.getAgencyId()).orElseThrow(this::notFound);if(r.totalPremium().compareTo(r.basePremium().add(r.taxesLevies()))!=0)throw invalid();InsuranceQuote q=new InsuranceQuote();q.setCaseId(c.getId());q.setCompanyId(company.getId());q.setQuoteNumber(StringUtils.trimToNull(r.quoteNumber()));q.setStatus("DRAFT");q.setCurrency(r.currency());q.setBasePremium(r.basePremium());q.setTaxesLevies(r.taxesLevies());q.setTotalPremium(r.totalPremium());q.setExcessDetails(StringUtils.trimToNull(r.excessDetails()));q.setCoverageSummary(r.coverageSummary().trim());q.setExclusions(StringUtils.trimToNull(r.exclusions()));q.setValidUntil(r.validUntil());q.setPreparedBy(uid());stamp(q);quoteRepo.save(q);activity(c.getId(),null,"QUOTE_PREPARED",null,null,company.getName());return quoteView(q);}
 public EmailExchangeView requestInsurerQuote(long caseId,QuoteDispatchRequest request){InsuranceCase c=caseForAgency(caseId);List<InsuranceDocument> proposalDocuments=documentRepo.findAllByCaseIdAndActiveTrueOrderByCreatedOnDesc(c.getId()).stream().filter(d->"PROPOSAL".equals(d.getCategory())).toList();if("MARINE_CARGO".equals(c.getProductCode())&&proposalDocuments.isEmpty())throw invalid();String details;try{details=objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString(proposalData(c.getProposalDataJson()));}catch(Exception e){details="{}";}String attachments=proposalDocuments.isEmpty()?"":"<p><strong>Proposal documents (secure links expire):</strong></p><ul>"+proposalDocuments.stream().map(d->"<li><a href=\""+HtmlUtils.htmlEscape(garageService.getPresignedUrlForStoredObject(d.getFileRef()))+"\">"+HtmlUtils.htmlEscape(d.getDisplayName())+"</a></li>").collect(Collectors.joining())+"</ul>";String body="<p>Please prepare a quotation for the following Silverwood proposal.</p>"+
   "<p><strong>Applicant:</strong> "+HtmlUtils.htmlEscape(c.getFullName())+"<br><strong>Product:</strong> "+HtmlUtils.htmlEscape(c.getProductCode())+"<br><strong>Subject:</strong> "+HtmlUtils.htmlEscape(c.getSubjectDescription())+"<br><strong>Preferred start:</strong> "+HtmlUtils.htmlEscape(Objects.toString(c.getCoverStartDate(),"Not specified"))+"</p>"+
    "<pre>"+HtmlUtils.htmlEscape(details)+"</pre>"+attachments+"<p>Please reply to this email without removing the Silverwood reference and correlation ID.</p>";
  return correspondenceService.queue(new InsurerEmailRequest(request.companyCode(),c.getReference(),"QUOTATION_REQUEST","Quotation request — "+c.getProductCode(),body));}
 @Transactional("pmsDBTransactionManager") public QuoteView publishQuote(long caseId,long quoteId){InsuranceCase c=lockedCase(caseId);if(!InsuranceStateMachine.canReceiveQuote(c.getStatus()))throw invalid();InsuranceQuote q=quoteRepo.findByIdAndCaseIdAndActiveTrue(quoteId,caseId).orElseThrow(this::notFound);if(!"DRAFT".equals(q.getStatus())||q.getValidUntil().isBefore(LocalDate.now()))throw invalid();q.setStatus("PUBLISHED");q.setApprovedBy(uid());q.setApprovedAt(LocalDateTime.now());quoteRepo.save(q);if(!"QUOTED".equals(c.getStatus())){c.setQuotedAt(LocalDateTime.now());transition(c,"QUOTED","QUOTES_PUBLISHED",null);}notifyEmail(c.getEmail(),NotificationType.INSURANCE_QUOTE_EMAIL,c.getReference());return quoteView(q);}
 @Transactional("pmsDBTransactionManager") public CaseView selectQuote(long caseId,SelectQuoteRequest r){InsuranceCase c=lockedOwnedCase(caseId);if(!"QUOTED".equals(c.getStatus()))throw invalid();InsuranceQuote q=quoteRepo.findByIdAndCaseIdAndActiveTrue(r.quoteId(),caseId).filter(x->"PUBLISHED".equals(x.getStatus())&&!x.getValidUntil().isBefore(LocalDate.now())).orElseThrow(this::notFound);quoteRepo.findAllByCaseIdAndActiveTrueOrderByTotalPremiumAsc(caseId).forEach(x->{if("PUBLISHED".equals(x.getStatus()))x.setStatus(x.getId().equals(q.getId())?"SELECTED":"NOT_SELECTED");});c.setSelectedQuoteId(q.getId());c.setSelectedAt(LocalDateTime.now());transition(c,"CUSTOMER_SELECTED","QUOTE_SELECTED",q.getId().toString());return view(c);}

 @Transactional("pmsDBTransactionManager") public PaymentView recordPayment(long caseId,PaymentRequest r){InsuranceCase c=lockedOwnedCase(caseId);if(!"CUSTOMER_SELECTED".equals(c.getStatus())||c.getSelectedQuoteId()==null)throw invalid();InsuranceQuote q=quoteRepo.findByIdAndCaseIdAndActiveTrue(c.getSelectedQuoteId(),caseId).orElseThrow(this::notFound);if(r.amount().compareTo(q.getTotalPremium())!=0||!r.currency().equals(q.getCurrency())||r.paidAt().isAfter(LocalDateTime.now().plusMinutes(5)))throw invalid();InsurancePaymentConfiguration configuration=paymentConfiguration(q,r.paymentConfigurationId(),r.paidAt().toLocalDate());InsurancePremiumPayment p=new InsurancePremiumPayment();p.setCaseId(caseId);p.setQuoteId(q.getId());p.setPaymentConfigurationId(configuration.getId());p.setAmount(r.amount());p.setCurrency(r.currency());p.setPaymentReference(r.paymentReference().trim());p.setPaidAt(r.paidAt());p.setStatus("PENDING_VERIFICATION");stamp(p);paymentRepo.save(p);transition(c,"PAYMENT_PENDING","PAYMENT_RECORDED",null);return paymentView(p);}
 @Transactional("pmsDBTransactionManager") public PaymentView uploadPaymentProof(long paymentId,MultipartFile file)throws IOException{InsurancePremiumPayment p=paymentRepo.findByIdForUpdate(paymentId).orElseThrow(this::notFound);if(!"PENDING_VERIFICATION".equals(p.getStatus())||StringUtils.isNotBlank(p.getProofFileRef()))throw invalid();InsuranceCase c=ownedCase(p.getCaseId());byte[] bytes=validate(file);String ref=path(c.getCustomerUserId(),"payments",file);garageService.uploadBytes(ref,bytes,file.getContentType());p.setProofFileRef(ref);p.setProofContentType(file.getContentType());p.setProofFileSize((long)bytes.length);p.setProofChecksum(hash(bytes));paymentRepo.save(p);return paymentView(p);}
 public String paymentProof(long paymentId){InsurancePremiumPayment p=paymentRepo.findByIdAndActiveTrue(paymentId).orElseThrow(this::notFound);if(StringUtils.isBlank(p.getProofFileRef()))throw notFound();InsuranceCase c=caseRepo.findById(p.getCaseId()).filter(x->x.isActive()&&Objects.equals(x.getAgencyId(),agencyEntity().getId())).orElseThrow(this::notFound);if(c.getCustomerUserId()!=uid()&&!userDao.hasPermission(Permission.VERIFY_INSURANCE_PAYMENTS))throw forbidden();return garageService.getPresignedUrlForStoredObject(p.getProofFileRef());}
 @Transactional("pmsDBTransactionManager") public PaymentView decidePayment(long id,PaymentDecisionRequest r){InsurancePremiumPayment p=paymentRepo.findByIdForUpdate(id).orElseThrow(this::notFound);if(!"PENDING_VERIFICATION".equals(p.getStatus())||"VERIFIED".equals(r.status())&&StringUtils.isBlank(p.getProofFileRef()))throw invalid();p.setStatus(r.status());p.setRejectionReason("REJECTED".equals(r.status())?StringUtils.trimToNull(r.reason()):null);InsuranceCase c=lockedCase(p.getCaseId());if(!"PAYMENT_PENDING".equals(c.getStatus()))throw invalid();if("VERIFIED".equals(r.status())){p.setVerifiedBy(uid());p.setVerifiedAt(LocalDateTime.now());transition(c,"PAYMENT_VERIFIED","PAYMENT_VERIFIED",null);}else transition(c,"CUSTOMER_SELECTED","PAYMENT_REJECTED",r.reason());notifyEmail(c.getEmail(),NotificationType.INSURANCE_PAYMENT_EMAIL,c.getReference(),r.status());return paymentView(paymentRepo.save(p));}
 @Transactional("pmsDBTransactionManager") public PaymentView remit(long id,RemittanceRequest r){InsurancePremiumPayment p=paymentRepo.findByIdForUpdate(id).orElseThrow(this::notFound);if(!"VERIFIED".equals(p.getStatus()))throw invalid();InsuranceCase c=lockedCase(p.getCaseId());if(!"PAYMENT_VERIFIED".equals(c.getStatus()))throw invalid();p.setStatus("REMITTED");p.setRemittanceReference(r.reference().trim());p.setRemittedAt(LocalDateTime.now());transition(c,"PREMIUM_REMITTED","PREMIUM_REMITTED",r.reference());return paymentView(paymentRepo.save(p));}
 @Transactional("pmsDBTransactionManager") public PolicyView issue(long caseId,PolicyRequest r){InsuranceCase c=lockedCase(caseId);if(!"PREMIUM_REMITTED".equals(c.getStatus())||c.getSelectedQuoteId()==null||r.endDate().isBefore(r.startDate())||policyRepo.findByCaseIdAndActiveTrue(caseId).isPresent())throw invalid();InsuranceQuote q=quoteRepo.findByIdAndCaseIdAndActiveTrue(c.getSelectedQuoteId(),caseId).orElseThrow(this::notFound);InsurancePolicy p=new InsurancePolicy();p.setCaseId(caseId);p.setQuoteId(q.getId());p.setCompanyId(q.getCompanyId());p.setCustomerUserId(c.getCustomerUserId());p.setPolicyNumber(r.policyNumber().trim());p.setStatus("ACTIVE");p.setStartDate(r.startDate());p.setEndDate(r.endDate());p.setRenewalStatus("UPCOMING");p.setIssuedBy(uid());p.setIssuedAt(LocalDateTime.now());stamp(p);policyRepo.save(p);transition(c,"POLICY_ISSUED","POLICY_ISSUED",p.getPolicyNumber());notifyEmail(c.getEmail(),NotificationType.INSURANCE_POLICY_EMAIL,p.getPolicyNumber(),c.getReference());return policyView(p);}
 public List<PolicyView> policies(){return policyViews(policyRepo.findAllByCustomerUserIdAndActiveTrueOrderByEndDateDesc(uid()));}

 @Transactional("pmsDBTransactionManager") public ClaimView claim(ClaimRequest r){InsurancePolicy p=policyRepo.findByIdAndCustomerUserIdAndActiveTrue(r.policyId(),uid()).orElseThrow(this::notFound);LocalDate incidentDate=r.incidentAt().toLocalDate();if(!Set.of("ACTIVE","EXPIRED").contains(p.getStatus())||incidentDate.isBefore(p.getStartDate())||incidentDate.isAfter(p.getEndDate())||r.incidentAt().isAfter(LocalDateTime.now().plusMinutes(5)))throw invalid();InsuranceClaim c=new InsuranceClaim();c.setPolicyId(p.getId());c.setCustomerUserId(uid());c.setReference(ref("CLM"));c.setStatus("SUBMITTED");c.setIncidentAt(r.incidentAt());c.setIncidentLocation(StringUtils.trimToNull(r.incidentLocation()));c.setDescription(r.description().trim());c.setEstimatedAmount(r.estimatedAmount());c.setSubmittedAt(LocalDateTime.now());stamp(c);claimRepo.save(c);activity(null,c.getId(),"CLAIM_SUBMITTED",null,"SUBMITTED",null);InsuranceCase insuranceCase=caseRepo.findById(p.getCaseId()).orElseThrow(this::notFound);notifyEmail(insuranceCase.getEmail(),NotificationType.INSURANCE_CLAIM_EMAIL,c.getReference(),c.getStatus());return claimView(c);}
 public List<ClaimView> claims(){return claimViews(claimRepo.findAllByCustomerUserIdAndActiveTrueOrderByCreatedOnDesc(uid()));}
 public Page<ClaimView> claimQueue(String status,Pageable pageable){Pageable p=PageRequest.of(Math.max(0,pageable.getPageNumber()),Math.min(100,Math.max(1,pageable.getPageSize())),Sort.by("createdOn").ascending());long agencyId=agencyEntity().getId();Page<InsuranceClaim> page=StringUtils.isBlank(status)?claimRepo.findQueueByAgencyId(agencyId,p):claimRepo.findQueueByAgencyIdAndStatus(agencyId,status.toUpperCase(Locale.ROOT),p);return new PageImpl<>(claimViews(page.getContent()),p,page.getTotalElements());}
 @Transactional("pmsDBTransactionManager") public ClaimView updateClaim(long id,ClaimStatusRequest r){InsuranceClaim c=claimRepo.findByIdForUpdate(id).orElseThrow(this::notFound);InsurancePolicy p=policyRepo.findById(c.getPolicyId()).orElseThrow(this::notFound);InsuranceCase insuranceCase=caseForAgency(p.getCaseId());if(!InsuranceStateMachine.canMoveClaim(c.getStatus(),r.status()))throw invalid();String from=c.getStatus();c.setStatus(r.status());c.setInsurerReference(StringUtils.defaultIfBlank(r.insurerReference(),c.getInsurerReference()));c.setResolutionNotes(StringUtils.defaultIfBlank(r.note(),c.getResolutionNotes()));if("CLOSED".equals(r.status()))c.setClosedAt(LocalDateTime.now());claimRepo.save(c);activity(null,c.getId(),"CLAIM_STATUS_CHANGED",from,r.status(),r.note());notifyEmail(insuranceCase.getEmail(),NotificationType.INSURANCE_CLAIM_EMAIL,c.getReference(),r.status());return claimView(c);}
 @Transactional("pmsDBTransactionManager") public PolicyView renewal(long id,RenewalRequest r){if(!Set.of("CONTACTED","LAPSED").contains(r.status()))throw invalid();InsurancePolicy p=policyRepo.findById(id).filter(x->x.isActive()).orElseThrow(this::notFound);InsuranceCase insuranceCase=caseForAgency(p.getCaseId());if(!InsuranceStateMachine.canMoveRenewal(p.getRenewalStatus(),r.status()))throw invalid();p.setRenewalStatus(r.status());if("CONTACTED".equals(r.status()))p.setRenewalContactedAt(LocalDateTime.now());if("LAPSED".equals(r.status()))p.setStatus("EXPIRED");p=policyRepo.save(p);notifyEmail(insuranceCase.getEmail(),NotificationType.INSURANCE_RENEWAL_EMAIL,p.getPolicyNumber(),r.status(),StringUtils.removeEnd(publicUrl,"/")+"/dashboard/insurance?tab=policies&policyId="+p.getId());return policyView(p);}

 @Transactional("pmsDBTransactionManager") public DocumentView upload(Long caseId,Long policyId,Long claimId,String category,MultipartFile file)throws IOException{if((caseId==null?0:1)+(policyId==null?0:1)+(claimId==null?0:1)!=1)throw invalid();String cat=category.toUpperCase(Locale.ROOT);if(!CATEGORIES.contains(cat))throw invalid();long owner=resolveOwner(caseId,policyId,claimId);if(owner!=uid()&&!staff())throw forbidden();byte[] bytes=validate(file);String ref=path(owner,"documents",file);garageService.uploadBytes(ref,bytes,file.getContentType());InsuranceDocument d=new InsuranceDocument();d.setCustomerUserId(owner);d.setCaseId(caseId);d.setPolicyId(policyId);d.setClaimId(claimId);d.setCategory(cat);d.setDisplayName(safeName(file.getOriginalFilename()));d.setFileRef(ref);d.setContentType(file.getContentType());d.setFileSize(bytes.length);d.setChecksumSha256(hash(bytes));d.setUploadedBy(uid());d.setVersionNumber(caseId==null?1:(int)documentRepo.countByCaseIdAndCategoryAndActiveTrue(caseId,cat)+1);stamp(d);return documentView(documentRepo.save(d));}
 public List<DocumentView> documents(){return documentRepo.findAllByCustomerUserIdAndActiveTrueOrderByCreatedOnDesc(uid()).stream().map(this::documentView).toList();}
 public DocumentView document(long id){InsuranceDocument d=documentRepo.findByIdAndActiveTrue(id).orElseThrow(this::notFound);if(d.getCustomerUserId()!=uid()&&!staff())throw forbidden();return documentView(d);}
 public OperationsSummary summary(){long a=agencyEntity().getId();return new OperationsSummary(caseRepo.countByAgencyIdAndActiveTrueAndStatusNotIn(a,Set.of("WITHDRAWN","POLICY_ISSUED")),caseRepo.countByAgencyIdAndActiveTrueAndAssignedAdviserIdIsNullAndStatusNotIn(a,Set.of("WITHDRAWN","POLICY_ISSUED")),paymentRepo.countByAgencyIdAndStatus(a,"PENDING_VERIFICATION"),claimRepo.countOpenByAgencyId(a,Set.of("CLOSED")),policyRepo.countRenewalsByAgencyId(a,LocalDate.now(),LocalDate.now().plusDays(60)));}
 public Page<PolicyView> renewalQueue(Pageable pageable){Pageable p=PageRequest.of(Math.max(0,pageable.getPageNumber()),Math.min(100,Math.max(1,pageable.getPageSize())),Sort.by("endDate").ascending());Page<InsurancePolicy> page=policyRepo.findRenewalsByAgencyId(agencyEntity().getId(),LocalDate.now(),LocalDate.now().plusDays(90),p);return new PageImpl<>(policyViews(page.getContent()),p,page.getTotalElements());}

 private CaseView view(InsuranceCase c){return caseViews(List.of(c)).getFirst();}
 private List<CaseView> caseViews(List<InsuranceCase> cases){if(cases.isEmpty())return List.of();List<Long> ids=cases.stream().map(InsuranceCase::getId).toList();List<InsuranceQuote> quotes=quoteRepo.findAllByCaseIdInAndActiveTrueOrderByCaseIdAscTotalPremiumAsc(ids);Map<Long,List<InsuranceQuote>> byCase=quotes.stream().collect(Collectors.groupingBy(InsuranceQuote::getCaseId));Map<Long,List<InsurancePremiumPayment>> payments=paymentRepo.findAllByCaseIdInAndActiveTrueOrderByCaseIdAscCreatedOnDesc(ids).stream().collect(Collectors.groupingBy(InsurancePremiumPayment::getCaseId));Map<Long,InsuranceCompany> companies=companyRepo.findAllById(quotes.stream().map(InsuranceQuote::getCompanyId).distinct().toList()).stream().collect(Collectors.toMap(InsuranceCompany::getId,x->x));boolean internal=staff();return cases.stream().map(c->new CaseView(c.getId(),c.getReference(),c.getProductCode(),c.getStatus(),c.getFullName(),c.getEmail(),c.getPhone(),c.getSubjectType(),c.getSubjectDescription(),c.getSumInsured(),c.getCurrency(),c.getCoverStartDate(),c.getRiskDetails(),proposalData(c.getProposalDataJson()),c.getAssignedAdviserId(),c.getSubmittedAt(),c.getSelectedQuoteId(),byCase.getOrDefault(c.getId(),List.of()).stream().filter(q->internal||!"DRAFT".equals(q.getStatus())).map(q->quoteView(q,companies.get(q.getCompanyId()))).toList(),payments.getOrDefault(c.getId(),List.of()).stream().map(this::paymentView).toList())).toList();}

 private void validateProposal(String product,String subject,Map<String,Object> data){
  if(data==null)throw invalid();
  switch(product){
    case "MOTOR"->{requiredRows(data,"vehicles","insuredType","registrationNumber","makeModel","driverAge","estimatedValue");positiveRows(data,"vehicles","estimatedValue");for(Object row:(List<?>)data.get("vehicles")){Map<?,?> vehicle=(Map<?,?>)row;String insuredType=String.valueOf(vehicle.get("insuredType"));if(!Set.of("VEHICLE","TRAILER","PRIME_MOVER","BUS","PSV","TOUR_VAN","SPECIAL_TYPE").contains(insuredType))throw invalid();if("SPECIAL_TYPE".equals(insuredType)&&(vehicle.get("specialType")==null||String.valueOf(vehicle.get("specialType")).isBlank()))throw invalid();BigDecimal age=number(vehicle.get("driverAge"));if(age.stripTrailingZeros().scale()>0||age.compareTo(BigDecimal.valueOf(16))<0||age.compareTo(BigDecimal.valueOf(100))>0)throw invalid();}}
    case "DOMESTIC"->{requiredRows(data,"domesticItems","propertyLocation","itemDescription","value");positiveRows(data,"domesticItems","value");if("PROPERTY".equals(subject)){if(!hasAssignedRole(PMSRole.LANDLORD))throw forbidden();}else if("HOUSEHOLD_ITEMS".equals(subject)){if(!hasAssignedRole(PMSRole.LANDLORD)&&!hasAssignedRole(PMSRole.TENANT))throw forbidden();}else throw invalid();}
   case "FIRE_ALLIED"->{requiredRows(data,"insuredItems","description","value");positiveRows(data,"insuredItems","value");}
   case "WIBA_EL"->{requiredRows(data,"workforce","jobDescription","monthlySalary","employeeCount");positiveRows(data,"workforce","monthlySalary","employeeCount");}
    case "CONTRACTORS_ALL_RISK","ALL_RISKS"->{requiredRows(data,"projects","projectValue","projectName","projectSiteLocation","constructionType","thirdPartyLiabilityEstimate");positiveRows(data,"projects","projectValue","thirdPartyLiabilityEstimate");}
    case "MEDICAL"->{if("CORPORATE".equals(subject)){required(data,"companyName");requiredRows(data,"staffMembers","fullName","dateOfBirth","gender");allowed(data,"waitingPeriod",Set.of("WAITING_PERIOD","NO_WAITING_PERIOD"));genderRows(data,"staffMembers");}else if("FAMILY_INDIVIDUAL".equals(subject)){required(data,"clientDateOfBirth");allowed(data,"clientGender",Set.of("MALE","FEMALE"));positive(data,"inPatientLimit");if(Boolean.TRUE.equals(data.get("outPatientRequired")))allowed(data,"outPatientBasis",Set.of("SHARED","PER_PERSON"));optionalRows(data,"otherMembers","fullName","dateOfBirth","gender");genderRows(data,"otherMembers");}else throw invalid();}
    case "MARINE_CARGO"->{requiredRows(data,"consignments","idfNumber","transportMode","estimatedCargoValue");positiveRows(data,"consignments","estimatedCargoValue");allowedRows(data,"consignments","transportMode",Set.of("SEA","AIR"));}
    case "TRAVEL"->{requiredRows(data,"trips","dateOfBirth","travelDuration","destination","purpose");}
    case "GOODS_IN_TRANSIT"->{requiredRows(data,"cargoItems","cargoDescription","singleCarryValue","annualCarryValue");positiveRows(data,"cargoItems","singleCarryValue","annualCarryValue");required(data,"conveyanceMode");required(data,"territorialLimits");required(data,"packaging");required(data,"temporaryGarageSafety");allowed(data,"usesHiredVehicles",Set.of("YES","NO"));allowed(data,"trackingDevices",Set.of("YES","NO"));allowed(data,"engineImmobilizers",Set.of("YES","NO"));allowed(data,"specifiedVehicleCover",Set.of("YES","NO"));if("YES".equals(data.get("usesHiredVehicles")))required(data,"hiredVehicleDetails");if("YES".equals(data.get("specifiedVehicleCover"))){requiredRows(data,"specifiedVehicles","vehicleType","make","registrationNumber","tonnage","sumInsured");positiveRows(data,"specifiedVehicles","tonnage","sumInsured");for(Object row:(List<?>)data.get("specifiedVehicles")){Map<?,?> vehicle=(Map<?,?>)row;if(!Set.of("PRIME_MOVER","TRAILER").contains(String.valueOf(vehicle.get("vehicleType"))))throw invalid();}}}
   default->throw invalid();
  }
 }
 private void required(Map<String,Object> data,String key){Object value=data.get(key);if(value==null||value instanceof String s&&s.isBlank())throw invalid();}
 private void requiredRows(Map<String,Object> data,String key,String...fields){Object value=data.get(key);if(!(value instanceof List<?> rows)||rows.isEmpty())throw invalid();validateRows(rows,fields);}
 private void optionalRows(Map<String,Object> data,String key,String...fields){Object value=data.get(key);if(value==null)return;if(!(value instanceof List<?> rows))throw invalid();validateRows(rows,fields);}
 private void validateRows(List<?> rows,String...fields){if(rows.size()>100)throw invalid();for(Object row:rows){if(!(row instanceof Map<?,?> values))throw invalid();for(String field:fields){Object item=values.get(field);if(item==null||String.valueOf(item).isBlank()||String.valueOf(item).length()>1000)throw invalid();}}}
 private void allowed(Map<String,Object> data,String key,Set<String> values){required(data,key);if(!values.contains(String.valueOf(data.get(key))))throw invalid();}
 private void allowedRows(Map<String,Object> data,String key,String field,Set<String> values){Object value=data.get(key);if(!(value instanceof List<?> rows)||rows.isEmpty())throw invalid();for(Object row:rows){if(!(row instanceof Map<?,?> fields)||!values.contains(String.valueOf(fields.get(field))))throw invalid();}}
 private BigDecimal number(Object value){try{return new BigDecimal(String.valueOf(value));}catch(NumberFormatException exception){throw invalid();}}
 private void positive(Map<String,Object> data,String key){required(data,key);if(number(data.get(key)).signum()<=0)throw invalid();}
 private void positiveRows(Map<String,Object> data,String key,String...fields){Object value=data.get(key);if(value==null)return;if(!(value instanceof List<?> rows))throw invalid();for(Object row:rows){if(!(row instanceof Map<?,?> values))throw invalid();for(String field:fields)if(number(values.get(field)).signum()<=0)throw invalid();}}
 private void genderRows(Map<String,Object> data,String key){Object value=data.get(key);if(value==null)return;if(!(value instanceof List<?> rows))throw invalid();for(Object row:rows){if(!(row instanceof Map<?,?> values)||!Set.of("MALE","FEMALE").contains(String.valueOf(values.get("gender"))))throw invalid();}}
 private Map<String,Object> normalizedProposal(String product,Map<String,Object> data){Map<String,Object> normalized=new LinkedHashMap<>(data);if("WIBA_EL".equals(product)){List<Map<String,Object>> workforce=new ArrayList<>();for(Object item:(List<?>)data.get("workforce")){Map<?,?> source=(Map<?,?>)item;Map<String,Object> row=new LinkedHashMap<>();source.forEach((key,value)->row.put(String.valueOf(key),value));BigDecimal monthlySubtotal=number(source.get("monthlySalary")).multiply(number(source.get("employeeCount")));row.put("monthlySubtotal",monthlySubtotal);row.put("annualSalary",monthlySubtotal.multiply(BigDecimal.valueOf(12)));workforce.add(row);}normalized.put("workforce",workforce);}BigDecimal total=calculatedSumInsured(product,normalized);if(total!=null)normalized.put(totalKey(product),total);if("CONTRACTORS_ALL_RISK".equals(product))normalized.put("totalThirdPartyLiability",sumRows(normalized,"projects","thirdPartyLiabilityEstimate"));if("GOODS_IN_TRANSIT".equals(product)){normalized.put("totalEstimatedSingleCarry",sumRows(normalized,"cargoItems","singleCarryValue"));if("YES".equals(normalized.get("specifiedVehicleCover")))normalized.put("totalSpecifiedVehicleValue",sumRows(normalized,"specifiedVehicles","sumInsured"));}return normalized;}
 private BigDecimal calculatedSumInsured(String product,Map<String,Object> data){return switch(product){case "MOTOR"->sumRows(data,"vehicles","estimatedValue");case "DOMESTIC"->sumRows(data,"domesticItems","value");case "FIRE_ALLIED"->sumRows(data,"insuredItems","value");case "WIBA_EL"->sumRows(data,"workforce","annualSalary");case "CONTRACTORS_ALL_RISK"->sumRows(data,"projects","projectValue");case "MARINE_CARGO"->sumRows(data,"consignments","estimatedCargoValue");case "GOODS_IN_TRANSIT"->sumRows(data,"cargoItems","annualCarryValue");default->null;};}
 private String totalKey(String product){return switch(product){case "WIBA_EL"->"totalAnnualPayroll";case "CONTRACTORS_ALL_RISK"->"totalContractValue";case "MARINE_CARGO"->"totalEstimatedCargoValue";case "GOODS_IN_TRANSIT"->"totalEstimatedAnnualCarry";default->"totalEstimatedValue";};}
 private BigDecimal sumRows(Map<String,Object> data,String collection,String field){Object value=data.get(collection);if(!(value instanceof List<?> rows))throw invalid();BigDecimal total=BigDecimal.ZERO;for(Object item:rows){if(!(item instanceof Map<?,?> row))throw invalid();total=total.add(number(row.get(field)));}return total;}
 private boolean hasAssignedRole(PMSRole role){return userRoleRepo.findByUserId(uid()).stream().anyMatch(assigned->role.getName().equals(assigned.getName()));}
 private String proposalJson(Map<String,Object> data){try{return objectMapper.writeValueAsString(data);}catch(Exception e){throw invalid();}}
 private Map<String,Object> proposalData(String json){if(StringUtils.isBlank(json))return Map.of();try{return objectMapper.readValue(json,new TypeReference<>(){});}catch(Exception e){return Map.of();}}
 private QuoteView quoteView(InsuranceQuote q){return quoteView(q,companyRepo.findById(q.getCompanyId()).orElseThrow(this::notFound));}
 private QuoteView quoteView(InsuranceQuote q,InsuranceCompany co){if(co==null)throw notFound();return new QuoteView(q.getId(),co.getId(),co.getCode(),co.getName(),q.getQuoteNumber(),q.getStatus(),q.getCurrency(),q.getBasePremium(),q.getTaxesLevies(),q.getTotalPremium(),q.getExcessDetails(),q.getCoverageSummary(),q.getExclusions(),q.getValidUntil());}
 private PaymentView paymentView(InsurancePremiumPayment p){return new PaymentView(p.getId(),p.getQuoteId(),p.getPaymentConfigurationId(),p.getAmount(),p.getCurrency(),p.getPaymentReference(),p.getPaidAt(),p.getStatus(),p.getRejectionReason(),p.getRemittanceReference(),p.getRemittedAt(),StringUtils.isNotBlank(p.getProofFileRef()),p.getProofContentType());}
 private InsurancePaymentConfiguration paymentConfiguration(InsuranceQuote quote,Long requestedId,LocalDate paidOn){List<InsurancePaymentConfiguration> candidates=requestedId==null?paymentConfigurationRepo.findByCompanyIdAndActiveTrueOrderByPaymentChannelAsc(quote.getCompanyId()):paymentConfigurationRepo.findById(requestedId).filter(InsurancePaymentConfiguration::isActive).stream().toList();List<InsurancePaymentConfiguration> valid=candidates.stream().filter(c->Objects.equals(c.getCompanyId(),quote.getCompanyId())).filter(c->!c.getEffectiveFrom().isAfter(paidOn)).filter(c->c.getEffectiveTo()==null||!c.getEffectiveTo().isBefore(paidOn)).filter(this::verifiedInsuranceAccount).toList();if(valid.size()!=1)throw invalid();return valid.get(0);}
 private boolean verifiedInsuranceAccount(InsurancePaymentConfiguration c){AccountDTO account=accountService.getAccountStatus(c.getPaymentAccountId());return account.active()&&account.verified()&&account.category()==AccountCategory.INSURANCE&&account.channel()==c.getPaymentChannel();}
 private PolicyView policyView(InsurancePolicy p){return policyViews(List.of(p)).getFirst();}
 private List<PolicyView> policyViews(List<InsurancePolicy> policies){if(policies.isEmpty())return List.of();Map<Long,InsuranceCase> cases=caseRepo.findAllById(policies.stream().map(InsurancePolicy::getCaseId).distinct().toList()).stream().collect(Collectors.toMap(InsuranceCase::getId,x->x));Map<Long,InsuranceCompany> companies=companyRepo.findAllById(policies.stream().map(InsurancePolicy::getCompanyId).distinct().toList()).stream().collect(Collectors.toMap(InsuranceCompany::getId,x->x));return policies.stream().map(p->{InsuranceCase c=cases.get(p.getCaseId());InsuranceCompany co=companies.get(p.getCompanyId());if(c==null||co==null)throw notFound();return new PolicyView(p.getId(),p.getCaseId(),p.getPolicyNumber(),co.getName(),c.getProductCode(),p.getStatus(),p.getStartDate(),p.getEndDate(),p.getRenewalStatus());}).toList();}
 private ClaimView claimView(InsuranceClaim c){return claimViews(List.of(c)).getFirst();}
 private List<ClaimView> claimViews(List<InsuranceClaim> claims){if(claims.isEmpty())return List.of();Map<Long,InsurancePolicy> policies=policyRepo.findAllById(claims.stream().map(InsuranceClaim::getPolicyId).distinct().toList()).stream().collect(Collectors.toMap(InsurancePolicy::getId,x->x));return claims.stream().map(c->{InsurancePolicy p=policies.get(c.getPolicyId());if(p==null)throw notFound();return new ClaimView(c.getId(),c.getPolicyId(),p.getPolicyNumber(),c.getReference(),c.getStatus(),c.getIncidentAt(),c.getIncidentLocation(),c.getDescription(),c.getEstimatedAmount(),c.getInsurerReference(),c.getResolutionNotes());}).toList();}
 private DocumentView documentView(InsuranceDocument d){return new DocumentView(d.getId(),d.getCaseId(),d.getPolicyId(),d.getClaimId(),d.getCategory(),d.getDisplayName(),d.getContentType(),d.getFileSize(),d.getChecksumSha256(),garageService.getPresignedUrlForStoredObject(d.getFileRef()),d.getVersionNumber());}
 private InsuranceAgency agencyEntity(){return agencyRepo.findByCodeAndActiveTrue(AGENCY).orElseThrow(this::notFound);}
 private InsuranceCase ownedCase(long id){return caseRepo.findByIdAndCustomerUserIdAndActiveTrue(id,uid()).orElseThrow(this::notFound);}
 private InsuranceCase lockedCase(long id){return caseRepo.findByIdForUpdate(id).filter(x->x.getAgencyId()==agencyEntity().getId()).orElseThrow(this::notFound);}
 private InsuranceCase lockedOwnedCase(long id){InsuranceCase c=lockedCase(id);if(c.getCustomerUserId()!=uid())throw notFound();return c;}
 private long resolveOwner(Long caseId,Long policyId,Long claimId){if(caseId!=null)return caseForAgency(caseId).getCustomerUserId();if(policyId!=null){InsurancePolicy p=policyRepo.findById(policyId).filter(x->x.isActive()).orElseThrow(this::notFound);caseForAgency(p.getCaseId());return p.getCustomerUserId();}if(claimId!=null){InsuranceClaim c=claimRepo.findById(claimId).filter(x->x.isActive()).orElseThrow(this::notFound);InsurancePolicy p=policyRepo.findById(c.getPolicyId()).filter(x->x.isActive()).orElseThrow(this::notFound);caseForAgency(p.getCaseId());return c.getCustomerUserId();}throw invalid();}
 private InsuranceCase caseForAgency(long id){long agencyId=agencyEntity().getId();return caseRepo.findById(id).filter(x->x.isActive()&&x.getAgencyId()==agencyId).orElseThrow(this::notFound);}
 private void transition(InsuranceCase c,String to,String event,String note){String from=c.getStatus();c.setStatus(to);caseRepo.save(c);activity(c.getId(),null,event,from,to,note);}
 private void activity(Long caseId,Long claimId,String event,String from,String to,String note){InsuranceActivity a=new InsuranceActivity();a.setCaseId(caseId);a.setClaimId(claimId);a.setEventType(event);a.setFromStatus(from);a.setToStatus(to);a.setNote(StringUtils.trimToNull(note));a.setActorUserId(uid());stamp(a);activityRepo.save(a);}
 private byte[] validate(MultipartFile f)throws IOException{if(f==null||f.isEmpty()||f.getSize()>MAX_FILE||!TYPES.contains(f.getContentType()))throw new PMSCustomException(ResponseCode.UNSUPPORTED_MEDIA_TYPE);byte[] b=f.getBytes();boolean ok="application/pdf".equals(f.getContentType())?b.length>4&&b[0]=='%'&&b[1]=='P'&&b[2]=='D'&&b[3]=='F':"image/png".equals(f.getContentType())?b.length>8&&(b[0]&255)==0x89&&b[1]=='P'&&b[2]=='N'&&b[3]=='G':b.length>3&&(b[0]&255)==0xff&&(b[1]&255)==0xd8;if(!ok)throw new PMSCustomException(ResponseCode.UNSUPPORTED_MEDIA_TYPE);malwarePolicy.requireSafe(b);return b;}
 private String path(long owner,String folder,MultipartFile f){String n=safeName(f.getOriginalFilename()),ext=n.contains(".")?n.substring(n.lastIndexOf('.')).toLowerCase(Locale.ROOT):"";return "insurance/"+AGENCY.toLowerCase(Locale.ROOT)+"/"+owner+"/"+folder+"/"+UUID.randomUUID()+ext;}
 private String safeName(String n){String s=StringUtils.defaultIfBlank(n,"document").replaceAll("[^A-Za-z0-9._ -]","_");return s.length()>255?s.substring(s.length()-255):s;}
 private String hash(byte[] b){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(b));}catch(Exception e){throw new IllegalStateException(e);}}
 private String ref(String prefix){return prefix+"-"+LocalDate.now().getYear()+"-"+UUID.randomUUID().toString().substring(0,8).toUpperCase(Locale.ROOT);}
 private void notifyEmail(String email,NotificationType type,Object...args){Object[] safe=Arrays.stream(args).map(x->HtmlUtils.htmlEscape(Objects.toString(x,""))).toArray();String body=String.format(i18n.getLocalizedMessage(type.getBody()),safe);notifications.queueNotification(new NotificationDTO(body,email,type));}
 private boolean staff(){var authentication=SecurityContextHolder.getContext().getAuthentication();return authentication!=null&&authentication.getAuthorities().stream().map(Object::toString).anyMatch(a->Set.of("review_insurance_applications","manage_insurance_quotes","manage_insurance_claims","manage_insurance_renewals","issue_insurance_policies").contains(a));}
 private long uid(){return userDao.getUserId();} private void stamp(org.pms.silverocean.database.pms.entities.base.BaseCreatorEntity e){e.setCreatedBy(uid());e.setActive(true);} private PMSCustomException invalid(){return new PMSCustomException(ResponseCode.INVALID_FIELD_DATA);} private PMSCustomException notFound(){return new PMSCustomException(ResponseCode.RESOURCE_NOT_FOUND);} private PMSCustomException forbidden(){return new PMSCustomException(ResponseCode.FORBIDDEN_ACCESS);}
}
